### ISSUE TITLE
Cannot pull from/push to docker registry using an escaped ipv6 address literal

### ISSUE THREAD

**Issue by cboylan** [containers/image#1004]
Running a command like:

```
skopeo copy docker://[2607:ff68:100:54:f816:3eff:fef2:fc69]:5000/zuul/nodepool:latest docker://insecure-ci-registry.opendev.org:5000/zuul/nodepool:12345_latest
```

We get:

```
Invalid source name docker://[2607:ff68:100:54:f816:3eff:fef2:fc69]:5000/zuul/nodepool:latest: invalid reference format
```

Ideally we would be able to use properly escaped ipv6 address literals with a port specified and still have skopeo function.

Chances are this is related to https://github.com/docker/distribution/pull/2899 and its related bug as I'm guessing skopeo pulls in that set of regexes to validate the url. Unfortunately that means that while docker is broken so is skopeo. I'm hoping that my PR there will end up in docker being fixed, but am also wondering if it is possible for skopeo to handle this properly even if docker doesn't?

**Comment by rhatdan** [comment]
We believe this is too complicated a change and too risky.  Since this can easily be worked around by using names rather then address, I am going to close.

**Comment by uablrek** [comment]
When a [local registry](https://distribution.github.io/distribution/) is used, it has no name but an address:
```
docker run -d --restart=always --name registry \
  -e REGISTRY_STORAGE_DELETE_ENABLED=true \
  -e REGISTRY_HTTP_ADDR=:80 registry:2
# Get the address to the registry;
docker inspect registry | jq -r .[0].NetworkSettings.GlobalIPv6Address
fd00:8000::242:ac11:2
```
