### ISSUE TITLE
Error writing manifest to GCR, fails with 200 status code

### ISSUE THREAD

**Issue by bcaton85** [containers/image#1006]
I'm currently attempting to copy an image from an Openshift registry to Google Container Registry. The skopeo command is running from within one of the pods in Openshift. Find the command below:

 `skopeo --debug copy --src-creds username:pass --dest-creds oauth2accesstoken:pass docker://<openshift-reg>/<project>/<image>:<tag>
docker://gcr.io/<project>/<image>:<tag>`

I get an error when writing to manifest during the last step with "Error body ". Find the debug output below:

`Writing manifest to image destination
time="2019-08-28T12:33:29Z" level=debug msg="PUT https://gcr.io/v2/<project>/<image>/manifests/latest" 
time="2019-08-28T12:33:30Z" level=debug msg="Error body " 
time="2019-08-28T12:33:30Z" level=debug msg="Error uploading manifest, status 200, &http.Response{Status:\"200 OK\", StatusCode:200, Proto:\"HTTP/1.1\", ProtoMajor:1, ProtoMinor:1, Header:http.Header{\"Docker-Distribution-Api-Version\":[]string{\"registry/2.0\"}, \"Server\":[]string{\"Docker Registry\"}, \"Alt-Svc\":[]string{\"quic=\\\":443\\\"; ma=2592000; v=\\\"46,43,39\\\"\"}, \"Content-Length\":[]string{\"0\"}, \"X-Frame-Options\":[]string{\"SAMEORIGIN\"}, \"X-Xss-Protection\":[]string{\"0\"}, \"Date\":[]string{\"Wed, 28 Aug 2019 12:33:29 GMT\"}, \"Location\":[]string{\"https://gcr.io/v2/<project>/<image>/manifests/latest\"}, \"Content-Type\":[]string{\"text/html\"}, \"Docker-Content-Digest\":[]string{\"sha256:621cf20722bccba3264b0485fc96481a4672c1a30c2f3786f80a1c4ede41555b\"}}, Body:(*struct { http.eofReaderWithWriteTo; io.Closer })(0xefdc10), ContentLength:0, TransferEncoding:[]string(nil), Close:true, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc4201ae4b0), TLS:(*tls.ConnectionState)(0xc4200c6630)}" 
time="2019-08-28T12:33:30Z" level=fatal msg="Error writing manifest: Error uploading manifest to /v2/<project>/<image>/manifests/latest, status 200" `

It seems to be an error when parsing the response body from the GCR endpoint. Is there a solution to this? Thanks.

**Comment by mtrmac** [comment]
Actually, status `200` was no longer required after https://github.com/containers/image/pull/382 . Even the exact text of the message, `Error uploading manifest, status` points at code as of https://github.com/containers/image/pull/264 or earlier; more than two years older than the original bug report.

So I’m fairly certain that this was fixed — it was probably fixed in a recent Skopeo version already by the time of the bug report.
