### ISSUE TITLE
Work around docker/distribution servers that don't include the JSON body on error

### ISSUE THREAD

**Issue by bparry02** [containers/image#1007]
I have a docker-distribution registry configured with `storage.maintenance.readonly.enabled: true` which prevents writes to the registry. When I run `skopeo copy`, I see an error message that fails to parse the body of the response.

Instead, I expect to see a simple message, such as "copy: Method not allowed" or something similar.

```
# skopeo copy --dest-tls-verify=false docker-daemon:registry.redhat.io/rhel7.7:latest docker://127.0.0.1:5000/rhel7.7:latest
Getting image source signatures
Copying blob 506371554037 done
Copying blob 893590530078 done
FATA[0002] Error writing blob: Error initiating layer upload to /v2/rhel7.7/blobs/uploads/ in 127.0.0.1:5000: error parsing HTTP 405 response body: invalid character 'M' looking for beginning of value: "Method not allowed\n" 
```

**Comment by rhatdan** [comment]
@mtrmac Are you planning on working on this, or should we put @QiWang19 on it?

**Comment by mtrmac** [comment]
@rhatdan I probably won’t work on this this week. (Most of the error handling in c/image/docker is already fairly centralized, so this should be a fairly small change.)

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
What workaround is needed? Define `error parsing HTTP 405 response body: invalid character 'M' looking for beginning of value: "Method not allowed` as an error and check if the failure is caused by that kind of error?

**Comment by mtrmac** [comment]
That’s already a typed error (`UnexpectedHTTPResponseError` I think), and it contains the full HTTP response body.

A workaround would be to check if that body looks like a non-JSON plain text string, or possibly HTML, and output some other kind of error. In a sense it would be nice to preserve the `UnexpectedHTTPResponseError` type and only wrap it, but that would not get rid of the visual noise, and we don’t document that type — so, probably just a plain-text error that contains the HTTP status and possibly the body if it is not too big.
