### ISSUE TITLE
Cannot delete image from Artifactory

### ISSUE THREAD

**Issue by nc-nvmt** [containers/image#1009]
This issue have been already mentioned once [here](https://github.com/containers/skopeo/issues/463#issuecomment-398445931)

I am able to inspect/copy the image on Artifactory but I got 406 Not acceptable why I tried to delete the image

The issue above state that is to enable delete config for Docker Registry. However I could not found any document relate to modify config.yml of Artifactory Docker Registry

I obtain the folllowing error
```$ skopeo --debug delete docker://<REGISTRY>/<IMAGE>:<VERSION> --creds=<U>:<P>
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/atomic/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/<REGISTRY>
DEBU[0000] GET https://<REGISTRY>/v2/
DEBU[0000] Ping https://<REGISTRY>/v2/ err <nil>
DEBU[0000] Ping https://<REGISTRY>/v2/ status 401
DEBU[0001] GET https://<REGISTRY>/v2/<IMAGE>/manifests/<VERSION>
DEBU[0002] DELETE https://<REGISTRY>/v2/<IMAGE>/manifests/sha256:<SHA>
FATA[0003] Failed to delete /v2/<IMAGE>/manifests/sha256:<SHA>: {
  "errors" : [ {
    "status" : 406,
    "message" : "Not Acceptable"
  } ]
} (406 Not Acceptable)
```

It would be nice to support Artifactory too. We distribute our images to both Artifactory and Openshift Regsitry so right now we need 2 different tool (jfrog cli and skopeo) to cleanup images

**Comment by Pvlerick** [comment]
Hello, I'm taking a look at this; I'll keep you posted :-)

**Comment by Pvlerick** [comment]
Well, this is now supported by Artifactory (at least in 7.46.11 where I just tested it).

I'm not sure if it's worth it to make a fix for older version, it's hard to find out when exactly this was fixed, if documented at all...

**Comment by rhatdan** [comment]
SGTM
