### ISSUE TITLE
Deletion fails when used against AWS ECR repository

### ISSUE THREAD

**Issue by agora9** [containers/image#1010]
Is AWS ECR supported by skopeo?

I'm trying to use skopeo to inspect and delete images in an AWS ECR repository, however, the `delete` command fails with the following output:

```
skopeo --debug delete docker://xxxxxxxxxxxx.dkr.ecr.region.amazonaws.com/repo_name:tag_to_delete
DEBU[0000] Returning credentials from /root/.docker/config.json
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/xxxxxxxxxxxx.dkr.ecr.region.amazonaws.com
DEBU[0000] GET https://xxxxxxxxxxxx.dkr.ecr.region.amazonaws.com/v2/
DEBU[0000] Ping https://xxxxxxxxxxxx.dkr.ecr.region.amazonaws.com/v2/ status 401
DEBU[0000] GET https://xxxxxxxxxxxx.dkr.ecr.region.amazonaws.com/v2/repo_name/manifests/tag_to_delete
DEBU[0000] DELETE https://xxxxxxxxxxxx.dkr.ecr.region.amazonaws.com/v2/repo_name/manifests/
FATA[0000] Failed to delete /v2/repe_name/manifests/: 404 page not found
(404 Not Found)
```

The `inspect` and `copy` commands operate normally.

To verify this is not an access issue I've used AWS CLI's [`batch-delete-image`](https://docs.aws.amazon.com/AmazonECR/latest/userguide/delete_image.html) command to delete `repo_name:tag_to_delete`. This operation was successful.

**Comment by graywolf-at-work** [comment]
Hello, I have encountered the same issue, and deleting using a digest does not seem to work:

```
+ skopeo delete --debug docker://XXXXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/XXXXXX/YYYYYY@sha256:cb92f03e258f965442b883f5402b310dd7a5ea0a661a865ad02a42bc21234bf7
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/00-shortnames.conf"
DEBU[0000] Found credentials for XXXXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/XXXXXX/YYYYYY in credential helper containers-auth.json in file /run/user/1000/containers/auth.json
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/XXXXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com
DEBU[0000] GET https://XXXXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/v2/
DEBU[0000] Ping https://XXXXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/v2/ status 401
DEBU[0000] GET https://XXXXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/v2/XXXXXX/YYYYYY/manifests/sha256:cb92f03e258f965442b883f5402b310dd7a5ea0a661a865ad02a42bc21234bf7
DEBU[0000] DELETE https://XXXXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/v2/XXXXXX/YYYYYY/manifests/
FATA[0000] Failed to delete /v2/XXXXXX/YYYYYY/manifests/: 404 page not found
 (404 Not Found)
```

```
+:( $ skopeo --version
skopeo version 1.6.1 commit: 49084d2cd8c9f8e7b38ba8405d61e701d5381bc0
```

However is deleting by digest actual correct replacement (even if it worked)? Since that would delete the digest and all tags associated with it, instead of just the one tag (and refcount clean up the image when no tags are left), no?

**Comment by mtrmac** [comment]
@graywolf-at-work Thanks for the confirmation. Could you test that #1497 makes a difference, please?

---

> However is deleting by digest actual correct replacement (even if it worked)? Since that would delete the digest and all tags associated with it, instead of just the one tag (and refcount clean up the image when no tags are left), no?

See https://github.com/containers/skopeo/issues/795 and the linked issues. Historically, deleting the manifest (and implicitly all tags) was the only operation exposed by the API. That’s no longer the case, after https://github.com/opencontainers/distribution-spec/commit/c90b0f145ac6bc09d2636ee214486ac333edc284?short_path=bc6661d#diff-bc6661da34ecae62fbe724bb93fd69b91a7f81143f2683a81163231de7e3b545 .

It’s a fair point that we should probably change the behavior; but it’s a separate issue from the AWS ECR interoperability problem.

**Comment by graywolf-at-work** [comment]
> Could you test that #1497 makes a difference, please?

What I did:

1. git-clone skopeo repository
2. cd vendor/github.com/containers/image
3. patch -p1 from https://patch-diff.githubusercontent.com/raw/containers/image/pull/1497.patch

```
patching file docker/docker_image_src.go
Hunk #1 succeeded at 602 (offset -8 lines).
Hunk #2 succeeded at 624 (offset -8 lines).
```

4. back to repo root and make bin/skopeo
5. skopeo copy docker://alpine:3.15.1 docker://X.dkr.ecr.eu-west-2.amazonaws.com/X/Y:3.15.1

```
Getting image source signatures
Copying blob 3d2430473443 done
Copying config e9adb5357e done
Writing manifest to image destination
Storing signatures
```

6. ./bin/skopeo delete docker://X.dkr.ecr.eu-west-2.amazonaws.com/X/Y:3.15.1

```
FATA[0000] Failed to delete /v2/X/Y/manifests/sha256:14b55f5bb845c7b810283290ce057f175de87838be56f49060e941580032c60c: 404 page not found
 (404 Not Found)
```

So it does not look like the patch helped (assuming I did the build right).

> Historically, deleting the manifest (and implicitly all tags) 

Oh my. I feel like this should be written somewhere in skopeo-delete(1), since
this is not what I would expect to happen.

**Comment by mtrmac** [comment]
> So it does not look like the patch helped (assuming I did the build right).

Thank you very much. Good news/bad news: The patch made a difference, but the registry seems to just not support this operation. So, mostly bad news.

Reference: https://github.com/aws/containers-roadmap/issues/1229 .

It seems to be possible to delete an image using an AWS-specific API (https://github.com/goharbor/harbor/pull/10453/files ), which is a bit unattractive.

---

> > Historically, deleting the manifest (and implicitly all tags)
> 
> Oh my. I feel like this should be written somewhere in skopeo-delete(1), since this is not what I would expect to happen.

That’s a very fair point. I’m afraid significantly improving the delete code (as discussed in https://github.com/containers/skopeo/issues/1432 and here) is not something I can work on right now (so many registries just disable deletion by default, making it somewhat obscure), but making this clearer is certainly worth doing: https://github.com/containers/skopeo/pull/1597 .

**Comment by graywolf-at-work** [comment]
I worked around this by using awscli, which is not as straight forward as skopeo delete, but works in my circumstances. The deletion of all tags would be a blocker for me anyway.

I completely understand the lack of time/interest regarding the deletion code and just want to thank you for the pull request for the manual page. I think this is good enough measure for now, at least for me it would suffice. So, thanks :)
