### ISSUE TITLE
oci-archive can't lchown when untarring

### ISSUE THREAD

**Issue by kitforbes** [containers/image#1017]
Hi folks,

We've got a rootless image created with Buildah. The image (with a bunch of irrelevant stuff removed) looks like this
```dockerfile
FROM registry.fedoraproject.org/fedora:32

RUN set -ex; \
  useradd deploy && \
  yum update -y -d 1 && yum install -y -d 1 \
    skopeo \
  && \
  yum clean all && rm -rf /var/cache /var/log/dnf* /var/log/yum.*

USER deploy
WORKDIR /home/deploy
```
The Skopeo version is 1.1.1.

I'm running the image locally through Docker with
```bash
docker run --rm -it --privileged image-name /bin/bash
```

I've downloaded a `tar` which was previously created with `skopeo copy` to create an OCI archive. Then, within the container I'm trying to run
```bash
skopeo copy oci-archive:container.tar docker://somewhere
```
Which results in the error of 
>FATA[0000] Error initializing source oci-archive:container.tar:: error creating temp directory: error untarring file "/var/tmp/oci564737160": lchown /var/tmp/oci564737160/blobs: operation not permitted

I've tried changing the directory in which the untarring occurs with the `--tmpdir` flag, but that hasn't helped so far. I was wondering if someone could point me in the right direction to make this work, and I appreciate that this may just be a Linux issue rather than an issue with Skopeo or one of the libraries. Most likely just my lack of knowledge in this area.

Thanks for your help.

**Comment by rudolpho1** [comment]
Hi @mtrmac do you have any update on this? This issue is a blocker for us as we want to use skopeo to automatically deploy new container images to the production system. And we cannot run it as root. Thanks a lot for your help!

**Comment by TomSweeneyRedHat** [comment]
LGTM
but definitely want a @mtrmac or @vrothberg head nod

**Comment by kitforbes** [comment]
Thanks for the fast turn around folks!
