### ISSUE TITLE
[performance] parallel layers upload/download in copy

### ISSUE THREAD

**Issue by runcom** [containers/image#105]
EDIT: This can be probably done in skopeo

**Comment by mtrmac** [comment]
How, if skopeo only passes source and destination references to `copy.Image`?

**Comment by runcom** [comment]
@mtrmac alright, then this should be implemented at copy level right

**Comment by rhatdan** [comment]
@runcom @mtrmac @vrothberg I think we have this now?  Can we close this?

**Comment by vrothberg** [comment]
Yup, that's done.
