### ISSUE TITLE
sigstore permission denied error is fatal, in a flow where signature check not required

### ISSUE THREAD

**Issue by dctrud** [containers/image#1066]
Version: 5.7.0

We are using `containers/image` in a (probably very unusual) flow in which we are running a `copy.Image()` operation as the 'fake' uid mapped root user within a user namespace. Up to and including 5.6.0 this would work normally. With the changes to 5.7.0 we see a fatal error, e.g.:

```
Error initializing source oci:/root/.singularity/cache/blob:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a: Error reading signatures: open /var/lib/containers/sigstore/library/alpine@sha256=d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e/signature-1: permission denied
```

This occurs in a CircleCI Ubuntu 20.04 VM environment that does not have any of the podman/skopeo etc. stack installed. There is no sigstore under `/var/lib/containers` on the host, and it cannot be created from the uid-mapped `root` in the user namespace.

```
circleci@default-7a59d3ae-2d34-40e7-851c-72869a86ff9b:~$ sudo ls -lah /var/lib/containers
total 12K
drwx------  3 root root 4.0K Oct 23 17:55 .
drwxr-xr-x 48 root root 4.0K Oct 23 17:55 ..
drwx------  2 root root 4.0K Oct 23 17:55 cache
```

In a Fedora Workstation 32 dev environment, where I have used podman/skopeo etc., I do not hit the error.

Though our usage is a bit strange, I'm wondering whether the failure to access the sigstore could be a non-fatal error? We are using an explicit policy that I believe should not require checking a global sigstore if it's not possible:

```
policy := &signature.Policy{
    Default: []signature.PolicyRequirement{signature.NewPRInsecureAcceptAnything()}
}
cp.policyCtx, err = signature.NewPolicyContext(policy)
```

We understand that this is probably very 'edge case'.

Many thanks!

**Comment by mtrmac** [comment]
Thanks for your report.

The error text doesn’t make sense at a first glance: the error is from c/image/docker.getSignaturesFromLookaside , not from c/image/oci (where GetSignatures does nothing). The code seems to have its own implementations if `ImageReference`, though…

Ignoring the OCI part: I could be wrong about this, but an initial guess is that it’s not OK to ignore “permission denied” errors – it might well be a real error and ignoring it could later read to surprising “signature missing” failures.

As for how to work with this, see `c/image/docker.SignatureStorageBaseURL`; there are at least two paths:
- Ship configuration, e.g. via `SystemContext.RegistriesDirPath`, that points at an accessible parent directory (it might well be a non-existent path, just not an inaccessible one).
- Perhaps more naturally, adjust the environment to work with c/image/internal/rootless.GetRootlessEUID; that will cause the GitHub.com/containers ecosystem to recognize that the user is not actually a system administrator, and adjust the default paths and the like accordingly.

**Comment by dctrud** [comment]
Thanks for the pointers! We'll pursue these avenues.
