### ISSUE TITLE
unclosed progress channel leading to leaks

### ISSUE THREAD

**Issue by haircommander** [containers/image#1095]
When inspecting the goroutines from a cri-o instance, I seem to have detected a leak. There are 87 instances of 
```
goroutine 25582655 [chan receive, 8118 minutes]:
github.com/cri-o/cri-o/server.(*Server).pullImage.func1(0xc000a45f80, 0x557988e967a0, 0xc002c14810, 0xc001c4da90, 0x557988eb1380, 0xc003569f80)
	/builddir/build/BUILD/cri-o-c0306f12a6db2dae8f11a2c9f4aeca08bcfab906/_output/src/github.com/cri-o/cri-o/server/image_pull.go:173 +0x91
created by github.com/cri-o/cri-o/server.(*Server).pullImage
	/builddir/build/BUILD/cri-o-c0306f12a6db2dae8f11a2c9f4aeca08bcfab906/_output/src/github.com/cri-o/cri-o/server/image_pull.go:172 +0x85b
```

which comes from:
https://github.com/cri-o/cri-o/blob/release-1.19/server/image_pull.go#L173

I believe we're stuck here because c/image isn't closing the progress channel in all cases. Unfortunately, I do not know which cases these are.

c/image version v5.5.1

**Comment by haircommander** [comment]
cc @saschagrunert

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by mtrmac** [comment]
@haircommander Nothing documents that `copy.Image` ever closes that channel, and AFAICS it never does. So either I’m being stupid, or we can’t change this in order not to break the API, and CRI-O will need to close it itself after `copy.Image` returns on the main goroutine.

**Comment by mtrmac** [comment]
The historical https://github.com/containers/image/pull/219#issuecomment-277606887 (with a WIP api) also suggests that the original intent was for the caller to close the channel.

(I could see an argument that this is a wrong design, as well as an argument that this is the right design, anyway three years after introducing the API we shouldn’t be changing it if it is unambiguous either way.)

**Comment by haircommander** [comment]
that's not a leak, that's a gaping wound

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o/pull/4412 to fix, thanks for your counsel

**Comment by saschagrunert** [comment]
I agree I see it as implementation issue on CRI-O's side, but still that's a tricky one. @haircommander do you think we can close this issue?

**Comment by haircommander** [comment]
I agree with the current behaviour. the caller is the one that creates the channel, so it makes sense to me it'd be the one to be in control of closing it. For some reason I just assumed it'd be closed by c/image. closing this issue because we've fixed it in master
