### ISSUE TITLE
Manifest lists break signatures verification?

### ISSUE THREAD

**Issue by runcom** [containers/image#114]
Probably blocking projectatomic/docker#200 but not really since we never thought well about this scenario.
Right now in docker/docker you can pull an image which its manifest isn't a single manifest (with a digest) but it's a list of manifests.

@mtrmac is this a blocking issue? should we trust all sub-manifests in a manifest list if the manifest list it's signed?

For manifest list (and following the idea from containers/image#99) we could have another field in signedBy with: "manifestList": {prohibit, trustList, trustTarged} and by default is trustList (or is it too open?)

**Comment by mtrmac** [comment]
We’ve been somewhat discussing these things before, e.g. https://github.com/containers/image/pull/25 .

I’m not sure what the best way to handle signatures for manifest lists is ATM. From a security POV, a signed manifest list implicitly authenticates the signed manifests, so, yes, a manifest signature could be accepted for the manifests listed in there.

OTOH that semantics may get messy: 1) download a manifest list 2) choose an item in the list, see the manifest digest; 3) publish/note the digest of the chosen manifest. Now, the user, given 3), can pull `withmanifestlist@sha256:digestfromstep3` to refer to an individual manifest, and there is no obvious way to to from `sha256:digestfromstep3` to the original manifest list (its digest, and tag, if any, are not known), so the signatures on the manifest list cannot be applied to the individual manifest. So, this would argue for attaching signatures to the individual images, not to the manifest list.

To a big extent extent all of this strongly depends on whether the tools (are there any in widespread use?) present manifest lists more as a single “fat” image or more as a directory of individually managed images; the signature UX model should be consistent with the non-signature manifest list UX model.

**Comment by runcom** [comment]
> OTOH that semantics may get messy: 1) download a manifest list 2) choose an item in the list, see the manifest digest; 3) publish/note the digest of the chosen manifest. Now, the user, given 3), can pull withmanifestlist@sha256:digestfromstep3 to refer to an individual manifest, and there is no obvious way to to from sha256:digestfromstep3 to the original manifest list (its digest, and tag, if any, are not known), so the signatures on the manifest list cannot be applied to the individual manifest. So, this would argue for attaching signatures to the individual images, not to the manifest list.

Right...

> I’m not sure what the best way to handle signatures for manifest lists is ATM. From a security POV, a signed manifest list implicitly authenticates the signed manifests, so, yes, a manifest signature could be accepted for the manifests listed in there.

is #115 in line with this though?

**Comment by mtrmac** [comment]
#115 is, AFAICS, OK WRT signing security.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by mtrmac** [comment]
We’ve settled on signing individual images, not the manifest list itself.
