### ISSUE TITLE
support username/password in auth files

### ISSUE THREAD

**Issue by simjnd** [containers/image#1153]
Hey guys!
I'm having an issue with Skopeo where if I have an auth file in this format
```json
{
    "auths": {
        "registry": {
            "username": "<value>",
            "password": "<value>"
        }
    }
}
```
and provide it to Skopeo with the --authfile option, I'm getting an error saying `Error initiating layer upload to <repo> in <registry>: unauthorized: The client does not have permission to push to the repository.`. Whereas if, with the same credentials I create an auth file in this format:
```json
{
    "auths": {
        "registry": {
            "auth": "<username:password in base64>"
        }
    }
}
```
Then I can successfully upload. Is it intentional? Most other container tools I've used recognize both formats so it made me think it might be an issue.

Thank you so much for all the work you guys do on Skopeo, this tool is a lifesaver!

**Comment by TomSweeneyRedHat** [comment]
@vrothberg my guess is that Docker and the others added the un/pwd format after we had implemented the current c/image authfile format and we didn't catch the new allowable format that they were using.

**Comment by mtrmac** [comment]
(Drive-by comment without research:) I _very vaguely_ recall that the internal Docker _implementation_ uses (used?) a single Go data type for in-memory content (where user name and password are distinct clear-text fields) and for the file format (with a single base64-obfuscated fields). It’s quite likely that in addition to this sloppy data structure, the implementation has been, at least at some point, likewise sloppy and left the user name / password data around when loading from files if the base64-obfuscated content is missing.

I can’t recall ever seeing any official documentation of the plain-text version (well, of the `auths` structure at all, really); I might have well missed it.

_If_ the above is correct, and this is originally an undocumented implementation detail of a not-strict-enough configuration parser, I’m honestly not too thrilled about the idea of adding support for an undocumented implementation detail that someone reverse-engineered; it’s a bad precedent.

**Comment by vrothberg** [comment]
Looks like we have to `git log/blame` Moby to see what's going on :)

**Comment by simjnd** [comment]
I'm personally not necessarily advocating in favor of this format, my issue was more so to bring awareness to the discrepancy between Docker and this tool.
If the choice is made not to support it, it may be useful to document it and maybe provide an explicit error message stating you're using a wrong format instead of saying the user specified doesn't have the permission to push, which can causes one to assume the user data has been parsed correctly?

**Comment by vrothberg** [comment]
Thanks, @simjnd. That's an excellent idea.

I suggest to first check whether the format has changed intentionally.  Once we know what happened, we can decide what to do.

**Comment by mtrmac** [comment]
https://github.com/containers/image/issues/1259#issuecomment-861782417 contains some relevant research now, so closing this issue in favor of that one. Please follow #1259 .
