### ISSUE TITLE
README links to wrong godoc

### ISSUE THREAD

**Issue by jawnsy** [containers/image#1154]
Hey there!

Thanks so much for implementing and maintaining this excellent library. I recently gave it a try and it was great (just doing something similar to `skopeo inspect --config`), but I got a little lost at first because the godoc link on the README goes here: https://pkg.go.dev/github.com/containers/image, where the latest version is v1.5.1, rather than to: https://pkg.go.dev/github.com/containers/image/v5

I would suggest adding an instruction for using `go get` to add the correct/latest version to someone's go.mod, and would be happy to create a PR!

**Comment by mrunalp** [comment]
@vrothberg @mtrmac

**Comment by vrothberg** [comment]
Thanks for reaching out, @jawnsy!

I opened https://github.com/containers/image/pull/1156 to update the link.
