### ISSUE TITLE
Image pull computes 2–3× more digests than necessary

### ISSUE THREAD

**Issue by mtrmac** [containers/image#1160]
On the most common pull path, we compute:
- `c/image/copy`:
  - `digestingReader` = digest of the compressed layer (for authenticity)
- `c/image/storage/storageImageDestination.PutBlob`:
  - digest of the compressed layer (for deduplication of metadata during pull + for API conformance of the “write” e.g. when decrypting)
  - digest of the uncompressed layer (for the “lookup side” layer deduplication / reuse across images)
- `c/storage/layerStore.ApplyDiff`:
  - digest of the compressed layer (to record data that allows avoiding layer pulls)
  - digest of the uncompressed layer (to record data that allows avoiding layer pulls)

i.e. each digest is computed at least twice; that should be avoidable by adding some guarantees to the API, and a new c/storage interface that allows the caller to submit pre-computed digest values.

**Comment by mrunalp** [comment]
@vrothberg @rhatdan @nalind @umohnani8 ptal

**Comment by vrothberg** [comment]
I'll be tackling push & pull optimizations this sprint.  Please let me know in case this issue has a higher priority.

**Comment by rhatdan** [comment]
@vrothberg @QiWang19 Any progress on this?  People are noticing...

**Comment by vrothberg** [comment]
I didn't work on it, no.

**Comment by vrothberg** [comment]
@mtrmac, to avoid duplicate work: are you tackling the c/storage parts as well?

**Comment by mtrmac** [comment]
The Jira card is assigned to me, so I’ll work on that.

**Comment by mtrmac** [comment]
Scope extension: Many transports’ `PutBlob` methods unconditionally recompute digests; they shouldn’t. (And we should make the requirement that `PutBlob` callers are required to only submit validated digests official.)

**Comment by mtrmac** [comment]
https://github.com/containers/storage/pull/1003 + https://github.com/containers/image/pull/1352 is the second part.

Scope extension work pending.

**Comment by mtrmac** [comment]
> Scope extension work pending.

The final part will eventually be https://github.com/containers/image/pull/1355 .

**Comment by rhatdan** [comment]
Thanks @mtrmac
