### ISSUE TITLE
mediaType for detached signatures

### ISSUE THREAD

**Issue by vbatts** [containers/image#1161]
Hey all,
likely a quick question, but do the detached container signatures have a mediaType/mime-type associated for them?
(in the event of actually pushing the signature payload as a blob to a registry, and addressing it in an OCI image-index descriptor)

**Comment by vbatts** [comment]
hahahah, @jonjohnsonjr strikes again! https://github.com/containers/image/issues/1159

**Comment by TomSweeneyRedHat** [comment]
@vbatts anytime you want to drop by and self answer a question, feel free!  :smile:
