### ISSUE TITLE
Please rename the master branch to the main branch.

### ISSUE THREAD

**Issue by rhatdan** [containers/image#1227]

**Comment by mtrmac** [comment]
Note that at least Skopeo’s man pages (shipped in various long-supported distributions) link directly to `https://github.com/containers/image/blob/master/docs/…`, so it would be nice to keep those links working. (It might be good enough for those links to continue pointing at a version frozen in time, OTOH that could also cause extra confusion.)

Would it be possible to achieve a transparent redirect, both for git and links like the above? (I haven’t checked, I’m just noting the desire.)

**Comment by rhatdan** [comment]
That is the hope, but so far it is not promising.

**Comment by rhatdan** [comment]
This has been completed.

**Comment by mtrmac** [comment]
> Would it be possible to achieve a transparent redirect, both for git and links like the above?

Not sure about git, but the HTTP links do redirect. Nice.
