### ISSUE TITLE
Documentation on Library usage

### ISSUE THREAD

**Issue by shahzzzam** [containers/image#1229]
Hello, 

Sorry, I couldn't find any Slack channel or a way to reach out the devs.

This is not really an issue so you can close it. But I want to use this as a go library in my project. I am unable to build it on Ubuntu and seems like it is dependent on a gpg library? 

If I use this go module in my project, do I need to install gpg?

My use case is quite simple: To get the Digest of the image without `docker pull`. Are there any docs on how to achieve that, or how to use it as a module? Thanks

**Comment by rhatdan** [comment]
Have you looked at skopeo?

**Comment by shahzzzam** [comment]
I understand that it is a CLI that uses this library, correct?
And I am also not able to build skopeo. [These setup](https://github.com/containers/skopeo/blob/cc3ddf4804995ab69606885c83a9990b84d1de36/install.md#ubuntu) instructions fail for me.

For my use-case, I think I will just import the module for getting the Digest.

I believe the way to get Manifest would be something [like this](https://github.com/containers/skopeo/blob/master/cmd/skopeo/inspect.go#L110)
And then retrieving the Digest from `rawManifest` like [this](https://github.com/containers/skopeo/blob/4e57679c9a85973f8a6115bfc0ccd9940c011b5e/cmd/skopeo/inspect.go#L188)

But, I am trying to find some documentation, for ex, how do I authenticate with a private registry?
I am not sure what [these steps](https://github.com/containers/skopeo/blob/4e57679c9a85973f8a6115bfc0ccd9940c011b5e/cmd/skopeo/inspect.go#L87-L100) actually do.

Would be incredibly helpful if you give me some pointers. 

Thanks

**Comment by rhatdan** [comment]
@vrothberg @mtrmac @lsm5  would be better at helping you out with that.

**Comment by TomSweeneyRedHat** [comment]
@shahzzzam FWIW, most (maybe all) of the developers in this project hangout on the IRC Freenode server on `#podman`, feel free to ask questions related to this project there too.

**Comment by vrothberg** [comment]
Thanks for reaching out!

Did you check out the building instructions in the readme (https://github.com/containers/image#building)?  In short, either you need install a dependency (gpgme-devel) or use `go build -tag containers_image_openpgp`.

> But, I am trying to find some documentation, for ex, how do I authenticate with a private registry?
> I am not sure what these steps actually do.

Many APIs in containers/image use the [types.SystemContext](https://github.com/containers/image/blob/master/types/types.go#L539) to pass around all kinds of information, including credentials in form of an auth config.  You can also find a field for setting an authentication file (see `man containers-auth.json`).
