### ISSUE TITLE
OCI Zstd → schema2 uncompressed manifest conversion fails

### ISSUE THREAD

**Issue by pombredanne** [containers/image#1260]
This fails to run:
>skopeo copy   --insecure-policy docker://ghcr.io/stargz-containers/alpine:3.10.2-zstdchunked docker-archive:ghcr.io-stargz-containers-alpine-3.10.2-zstdchunked

> Getting image source signatures
Copying blob 0e427c87cfcb done  

> FATA[0003] Error creating an updated image manifest: Error during manifest conversion: "application/vnd.oci.image.layer.v1.tar+zstd": zstd compression is not supported for docker images

**Comment by pombredanne** [comment]
> FWIW a possible (costly) workaround: podman pull + podman save should work, because podman save starts with uncompressed data.

Thanks but no thanks! this would assume podman is installed and that I am pulling first ... it would be a whole lot of extra complexity for my use case:

I am fetching arbitrary images using this CLI wrapper here: https://github.com/nexB/scancode.io/blob/a49b2edc8bdd77e910f594ea01ed29ed851541ce/scanpipe/pipes/fetch.py#L132

This is then typically used as an input to a Docker image composition analysis https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/docker.py

**Comment by mtrmac** [comment]
A variant of this is #1604, decrypting OCI into the archive format.

**Comment by mtrmac** [comment]
Note to self: #1932 builds a fix for decryption; the conversion from zstd can be built similarly.
