### ISSUE TITLE
Use golang.org/x/crypto/openpgp for signing

### ISSUE THREAD

**Issue by wlei27** [containers/image#1275]
Now only the verification feature is supported when using the golang.org/x/crypto/openpgp.  What's the cause that signing is not supported with golang.org/x/crypto/openpgp ? Will it be supported in future ?  Thanks!
In addition,  it uses golang.org/x/crypto/openpgp (through ocicrypt) for encryption and decryption now.

**Comment by mtrmac** [comment]
Thanks for your report.

The original reason is that with Go a garbage-collected language, it’s rather difficult to protect private keys (e.g. in pure Go it  is AFAIK impossible to ensure that a key can be completely removed from memory after use). Even the verification-only support is basically a concession to users who didn’t want to link with CGo for marginal uses, but the default intentionally to use GnuPG for that as well.

Also note https://github.com/golang/go/issues/44226 .

**Comment by wlei27** [comment]
@mtrmac Thanks for your explanation and info!
