### ISSUE TITLE
Support pulling from different accounts on same registry

### ISSUE THREAD

**Issue by saschagrunert** [containers/image#1276]
This is the tracking issue for the feature implementation.

#### Summary

- Change the auth.json parsing behavior to allow full URL paths
- Update [the documentation](https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md) to reflect the changed behavior

**Comment by mtrmac** [comment]
Cross-linking https://issues.redhat.com/browse/RUN-1246 .

Do we really want URLs? I’d prefer `host[:port]/ns/…repo` , both because those values are not HTTP-reachable URLs and because it is clearly conflicting with the legacy format of `.dockercfg`.

**Comment by mtrmac** [comment]
#1278 was merged.
