### ISSUE TITLE
use docker/distribution/digest

### ISSUE THREAD

**Issue by runcom** [containers/image#128]
as rightly pointed our here https://github.com/docker/docker/pull/26369#issuecomment-253321368 it would be nice to use `docker/distribution/digest` type and functions instead of just `string`. Anyone? :angel:

**Comment by stevvooe** [comment]
@runcom Let me know if it would be easier to break this out.

**Comment by runcom** [comment]
Sure, we can start transport by transport, starting with the Docker transport under "docker" would be nice

**Comment by Crazykev** [comment]
Did anyone take over this one ?

**Comment by rhatdan** [comment]
@Crazykev I don't think so.

**Comment by runcom** [comment]
I have a branch locally, but feel free to take this over if you want @Crazykev

**Comment by Crazykev** [comment]
@runcom Very glad to help this when getting familiar with this project, thanks @rhatdan

**Comment by stevvooe** [comment]
This was broken out into a separate package: https://github.com/docker/go-digest.

I've also submitted to OCI as a top-level project.

**Comment by mtrmac** [comment]
This has been fixed by #163.
