### ISSUE TITLE
Add a test against skopeo?

### ISSUE THREAD

**Issue by mtrmac** [containers/image#13]
So here is a completely horrible idea: As part of tests, perhaps in `Makefile` and definitely in Travis, checkout `skopeo`, replace the vendored copy with current working directory, and test that skopeo runs and its tests pass.

As I said, completely horrible. But perhaps worth it, at least until most of the transports in this repo grow some real tests.  Merging https://github.com/projectatomic/skopeo/pull/102 and only a week later discovering that it breaks pushing to OpenShift would be pretty awkward…

WDY(all)T?

**Comment by runcom** [comment]
seems fine to me as a temporary workaround until we figure the whole stuff out
