### ISSUE TITLE
“copy --dest-compress-format=zstd --dest-compress-level=20” produces suboptimal compression

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/image#1313]
As discussed at https://github.com/containers/buildah/issues/3321 when `skopeo copy --dest-compress-format=zstd --dest-compress-level=20 containers-storage:localhost/abc oci-archive:t.tar` is used, the t.tar file is not optimally compressed.

Exporting to uncompressed image, and calling then `zstd -19 -k m.tar`  produces much smaller output file.

**Comment by mtrmac** [comment]
Thanks for your report.

The Zstd implementation on the CLI (presumably https://github.com/facebook/zstd ) and the implementation we use ( https://github.com/klauspost/compress/tree/master/zstd ) are different, and may well produce different output or even accept different options.

If there is something we are doing wrong in _invoking_ the compression implementation, that would certainly be interesting to know and to fix. (It might be relevant that https://github.com/klauspost/compress/blob/94867dd0db717f2a857a73816da3522e06536a16/zstd/encoder_options.go#L183 can’t set `SpeedBestCompression`, whatever effect that may or may not have.)

But, to set expectations, we are not going to dig deep down into alternative compression algorithm implementations to figure out how they differ and to work on changing them to squeeze extra efficiency; that’s an expertise entirely different from this project.

**Comment by mtrmac** [comment]
> (It might be relevant that https://github.com/klauspost/compress/blob/94867dd0db717f2a857a73816da3522e06536a16/zstd/encoder_options.go#L183 can’t set `SpeedBestCompression`, whatever effect that may or may not have.)

Note https://github.com/klauspost/compress/pull/410 . That will be included by #1327.
