### ISSUE TITLE
Support other OCI artifact types

### ISSUE THREAD

**Issue by gaocegege** [containers/image#1370]
> skopeo can work with OCI images as well as the original Docker v2 images.

It will be great if we could support Helm Chart, CNAB and other [OCI artifact](https://github.com/opencontainers/artifacts) types.

**Comment by nevermore-muyi** [comment]
Support other OCI types are very useful.

**Comment by bt-lemery** [comment]
A Harbor user here who would also find this very useful.

**Comment by mtrmac** [comment]
With #1574 , c/image should now support copying OCI artifacts. Some operations, like inspecting an image or format conversions, are rejected.

Note that the only _specific_ example of a failure in this issue, https://github.com/containers/image/issues/1370#issuecomment-705125081 , was referring to a non-OCI manifest/index type. Those objects are not OCI artifacts, and are not enabled by #1574 .
