### ISSUE TITLE
mechanism_gpgme appears broken on linux/arm64

### ISSUE THREAD

**Issue by moio** [containers/image#1382]
I am using containers/image in my project, and goreleaser outputs the following error:

```
failed to build for linux_arm64: # github.com/containers/image/v5/signature
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:17:16: undefined: gpgme.Context
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:67:44: undefined: gpgme.Context
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:68:14: undefined: gpgme.New
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:72:27: undefined: gpgme.ProtocolOpenPGP
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:76:28: undefined: gpgme.ProtocolOpenPGP
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:98:20: undefined: gpgme.NewDataBytes
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:127:20: undefined: gpgme.NewDataBytes
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:132:18: undefined: gpgme.NewDataWriter
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:136:25: undefined: gpgme.Key
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:136:61: undefined: gpgme.SigModeNormal
vendor/github.com/containers/image/v5/signature/mechanism_gpgme.go:136:61: too many errors
```

Full configuration here: https://github.com/moio/booster/blob/main/.goreleaser.yml

I wonder whether this an inherent limitation of the gpgme bindings, or a bug in those, or a bug in this library - please excuse me if I filed this issue against the wrong repo!

**Comment by moio** [comment]
PS: adding:

```yaml
    tags:
      # containers/image defaults to gpgme which is not available on linux/arm64
      - containers_image_openpgp
```

does fix the build, but image signing capabilities are not available that way, per README.md.

**Comment by mtrmac** [comment]
Thanks for your report.

As the README says, for using the GpgME variant, the GpgME libraries must be available — and because these are C libraries, CGo must be enabled. So at least the `CGO_ENABLED=0` part makes that variant inaccessible.

AFAIK there’s nothing inherently broken about GpgME on linux/arm64; e.g. Fedora is, to my knowledge, using that.

**Comment by moio** [comment]
You are right, `goreleaser` actually bails out at the first failure, but the problem is indeed not ARM-specific, and repeating the build in different conditions shows other platforms fail.

Thank you for the explanation, I am closing this issue!

Have a nice day

**Comment by edikwhitman** [comment]
> PS: adding:
    tags:
      # containers/image defaults to gpgme which is not available on linux/arm64
      - containers_image_openpgp

sorry, adding this code where exactly?

**Comment by mtrmac** [comment]
https://pkg.go.dev/cmd/go#hdr-Build_constraints
