### ISSUE TITLE
Support Docker saved image format

### ISSUE THREAD

**Issue by cyphar** [containers/image#140]
Namely, the `docker load`-friendly format. This would make it possible to use `skopeo` to have a full OCI build system that will then pipe directly into a Docker image without needing a Docker registry or Docker daemon on the build system. In particular this would be very handy for implementing the Open Build Service support that we're planning at SUSE (we can't easily run a Docker registry as part of our infrastructure).

**Comment by rhatdan** [comment]
Yes we are interested in something similar.  I would love to see ansible-container move to a docker daemon free build environment.  The only question I have is whether or not using runc to do the heavy lifting of image building in a more secure container environment is worth it.

**Comment by cyphar** [comment]
@rhatdan 

> The only question I have is whether or not using runc to do the heavy lifting of image building in a more secure container environment is worth it.

That's the plan for KIWI integration. We also might end up using rootless containers inside OBS to make it possible to do without any root privileges -- but we'll see how that goes. Currently I'm still trying to get all of the image components into the right places. I will probably write a blog post about all of the integration once it's more done (and you'll see my PRs in the meantime).

**Comment by mtrmac** [comment]
The conversions from/to that format (or at least the latest version) already exist in #135, so this would be a matter of factoring the conversion code out and adding a transport which simply uses files instead of docker/engine-api/client.

**Comment by cyphar** [comment]
Alright, in which case I can work on this during this week or next.

**Comment by cyphar** [comment]
#148 is a wip implementation. I still need to refactor everything so it's not just a copy of the old code (which I'm working on now). But it does work. :D

**Comment by mtrmac** [comment]
@cyphar Is this handled by #148, or is there more that needs to be done?

**Comment by cyphar** [comment]
Yup, this is done. :tada:
