### ISSUE TITLE
Document how to access rootless containers-storage:

### ISSUE THREAD

**Issue by dcermak** [containers/image#1400]
I am currently trying to read images from the local podman container storage via the following code:
```go
package main

import (
	"fmt"

	"github.com/containers/image/v5/transports/alltransports"
)

func main() {
	imgRef, err := alltransports.ParseImageName("containers-storage:registry.opensuse.org/opensuse/busybox:latest")
	if err != nil {
		panic(err)
	}
	fmt.Println(imgRef)
}
```
which fails with:
```
panic: chown /home/dan/.local/share/containers/storage/overlay/l: operation not permitted
```

Running this through strace reveals that the library tries to `chown` the directory to `root:root`, which fails when run as a normal user
```
fchownat(AT_FDCWD, "/home/dan/.local/share/containers/storage/overlay/l", 0, 0, 0) = -1 EPERM (Operation not permitted)
```

Now, given that skopeo can inspect that reference (`skopeo inspect containers-storage:registry.opensuse.org/opensuse/busybox`) leads me to the assumption that I am doing something wrong. Unfortunately, I don't really see what.

**Comment by mtrmac** [comment]
Thanks for your report. For rootless, the whole process must switch to a rootless namespace; compare https://github.com/containers/skopeo/blob/main/cmd/skopeo/unshare_linux.go , I’m not sure whether it’s _exactly_ what is necessary.

I’m afraid there’s quite a lot of things that Podman does, process-wide, for rootless setup, and c/image doesn’t _exactly_ mirror all of that (that would turn c/image into half of Podman, and it’s also not something c/image can do in the middle of a process lifetime).

**Comment by dcermak** [comment]
Thanks for the pointer @mtrmac! Using `maybeReexec()` function from https://github.com/containers/skopeo/blob/c2732cb15d3f9e9aab3c4a7db8cb5153e3511a78/cmd/skopeo/unshare_linux.go#L19 in my code solves this issue.

Forgive my naivety here, but shouldn't the containers library only perform reads when parsing an image description? After all, the containers are just stored on the filesystem and if they can be read, then it should work?

**Comment by mtrmac** [comment]
c/image doesn’t, at that time, know whether the storage (a singleton for the life of the process) will be used only for reads or for writes as well — and even if it did, I don’t think there’s a c/storage API that would allow telling the difference.

Also, c/storage maintains various cross-process locks, I’m not sure an _entirely_ read-only storage access is feasible with possible concurrent writers.

And even if it were technically possible to read c/storage _metadata_ without any privileges, I don’t think it would end up being very useful: if the extracted image layers contains files owned by “rootless user 0” or “rootless user 1”, c/image can only read the image layers in an environment that allows the current user to read all of these files, i.e. only from the inside of a user namespace. So it might be possible to list images, but not even read them.

(Warning: I don’t know that much about c/storage , and especially about rootless operation. That would probably be best discussed with the experts in the c/storage repo.)

**Comment by dcermak** [comment]
> c/image doesn’t, at that time, know whether the storage (a singleton for the life of the process) will be used only for reads or for writes as well — and even if it did, I don’t think there’s a c/storage API that would allow telling the difference.
> 
> Also, c/storage maintains various cross-process locks, I’m not sure an _entirely_ read-only storage access is feasible with possible concurrent writers.
> 
> And even if it were technically possible to read c/storage _metadata_ without any privileges, I don’t think it would end up being very useful: if the extracted image layers contains files owned by “rootless user 0” or “rootless user 1”, c/image can only read the image layers in an environment that allows the current user to read all of these files, i.e. only from the inside of a user namespace. So it might be possible to list images, but not even read them.
> 
> (Warning: I don’t know that much about c/storage , and especially about rootless operation. That would probably be best discussed with the experts in the c/storage repo.)

That makes sense.

Would it be worth documenting how to access podman's rootless container storage?

**Comment by mtrmac** [comment]
That’s a good point (though I’m not 100% sure _where_ to document it so that users will find it).

Let’s convert this issue to track that — and a PR would be welcome.

(Cc: @giuseppe @nalind to make sure the guidance, if any, is correct.)

**Comment by dcermak** [comment]
I'd be willing to contribute any documentation, if you tell me where :-)

**Comment by mtrmac** [comment]
My best guess is somewhere around `c/image/storage.Transport`, OTOH callers of `alltransports.ParseImageName` are not likely to find that.
