### ISSUE TITLE
copying a new image from a registry to local storage deadlocks somewhere

### ISSUE THREAD

**Issue by dcermak** [containers/image#1401]
I am currently trying to pull an image from a remote registry to the local `containers-storage`, via the following function:
```go
func PullImageToLocalStorage(image string) error {
	policy, err := signature.DefaultPolicy(nil)
	if err != nil {
		return err
	}
	policyCtx, err := signature.NewPolicyContext(policy)
	if err != nil {
		return err
	}
	defer policyCtx.Destroy()

	localRef, err := alltransports.ParseImageName(fmt.Sprintf("containers-storage:%s", image))
	if err != nil {
		return err
	}

	ref, err := reference.ParseNormalizedNamed(image)
	if err != nil {
		return err
	}

	image = "//" + image
	if _, isNamedTagged := ref.(reference.NamedTagged); !isNamedTagged {
		image += ":latest"
	}
	remoteRef, err := docker.ParseReference(image)
	if err != nil {
		return err
	}

	if _, err := copy.Image(backgroundContext, policyCtx, localRef, remoteRef, &copy.Options{
		ReportWriter: os.Stdout,
	}); err != nil {
		return err
	}
	return nil
}
```

However, the above function does not work when the image does not yet exist in the local storage. It will output the following to stdout:
```Shellsession
❯ go build &&  go run test.go docker.io/library/alpine
Getting image source signatures
Copying blob a0d0a0d46f8b done

```
and then hang for ever. There appears to be some kind of lock that is not being released, because `podman images` is also hanging. Note, that the function works flawlessly if the image is present in the local container storage.

Any idea what I am doing wrong here?

**Comment by mtrmac** [comment]
Nothing immediately springs to mind, and if `podman images` is hanging, it’s probably something broken about the existing state, unrelated to c/image.

Bumping the Logrus log level to “debug” might help, but if it is really a locking hang, triggering a complete Go backtrace would probably lead directly to the lock.

**Comment by dcermak** [comment]
Appologies for not updating this earlier, but @nalind on irc pointed me to the right solution: add `reexec.Init()` at the top of my `func main()`. That resolved the problem for me.

**Comment by mtrmac** [comment]
(This is certainly unrelated, and the existing code works fine just a note of what is possible:)


> ```go
> 	localRef, err := alltransports.ParseImageName(fmt.Sprintf("containers-storage:%s", image))
> ```
`storage.Transport.ParseReference(image)` would avoid the string syntax, and drag in fewer dependencies.


> ```go
> 	ref, err := reference.ParseNormalizedNamed(image)
> 	if err != nil {
> 		return err
> 	}
> 
> 	image = "//" + image
> 	if _, isNamedTagged := ref.(reference.NamedTagged); !isNamedTagged {
> 		image += ":latest"
> 	}
> 	remoteRef, err := docker.ParseReference(image)
> 	if err != nil {
> 		return err
> 	}
> ```

`remoteRef, err := docker.NewReference(reference.TagNameOnly(ref))` is a more direct way to express that.

**Comment by dcermak** [comment]
Thanks @mtrmac, that simplifies my code a bit.

Now for the elephant in the room: where should this be documented? Maybe we should create a "rootless mode" guide?

**Comment by mtrmac** [comment]
@nalind wouldn’t it be possible for c/storage to detect the lack of `reexec.Init` and fail with a clear error? E.g. any user of `reexec.Command*` could check a variable indicating that `reexec.Init` was called, and fail immediately if it wasn’t? Or is it more complex than this?

(Should that just be an API change, or are they supposed to stay stable and need to be deprecated in favor of `Command*WithError`?)

**Comment by nalind** [comment]
Oh, I rather like that idea.  `Command()` doesn't have space to return an error, but panicking is an option.
