### ISSUE TITLE
Separate mirror list for digest only and tag allowed image pull

### ISSUE THREAD

**Issue by QiWang19** [containers/image#1407]
`mirror-by-digest-only` in registry.conf is configured for the original registry.
It is expected to configure this feature for mirrors, keep two lists of mirrors for the original registry: one list of mirrors is digest only, the other list of mirrors is tag allowed.
This feature is requested by ImageContentSourcePolicy CRD [enhancement](https://github.com/openshift/enhancements/pull/929/files#diff-eebeb781f4d3603039f4db588d8bd2ad7f35467593652f558463bf1c10312a3aR260) supporting the allow mirror by tags. This underlying change in registry.conf can simplify the syntax checking and validation of API implementation.

Enhancement PR: https://github.com/openshift/enhancements/pull/929

**Comment by vrothberg** [comment]
Here's the specific location in the enhancement: https://github.com/openshift/enhancements/pull/929/files#diff-eebeb781f4d3603039f4db588d8bd2ad7f35467593652f558463bf1c10312a3aR260

**Comment by vrothberg** [comment]
Before opening a PR, let's have a conversation on how to achieve that.  As @QiWang19 mentions above, `mirror-by-digest-only` is an attribute of the main registry. We must not change that for backwards compat.

I think that we may need two attributes for mirrors: `mirror-by-digest-only`  and `mirror-by-tag-only`.  They cannot both be set to `true`.  If non is set, the mirror will be used for tags and for digests.

**Comment by mtrmac** [comment]
No, the goal is not to have two _booleans_, but two _lists_. I.e. turn `mirrors` into `digest-mirrors` and `tag-mirrors`, or maybe more likely(?) `digest-mirrors` and `mirrors` (I need to re-read the enhancement and earlier discussions carefully.) 

I.e. allow defining digest-only mirrors, and tag+digest mirrors, both for the same scope (where the digest-only mirrors can be on quite untrusted infrastructure, but the tag mirrors need to be more trusted for unsigned images, and possibly carefully synchronized if mutable tags like `:latest` are used in deployment configurations). The `mirror-by-digest-only` boolean would remain but probably effectively become deprecated, in favor of using the `digest-mirrors` list.

(Naming is hard. `digest-reference-mirrors`? More accurate, but probably too long to type.)

**Comment by vrothberg** [comment]
I'd much prefer two booleans over keeping two separate lists of mirrors.  What if we need more attributes in the future?  Having **N** lists for **N** use cases seems confusing.  Having **1** list where each item can be configured independently seems cleaner to me.

**Comment by vrothberg** [comment]
Just be sure.  I imagine these attributes on the scope of mirrors not on the registry scope:
```TOML
[[registry]]
location="registry.com"

[[mirror]]
location="digest.mirror.com"
mirror-by-digest-only=true
[[mirror]]
location="tag.mirror.com"
mirror-by-tag-only=true
[[mirror]]
location="generic.mirror.com"
```

**Comment by mtrmac** [comment]
Ah, I misread and I didn’t realize you were talking about _per-mirror_ booleans. That would work, of course.

At this point I don’t have a strong preference between two lists and per-mirror booleans; and I suspect we don’t need the `mirror-by-tag-only` option. But I’ll need to re-read the previous discussions, WRT both of these.

**Comment by QiWang19** [comment]
If implement this feature by only adding one boolean `mirror-by-digest-only` for each mirror table and the mirror will be used for tags and for digests if the boolean is not set. Do we need to consider the order between `mirror-by-digest-only` mirrors and non set mirrors when collecting the pullsource? For example, the non set mirrors should append after the digest-only mirrors in the endpoints slice? https://github.com/containers/image/blob/e2f122ef2a19553327541117e39abeab465a00bb/pkg/sysregistriesv2/system_registries_v2.go#L134-L143

**Comment by vrothberg** [comment]
Good question, @QiWang19.  I think that they should kept separate and hence not get appended.  In both cases (i.e. pull by tag or by digest) the relative order should be preserved.
