### ISSUE TITLE
OCI image source

### ISSUE THREAD

**Issue by runcom** [containers/image#141]
Following a chat between @rhatdan and @alexlarsson in #atomic on Freenode:

```
10:27         alexlarsson : skopeo copy oci:oci-dir oci:other-dir
10:27         alexlarsson : FATA[0000] Error initializing source oci:oci-dir:latest: Reading images not implemented for oci: image names
10:27         alexlarsson : Not much support for oci, is there?
10:28             dwalsh_ : runcom|afk, ^^
10:28         alexlarsson : I changed the flatpak oci code to export a directory following the oci image spec layout
10:28         alexlarsson : do we have anything that can read that?
10:29         alexlarsson : To like, test it or something :)
10:29             dwalsh_ : alexlarsson, I thought skopeo had grown support for it.
10:29             dwalsh_ : We need to wait for runcom|afk to come back.
```

What you need is the ability to have an OCI source, probably remote? well, since OCI hasn't "distribution" in scope that's simply not possible right now (there's work on https://github.com/docker/distribution/pull/2021)

**Comment by alexlarsson** [comment]
I was just experimenting with skopeo, but the command above is copying from one OCI directory (which skopeo created) to another directory. Why should this not work?

**Comment by runcom** [comment]
Because we didn't implement that yet. Can't you just cp the directory? Do you have any hard requirement to do that here?

**Comment by alexlarsson** [comment]
I was going to use skopeo to test OCI support for flatpak use, and this was just the minimal test i could come up with. What I really wanted was to take an OCI directory i've created and round-trip it to a docker registry and back to see how well that worked.

**Comment by mtrmac** [comment]
Yeah, it makes sense that containers/image should support this. I don’t personally know about priorities/timing though.

**Comment by runcom** [comment]
@mtrmac do you mean you're ok having an OCI image source based on directories? (and maybe later support remote images for OCI as well). 
Implementing this for directories should be trivial afaict and I have some spare cycles if this is needed.

**Comment by mtrmac** [comment]
Well, to be precise: I haven’t paid enough attention to OCI to say how much (or whether) the OCI directory transport is useful. But it seems to me that _if_ it is useful, both reading and writing is probably useful.

(I’d also like OCI to switch to the manifest support in c/i/image instead of hiding the conversions if possible; the write path was an useful stopgap but it would be nice not propagate that further.)

**Comment by runcom** [comment]
@mtrmac what do you mean by switch to the manifest support in c/i/image? Link to code?

**Comment by mtrmac** [comment]
* Copy `image/manifest_schema2.go` to `image/manifest_oci.go`, edit suitably.
 * Implement `types.Image.UpdatedImage(&types.ManifestUpdateOptions{ManifestMIMEType:}` to convert at least between s2 and OCI, both ways, based on the existing `oci_dest.go:createManifest` code; then combine with existing s1<->s2 conversions to support any conversion between all three of s1, s2, OCI.
 * Drop the now redundant ad-hoc conversion in `oci_dest.go:createManifest`

**Comment by hustcat** [comment]
@runcom @mtrmac I want to copy image from OCI layout directories to docker daemon after [docker #26369](https://github.com/docker/docker/pull/26369).
So OCI image source based on directories is very useful. I'd like to implement:)
