### ISSUE TITLE
Use `context` instead of `golang.org/x/net/context`

### ISSUE THREAD

**Issue by mtrmac** [containers/image#142]
Now that we have (AFAICT) abandoned Go 1.6 and require Go 1.7, we probably can use the stdlib-included one.

**Comment by runcom** [comment]
We will, though, F24 still has go 1.6.3

**Comment by runcom** [comment]
And we're still using engine-api, so, as soon as Docker 1.13 goes GA we'll abandon engine-api and golang 1.6.z will work again (the reason behind 1.6 not compiling was that engine-api is broken wrt to multiple golang and did break 1.6)

**Comment by mtrmac** [comment]
Thanks, never mind then.
