### ISSUE TITLE
Support for simple registries in the filesystem (`file://` protocol)

### ISSUE THREAD

**Issue by lukasbestle** [containers/image#1435]
## Use case

I have a multi-user server where the users will have access to a local container registry with images built by the server admin. These images can then be `podman pull`ed and used to spin up containers.

This use case comes with a few requirements:
- The registry should only be writable by the admin.
- Most images should be accessible by all users, but it should also be possible to limit read access to one group for specific images.
- The setup should be as simple as possible to reduce complexity and the attack surface.

## Idea

The three requirements can easily be met by a filesystem registry.

I.e. there would be a directory on the server that's readable by all users but only writable by the admin. Images are stored in subdirectories and each subdirectory can again have different directory permissions so that it is e.g. only readable by a specific group or user. The filesystem already comes with all these features for free with reduced complexity compared to a HTTP(S) registry.

I feel like this feature can be useful beyond the use case I described above. It integrates well into custom setups.

## Proposal

`containers-registries.conf` should allow the `file://` protocol for the `location` attribute:

```toml
[[registry]]
prefix = "builder.localhost"
location = "file:///path/to/the/registry/directory"
```

## Question

I don't have a good understanding of the inner workings of this library yet, so maybe a filesystem registry is already possible. If so, I'd be really happy about hints.

**Comment by lukasbestle** [comment]
@mtrmac Thank you VERY much for the pointers, your reply is super helpful to me. 👍
I'll try it out and report back.

**Comment by vrothberg** [comment]
Friendly ping.
@lukasbestle are we good to close the issue?

**Comment by lukasbestle** [comment]
Thanks for the ping and sorry for the delay. I didn't get around to testing this because I was busy with other projects. I'm closing the issue as I am pretty sure the proposed solutions (especially `additionalimagestores`) are just right and no additional features are needed. :)
