### ISSUE TITLE
Add tests for image/docker_schema1.go

### ISSUE THREAD

**Issue by mtrmac** [containers/image#144]
At least covering the success case for manifest conversion, like docker_schema2_test.go

**Comment by rhatdan** [comment]
@mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
There are tests now, so I think we can close the issue.

**Comment by mtrmac** [comment]
Fixed in https://github.com/containers/image/pull/416 for the record.
