### ISSUE TITLE
Enhance readme

### ISSUE THREAD

**Issue by HuKeping** [containers/image#146]
Hi, does is make sense to add more detail about this project to the README. I want to know more about this project but hardly find a docs to begin with.

First question in my mind, what's the different with the OCI/image-tool? 

Sorry I don't want to bother you guys @philips  @runcom  but I find you are the only members of github.com/container.

**Comment by rhatdan** [comment]
@runcom can we still some of the text from skopeo to enhance the README?  The readme is rather lacking.

**Comment by runcom** [comment]
We could, I'll try to find some spare cycles to do this but if anyone want to contribute please do so

**Comment by rhatdan** [comment]
@cyphar did some decent write up in https://github.com/kubernetes-incubator/cri-o/issues/175  We could probably grab some of his content.

**Comment by HuKeping** [comment]
Thanks @rhatdan @runcom , I've got what I want in kubernetes-incubator/cri-o#175 . 

If we should still keep this issue open to track the updating of README?

**Comment by Crazykev** [comment]
+1 for a detailed README
