### ISSUE TITLE
Requirements for making OCI layout a parallel-safe destination

### ISSUE THREAD

**Issue by Madeeks** [containers/image#1466]
Hello,
I'd be interested in knowing what would be necessary to qualify the OCI layout transport as a parallel-safe image destination.

I have naively modified `ociImageDestination.HasThreadSafePutBlob()` to return `true`, built Skopeo on top of the modified c/image, and  I was able to copy a number of moderately large (in overall size and number of layers) images from remote registries.
Is there a specific use case or workflow posing constraints on concurrency?
Thanks!

**Comment by mtrmac** [comment]
Thanks for your report.

Looking at the code, AFAICS it does seem safe from a quick look; originally we marked everything as not-safe until a careful review happens.

One thing to _possibly_ think about is detecting/handling concurrent attempts to create the same blob (and not actually _doing_ the second one, just blocking on the first one finishing), but it’s not at all clear that it’s worth the complexity and I don’t think it’s necessary — the existing “thread-safe” don’t do this either.

**Comment by Madeeks** [comment]
Thanks for your assessment @mtrmac. Do you think that `PutBlob()` could be promoted to "thread-safe" in the near future, then?
I'd be interested in helping, if necessary.

**Comment by Madeeks** [comment]
Sorry for the delay in replying, I've been a bit busy.
Yeah, I can set up a PR, but I'm a bit uncertain about unit tests and documentation.
I had a look around for other `PutBlob()` parallel tests and for docs mentioning thread-safety and I found none, even for transports already classified as "thread-safe" (I am aware of #789).

Do you have any suggestion or is the boolean change enough?

**Comment by mtrmac** [comment]
No other transports do probabilistic concurrency testing where we would try to run a few hundred writes in parallel and see what happens; I don’t think it’s _that_ useful here, essentially just stress-testing the OS `Rename` atomicity (and we wouldn’t really want to spend minutes running a unit test).

I think just the one-line boolean change is sufficient, given your practical testing and the PR providing an opportunity for a few more reviewers to carefully check the current implementation.
