### ISSUE TITLE
can't pull image from http registry using podman

### ISSUE THREAD

**Issue by k19810703** [containers/image#1583]
I edited config file as below, added private insecure registry.

```
$ cat /etc/containers/registries.conf
[[registry]]
prefix = "9.197.12.29:5000"
location = "9.197.12.29:5000"
insecure = true
```

When I use podman to pull image , got below error
```
podman pull 9.197.12.29:5000/myimage
Trying to pull 9.197.12.29:5000/myimage:latest...
Error: initializing source docker://9.197.12.29:5000/myimage:latest: pinging container registry 9.197.12.29:5000: Get "https://9.197.12.29:5000/v2/": http: server gave HTTP response to HTTPS client
```

Any advice to fix that.

**Comment by rhatdan** [comment]
Looks like there is no container registry listening at this port?

**Comment by k19810703** [comment]
@mtrmac 

➜ git:(dev-whd) podman --log-level=debug pull 9.197.12.29:5000/myimage
INFO[0000] podman filtering at log level debug
DEBU[0000] Called pull.PersistentPreRunE(podman --log-level=debug pull 9.197.12.29:5000/myimage)
DEBU[0000] SSH Ident Key "/Users/wuhuidong/.ssh/podman-machine-default" SHA256:*** ssh-ed25519
DEBU[0000] Found SSH_AUTH_SOCK "/private/tmp/com.apple.launchd.zgbLETbLWY/Listeners", ssh-agent signer(s) enabled
DEBU[0000] SSH Agent Key SHA256:*** ssh-ed25519
DEBU[0000] SSH Agent Key SHA256:*** ssh-ed25519
DEBU[0000] Dedup SSH Key SHA256:*** ssh-ed25519
DEBU[0001] DoRequest Method: GET URI: http://d/v4.1.1/libpod/_ping
DEBU[0002] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0002] Found credentials for jp.icr.io in credential helper containers-auth.json in file /Users/wuhuidong/.config/containers/auth.json
DEBU[0002] No credentials matching docker.io found in /Users/wuhuidong/.config/containers/auth.json
DEBU[0002] No credentials matching docker.io found in /Users/wuhuidong/.config/containers/auth.json
DEBU[0002] No credentials matching docker.io found in /Users/wuhuidong/.dockercfg
DEBU[0002] No credentials for docker.io found
DEBU[0002] No credentials matching us.icr.io found in /Users/wuhuidong/.config/containers/auth.json
DEBU[0002] No credentials matching us.icr.io found in /Users/wuhuidong/.config/containers/auth.json
DEBU[0002] No credentials matching us.icr.io found in /Users/wuhuidong/.dockercfg
DEBU[0002] No credentials for us.icr.io found
DEBU[0002] DoRequest Method: POST URI: http://d/v4.1.1/libpod/images/pull
Trying to pull 9.197.12.29:5000/myimage:latest...
Error: initializing source docker://9.197.12.29:5000/myimage:latest: pinging container registry 9.197.12.29:5000: Get "https://9.197.12.29:5000/v2/": http: server gave HTTP response to HTTPS client
➜  ymfg-design-doc git:(dev-whd) cat /etc/containers/registries.conf
[[registry]]
prefix = "docker.io"
location = "ksj6sxsh.mirror.aliyuncs.com"

[[registry]]
prefix = "9.197.12.29:5000"
location = "9.197.12.29:5000"
insecure = true

**Comment by mtrmac** [comment]
Oh, this is _remote_ Podman? In that case the relevant `/etc/containers/registries.conf` should be one on the server, not the one on the client. I’m not sure how/if ever that is automatically populated from the client, that’s a Podman question.

**Comment by mtrmac** [comment]
@k19810703 did you manage to get this working?

**Comment by mtrmac** [comment]
Assuming this is no longer an issue; please reopen if that’s not the case.
