### ISSUE TITLE
Skopeo leaks details about the host in oci-archives

### ISSUE THREAD

**Issue by graywolf-at-work** [containers/image#1627]
When running 

	skopeo copy docker://docker.io/library/ubuntu@sha256:b2339eee806d44d6a8adc0a790f824fb71f03366dd754d400316ae5a7e3ece3e oci-archive:/tmp/x.tar

the resulting /tmp/x.tar contains references to the current user. In particular
it seems that uname and gname are set to the current user and group. uid and
gid are set as well (I think they should simply be 0 since they are not
relevant on this level in the oci-archive). I don't think there is a good
reason to leak this information about the host running the skopeo-copy.

I think the same happening even with the layers inside the oci-archive when
doing podman save, but I assume root cause will be the same so I'm not filling
that separately (I can if it is desired).

**Comment by mtrmac** [comment]
Non-Ruby demonstration:
```sh
$ tar tvvf foo.tar       
drwxr-xr-x  0 $user   $group       0 Aug 10 17:32 blobs/
…
```

**Comment by mtrmac** [comment]
From a quick look, it currently seems possible to override the UID/GID via `c/storage/pkg/archive.TarOptions.ChownOpts`, but that only sets the numerical ID values, not the `Uname`/`Gname` values.

**Comment by mtrmac** [comment]
> It actually applies to both, at least as far as I can tell. I just think the root cause will be the same so I've made just one bug report.

It probably involves the same _code_ but it’s very unlikely to be the same _fix_ (because container images actually have various UID/GID value that must be preserved). So, please file the build part against Buildah.

**Comment by mtrmac** [comment]
(Also, that note to self was because I was very confused how a copy could modify layer contents, because c/image just doesn’t touch the underlying tar data when `docker://` and `oci-archive:` are used.)

**Comment by rhatdan** [comment]
Bin inside of the container is UID 1?  Perhaps I don't understand the leak.

**Comment by mtrmac** [comment]
@rhatdan Let’s discuss the build case in the Buildah issue.
