### ISSUE TITLE
Can't acces prefixed localhost registry

### ISSUE THREAD

**Issue by Tokariew** [containers/image#1629]
```
[[registry]]
prefix="reg.tok"
location="localhost:5000"
insecure=true
```
I have above code in the `/home/tokariew/.config/containers/registries.conf.d/10-registry.conf`
If i don't add prefix, my local registry work fine and i can access it and can pull and push from it. But when i setup prefix i get the following error:
```
Error: trying to reuse blob sha256:xxxx at destination: pinging container registry reg.tok: Get "http://reg.tok/v2/": dial tcp: lookup reg.tok: no such host
```
If i change the file to have following
```
[[registry]]
prefix="reg.tok"
location="docker.io"
```

I can use reg.tok as shorter form of docker.io. I can have insecure in file and not, and it didn't change a thing when I try access my registry via podman when prefix is set.

**Comment by mtrmac** [comment]
Thanks for your report. 
> trying to reuse blob sha256:xxxx at destination

Note https://github.com/containers/image/blob/6d34786aec96dfbf5650661b1cf3739f51b0c63d/docs/containers-registries.conf.5.md?plain=1#L130-L131 : pushes currently don’t use remapping.

Is the difference _really_ between `localhost` and `docker.io`? If so, please provide a complete reproducer (full configuration and exact command), and a debug log (`skopeo --debug`/`podman --log-level=debug`, or in custom code, using `logrus.SetLevel(logrus.DebugLevel)`).

**Comment by Tokariew** [comment]
Missed the note
Sorry for problem, but if only work for pulling, so it is working as intended
SO closing it…
