### ISSUE TITLE
Build fails if CGO_ENABLED=0

### ISSUE THREAD

**Issue by paralin** [containers/image#1634]
Cgo is not available on many platforms. libgpgme is used for signing.

#1632 (closed) proposed to enable openpgp when cgo is unavailable.

The package should compile when `CGO_ENABLED=0` - with some kind of alternative implementation to libgpgme that is go-only.

**Comment by paralin** [comment]
@mtrmac thanks for the background information 

But this issue is still not solved; building on platforms without cgo fails.

There seems to be two solutions: add stubs that return errors when no implementation is compiled in, and use those for !cgo, or auto enable openpgp if !cgo.

Since the latter was already rejected, are we all good with the former? I'll send a pr...

**Comment by rhatdan** [comment]
I think the former should be ok. Just functionality will be limited.

**Comment by paralin** [comment]
> MHO the user should just make a choice and add a tag. That’s not impossible, is it?

The build fails with an error that doesn't make it clear why the build is failing. At minimum I would expect the build to fail with something like "ImageSigningRequiresCgo is not defined" and not "fooBar() undefined"

Also, this code is being used in non-cgo environments. Maybe not the original intent of the code, but it's the way it is. It should work without cgo, regardless of the security implications. A tag opt-in to avoid a compile error is fine, but the compile error should make it clear why the build is failing.

**Comment by mtrmac** [comment]
> It should work without cgo, regardless of the security implications.

I don’t think we agree on basic values enough to continue this discussion.

**Comment by paralin** [comment]
Typical. Disappointing. But I'll maintain a fork.

Not sure how it's "basic values" to believe that the code should work without cgo. Seems more like your personal opinion.

**Comment by paralin** [comment]
@mtrmac from your readme...

> containers_image_ostree: Import ostree: transport in github.com/containers/image/transports/alltransports. This builds the library requiring the libostree development libraries. Otherwise a stub which reports that the transport is not supported gets used. The github.com/containers/image/ostree package is completely disabled and impossible to import when this build tag is not in use

How is this different? The other tag you've got also is stubbed.

**Comment by mtrmac** [comment]
Everyone is busy all the time, and no-one knows everything about everything. so we as engineers are responsible for making code secure by default. The convenient and lazy thing to do must be the sufficiently secure one.

Users have always the freedom to take the extra effort to make the less secure choice — ultimately, by forking, or using another product, sure — but to make the low-effort path the dangerous one is abdicating responsibility and trust placed in us.

**Comment by paralin** [comment]
@mtrmac Understood, I'll send a PR which at least changes the build error from:

```
# github.com/containers/image/v5/signature
signature/mechanism_gpgme.go:18:22: undefined: gpgme.Context
signature/mechanism_gpgme.go:72:50: undefined: gpgme.Context
signature/mechanism_gpgme.go:73:20: undefined: gpgme.New
signature/mechanism_gpgme.go:77:33: undefined: gpgme.ProtocolOpenPGP
signature/mechanism_gpgme.go:81:34: undefined: gpgme.ProtocolOpenPGP
signature/mechanism_gpgme.go:103:26: undefined: gpgme.NewDataBytes
signature/mechanism_gpgme.go:132:26: undefined: gpgme.NewDataBytes
signature/mechanism_gpgme.go:137:24: undefined: gpgme.NewDataWriter
signature/mechanism_gpgme.go:156:41: undefined: gpgme.PinEntryLoopback
signature/mechanism_gpgme.go:161:31: undefined: gpgme.Key
signature/mechanism_gpgme.go:161:31: too many errors
```

To...

```
# github.com/containers/image/v5/signature
signature/mechanism_nocgo.go: ContainersImageSignatureRequiresCgo is not defined.
```

... at least that way it's clear that it's intentional and meant to be left that way.

**Comment by rhatdan** [comment]
Add the buildtag to your error message to tell the user, if they want to disable signing, you can use this flag.

**Comment by paralin** [comment]
@rhatdan do you mean add a new build tag which has a stub that returns errors instead of failing the build?

**Comment by rhatdan** [comment]
Yes if there is a buildtag that states, without_pgp or something like that then the error for no cgo should suggest it.

**Comment by paralin** [comment]
@rhatdan there is not currently a tag which builds a stub returning an error - I could add one, maybe `containers_image_disable_signing` ?

**Comment by rhatdan** [comment]
I believe that would satisfy @mtrmac desire to make users explicitly disable the security feature.

**Comment by paralin** [comment]
@rhatdan The PR I sent: If CGO_ENABLED=0 the build fails with a warning saying Cgo is required.

They would have to explicitly enable openpgp (considered insecure) to make the build pass.

So I think that already satisfies what @mtrmac is saying which is that the "insecure" openpgp implementation should not be compiled unless a build flag is specified. The "default go build" output should always be considered secure.

**Comment by paralin** [comment]
If you wanted to add a build tag - say `containers_image_disable_signing`:

```go
//go:build containers_image_disable_signing
// +build containers_image_disable_signing

package signature

// ErrSigningDisabled is returned if container image signing is disabled.
var ErrSigningDisabled = errors.New("container image signing is disabled in this build")

// newGPGSigningMechanismInDirectory returns an error indicating signing is disabled.
func newGPGSigningMechanismInDirectory(optionalDir string) (SigningMechanism, error) {
	return nil, ErrSigningDisabled
}

// newEphemeralGPGSigningMechanism returns a new GPG/OpenPGP signing mechanism which
// recognizes _only_ public keys from the supplied blob, and returns the identities
// of these keys.
// The caller must call .Close() on the returned SigningMechanism.
func newEphemeralGPGSigningMechanism(blobs [][]byte) (SigningMechanism, []string, error) {
	return nil, nil, ErrSigningDisabled
}

```

**Comment by paralin** [comment]
@rhatdan Added to #1638 - the first commit clarifies the build failure error message & adds a comment explaining why. The second commit adds a new tag which compiles cleanly with a stub returning a runtime error instead of a build failure.

Hopefully that clears up all use cases:

 - default: use cgo and enable libgpgme
 - CGO_ENABLED=0 -> build fails
 - CGO_ENABLED=0 and containers_image_openpgp -> build succeeds
 - CGO_ENABLED=0 and containers_image_disable_signing -> build succeeds but returns errors at runtime

**Comment by developer-guy** [comment]
> _https://github.com/wolfi-dev/os/pull/122_
