### ISSUE TITLE
[Feature] Support docker config authentication including username and password

### ISSUE THREAD

**Issue by kycheng** [containers/image#1660]
There is a docker authentication config like this, and it's in the correct folder (~/.docker/config.json). skopeo cannot use this file to complete the authentication.
```json
{
  "auths": {
    "docker.io": {
      "username": "admin",
      "password": "123456"
    },
    "query.io": {
      "username": "admin",
      "password": "123456"
    }
  }
}
```
Because skopeo ignores username and password when reading the configuration，but auth can actually be generated by username and password, which is easy to do.
```go
type dockerAuthConfig struct {
	Auth          string `json:"auth,omitempty"` 
	IdentityToken string `json:"identitytoken,omitempty"`
}

type dockerConfigFile struct {
	AuthConfigs map[string]dockerAuthConfig `json:"auths"`
	CredHelpers map[string]string           `json:"credHelpers,omitempty"`
}
```
I hope skopeo can do the job like this, it might be better.

**Comment by mtrmac** [comment]
Thanks for your report. This is already tracked in #1259 .
