### ISSUE TITLE
Is the new LayersData field the compressed size?

### ISSUE THREAD

**Issue by jchunkins** [containers/image#1663]
I saw a recent change in this PR: https://github.com/containers/image/pull/1626 and was wondering what the `LayersData.Size` field corresponds to. Is this the compressed size of the layer?

For example, docker reports this for the latest redis image:

```console
$ docker image ls redis
REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
redis        latest    9da089657551   29 hours ago   117MB
```

Another way to look at the image with docker:

```console
$ docker history redis --human=false --format "{{.Size}}" | jq -s 'add' | numfmt --to=si
117M
```

**NOTE:** I think both of the above examples must be returning the size of the redis image AND its base image? Maybe?

This way seems to match value reported by skopeo:

```console
$ docker manifest inspect -v redis | jq '.[] | select( .Descriptor.platform.architecture | contains("amd64")) | [.. | objects | .size] | add ' | numfmt --to=si
43M
```

The skopeo code that consumes this latest change reports this:

```console
$ ./bin/skopeo --override-os linux inspect --no-tags docker://redis | jq '[.. | objects | .Size] | add' | numfmt --to=si 
43M
```

**NOTE**  I assume these last two examples above only report the layers for the image itself?

At any rate, I have to assume `LayersData.Size` is the compressed image size, or maybe I am missing something. Perhaps @ningmingxiao can provide more insight into what the value represents.

Would it be possible to report compressed and uncompressed sizes, if for no other reason than completeness / convenience?

**Comment by ningmingxiao** [comment]
LayersData.Size is the compressed image size

**Comment by jchunkins** [comment]
@ningmingxiao Thanks for the confirmation. 

Given the first set of commands in my original post (i.e. `docker image ls` and `docker history`), those sizes appear to be the uncompressed sizes. I tested this by extracting the redis image onto the file system, and the size matches the 117MB in those examples.

So the question I have, is there a way to provide the uncompressed size? Docker seems to have a way to do this, so just wondering if there's something easily done to provide that value in the results too.

**Comment by jchunkins** [comment]
@mtrmac So there's no way to make any guarantees about the `LayersData.Size` other than the amount of data stored in the source (and it could be compressed or uncompressed). This is different from the assertion @ningmingxiao made saying it's always compressed size.

**Comment by jchunkins** [comment]
Tangential question... if a tool "mirrors" an image to a new destination and changes the compression type (i.e. compressed -> uncompressed OR uncompressed ->compressed), then I assume that changes the image digest too?

**Comment by mtrmac** [comment]
Yes it does.
