### ISSUE TITLE
docker.tarfile: support multiple images in the same archive

### ISSUE THREAD

**Issue by cyphar** [containers/image#177]
From a source perspective, this would be implemented as selecting what `RepoTag` to extract layers from. And from a destination perspective, it would be implemented by changing what the resultant `RepoTag`s already present at a destination are.

Essentially all of this would be controlled by choosing a full reference when creating references that use `docker.tarfile`.

**Comment by rhatdan** [comment]
@cyphar @mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
The issue remains but I think we can close it given the age of the issue.

**Comment by mtrmac** [comment]
Age or not, this was actually requested recently — but in a duplicate which has more details on a possible implementation approach, so, sure, we can close this one.

To link the two, https://github.com/containers/image/issues/610 .
