### ISSUE TITLE
Disable Dependabot filing version updates

### ISSUE THREAD

**Issue by mtrmac** [containers/image#1836]
They are still filed for this repo; it seems to be enabled by mere presence of `.github/dependabot.yml` (but it also seems possible to keep that file around but to disable version updates by setting the PR limit to 0).

We should decide what we want to do (remove that configuration entirely? Keep it around for some of the scanning / vulnerability data?). And then do the same thing in Skopeo.

From my POV this is a low-priority cleanup.

Cc: @cevich

**Comment by mtrmac** [comment]
> but it also seems possible…

Ref: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file

**Comment by cevich** [comment]
> They are still filed for this repo

Hrmmm, :vomiting_face: that means it's still enabled for c/skopeo as well :disappointed: 

Thanks for the doc reference.  I'll push PRs to disable it via that file as well.
