### ISSUE TITLE
Image upload fails if PATCH lasts longer than expiry time of an OAuth token

### ISSUE THREAD

**Issue by bainsy88** [containers/image#1907]
In the case a PATCH request last longer the the expiry time of the OAuth token then the image push will always fail. 

# What happens 

This would be exposed if the PATCH [here](https://github.com/containers/image/blob/main/docker/docker_image_dest.go#L183)  takes longer than expiry time of the OAuth token meaning the PUT [here](https://github.com/containers/image/blob/main/docker/docker_image_dest.go#L213) will fail with a 401 and the code will not handle this. 

# What I expect to happen. 

When the PUT gets a 401 I would expect the challenge header to be read and the request retried after getting a new OAuth token

**Comment by mtrmac** [comment]
@bainsy88 did you manage to diagnose the failure further?

**Comment by mtrmac** [comment]
Closing due to lack of response; please reopen if the situation can be clarified.
