### ISSUE TITLE
Restore in-memory check for duplicate layers

### ISSUE THREAD

**Issue by mtrmac** [containers/image#196]
… per https://github.com/containers/image/pull/63#discussion_r91383407 . That PR did add an `imageCopier.copiedBlobs` but it has no uses.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
AFAIU the issue, we can close it.

**Comment by mtrmac** [comment]
(With #611, alternatively:
- an in-memory duplicate check exists in the current version.
- just silently skipping blob copies in generic code is no longer permissible; the code should involve `TryReusingBlob` even for duplicates.

See https://github.com/containers/image/pull/611#discussion_r278085641 )
