### ISSUE TITLE
Can the server be upgraded to TLS1.2?

### ISSUE THREAD

**Issue by shitou12345678** [containers/image#1962]
Since the TLS1.0 and TLS1.1 versions are old. Can the server be upgraded to TLS1.2? 
```
// this is cloned from docker/go-connections because upstream docker has changed
// it and make deps here fails otherwise.
// We'll drop this once we upgrade to docker 1.13.x deps.
func serverDefault() *tls.Config {
	return &tls.Config{
		// Avoid fallback to SSL protocols < TLS1.0
		MinVersion:               tls.VersionTLS10,
		PreferServerCipherSuites: true,
		CipherSuites:             tlsconfig.DefaultServerAcceptedCiphers,
	}
}
```
Upstream docker/go-connections has been upgraded.
https://github.com/docker/go-connections/commit/eed1c499cef34e358f4a10f8de1ce1b1a945556f#diff-2cce4edd4dc7effba397d7bbbcb4b4c39760daf4796ceb876823ae1a87ade022L73

**Comment by mtrmac** [comment]
Thanks for your report.

To clarify, there is not _server_ managed by this code (and the “server” naming is for old historical reasons, something we should probably fix).

WRT the changing the default, I’d personally prefer to get out of the business of defining cryptography policy at all, and to leave that to the language runtime. I’m not sure how viable that is, though.

**Comment by mtrmac** [comment]
Filed #1963 .
