### ISSUE TITLE
Why gpgme instead of native openpgp?

### ISSUE THREAD

**Issue by mikeatlas** [containers/image#197]
In the `signature` package, the [`mechanism`](https://github.com/containers/image/blob/master/signature/mechanism.go) source uses a cgo wrapper for GnuPG Made Easy library: [`github.com/mtrmac/gpgme`](http://github.com/mtrmac/gpgme). Is there a reason why this was chosen over pure [Go's native OpenPGP](https://godoc.org/golang.org/x/crypto/openpgp) package?

Thanks.

**Comment by mtrmac** [comment]
Please see the extensive discussion currently happening in https://github.com/projectatomic/skopeo/issues/274 ; let’s discuss there instead of splitting that into two places.

**Comment by mikeatlas** [comment]
Thanks
