### ISSUE TITLE
http auth scope parsing fails with multiple scopes

### ISSUE THREAD

**Issue by filippog** [containers/image#1972]
Hi,
Thank you for your work on Podman! We are using it to pull, build and push container images to/from gitlab
16.0.1 registry. Pull works as expected, whereas pushing fails with the following 
error:

```
$ podman push $IMAGE_TAG
Getting image source signatures
Copying blob sha256:4f797c4e564a3c2d027b3b9f4e13dc8d09368eb0c5add8793dd02467a39216ac
Copying blob sha256:116579b5e2e7c79f657a3c4a09d3f5cdf6be55c092937e9305782fe59aea5d91
Copying blob sha256:8553b91047dad45bedc292812586f1621e0a464a09a7a7c2ce6ac5f8ba2535d7
Copying blob sha256:6a8415b7c0036ca81fb161989d5ac1e46b7d41bff5268fec8a712284c1d3a742
Copying blob sha256:0c5c51c952396c73ae2528fb96fe98203adaeda4ea9310279ea0c7b660163d05
Copying blob sha256:f708fd99d91802f0165b0b2b5c85690b97deec2e82a0a4fdc8fc0e746e9eb17b

time="2023-05-31T10:01:56Z" level=error msg="Failed to parse the authentication
scope from the given challenge" challenge="{bearer map[error:insufficient_scope
realm:https://gitlab.foo.bar/jwt/auth scope:repository:repos/repo1:pull,push
repository:repos/repo2:pull service:container_registry]}" error="error parsing
auth scope: 'repository:repos/repo1:pull,push repository:repos/repo2:pull'"
scope="repository:repos/repo1:pull,push repository:repos/repo2:pull"

time="2023-05-31T10:01:56Z" level=error msg="Failed to parse the authentication
scope from the given challenge" challenge="{bearer map[error:insufficient_scope
realm:https://gitlab.foo.bar/jwt/auth scope:repository:repos/repo1:pull,push
repository:repos/repo2:pull service:container_registry]}" error="error parsing
auth scope: 'repository:repos/repo1:pull,push repository:repos/repo2:pull'"
scope="repository:repos/repo1:pull,push repository:repos/repo2:pull"

time="2023-05-31T10:01:56Z" level=error msg="Failed to parse the authentication
scope from the given challenge" challenge="{bearer map[error:insufficient_scope
realm:https://gitlab.foo.bar/jwt/auth scope:repository:repos/repo1:pull,push
repository:repos/repo2:pull service:container_registry]}" error="error parsing
auth scope: 'repository:repos/repo1:pull,push repository:repos/repo2:pull'"
scope="repository:repos/repo1:pull,push repository:repos/repo2:pull"
```

From a cursory look at the code, the error comes from https://github.com/containers/podman/blob/main/vendor/github.com/containers/image/v5/docker/docker_client.go#L507 and `parseAuthScope` does indeed expect only one scope: https://github.com/containers/podman/blob/main/vendor/github.com/containers/image/v5/docker/wwwauthenticate.go#L75

**Comment by mtrmac** [comment]
Thanks for your report.

Yes, that would fail, and we need to look into whether/how that should be handled.

OTOH, we should already be asking for the right scope; this happens only on a secondary authentication path. I wonder why the primary path is failing in the first place. Is it possible that your credentials just don’t allow the push at all? Or maybe that your current credentials don’t allow pulling from `repos/repo2` (but you did pull from that location with some other credentials previously, triggering a reuse attempt)?

---


And, those are logged errors on that secondary authentication path, but that path does not actually _directly_ cause anything to fail. I’d expect to exist an error message recording the _actual reason to fail_ (in this case, probably some permission denied with that the secondary authentication was trying to recover from).

Please collect a full `podman --log-level=debug push …` output.

**Comment by mtrmac** [comment]
> ```
> time="2023-06-02T07:19:48Z" level=debug msg="Detected insufficient_scope error, will retry request with updated scope"
> time="2023-06-02T07:19:48Z" level=debug msg="GET https://gitlab.foo.bar/jwt/auth?scope=repository%3Arepos%2Frepo1%3Apull%2Cpush&scope=repository%3Arepos%2Frepo1%3Apull%2Cpush&service=container_registry"
> ```
So we are getting an `insufficient_scope` error. In response for that we ask for two scopes: 1. the one we hard-code, and we already got a token for, and 2. the one the registry is complaining about. The URL above shows that — but the two are identical!

Assuming this isn’t an artifact of an inaccurate log redaction, that sounds like something that needs to be diagnosed server-side. Why is the registry reporting “insufficient scope” for a scope that has already been granted?

---

> ```
> Error: writing blob: initiating layer upload to /v2/repos/repo1/blobs/uploads/ in registry.gitlab.foo.bar: requested access to the resource is denied
> ```

This is the actual upload-terminating failure.

And more details in the error log:
> ```
> time="2023-06-02T07:19:48Z" level=debug msg="Error initiating layer upload, response http.Response{Status:\"401 Unauthorized\", StatusCode:401, Proto:\"HTTP/1.1\", ProtoMajor:1, ProtoMinor:1, Header:http.Header{\"Connection\":[]string{\"keep-alive\"}, \"Content-Length\":[]string{\"244\"}, \"Content-Type\":[]string{\"application/json\"}, \"Date\":[]string{\"Fri, 02 Jun 2023 07:19:55 GMT\"}, \"Docker-Distribution-Api-Version\":[]string{\"registry/2.0\"}, \"Server\":[]string{\"nginx\"}, \"Www-Authenticate\":[]string{\"Bearer realm=\\\"https://gitlab.foo.bar/jwt/auth\\\",service=\\\"container_registry\\\",scope=\\\"repository:repos/repo1:pull,push\\\",error=\\\"insufficient_scope\\\"\"}, \"X-Content-Type-Options\":[]string{\"nosniff\"}}, Body:(*http.bodyEOFSignal)(0xc000728b80), ContentLength:244, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc000820000), TLS:(*tls.ConnectionState)(0xc000656160)}"
> ```

And again it is complaining about a scope that was _granted_ in every earlier `/jwt/auth` call; at least I can’t find anything to suggest a `/jwt/auth` call has ever failed.

**Comment by filippog** [comment]
> > ```
> > time="2023-06-02T07:19:48Z" level=debug msg="Detected insufficient_scope error, will retry request with updated scope"
> > time="2023-06-02T07:19:48Z" level=debug msg="GET https://gitlab.foo.bar/jwt/auth?scope=repository%3Arepos%2Frepo1%3Apull%2Cpush&scope=repository%3Arepos%2Frepo1%3Apull%2Cpush&service=container_registry"
> > ```
> 
> So we are getting an `insufficient_scope` error. In response for that we ask for two scopes: 1. the one we hard-code, and we already got a token for, and 2. the one the registry is complaining about. The URL above shows that — but the two are identical!
> 
> Assuming this isn’t an artifact of an inaccurate log redaction, that sounds like something that needs to be diagnosed server-side. Why is the registry reporting “insufficient scope” for a scope that has already been granted?

Thank you for your help, I have double checked the non-redacted log and the requested repos are indeed the same! I have opened an issue with gitlab registry upstream here: https://gitlab.com/gitlab-org/gitlab/-/issues/414402

**Comment by mtrmac** [comment]
@filippog reading https://gitlab.com/gitlab-org/gitlab/-/issues/414402 suggests that this was caused by a missing `podman login`; and in that case the non-debug-log
```
Error: writing blob: initiating layer upload to /v2/repos/repo1/blobs/uploads/ in registry.gitlab.foo.bar: requested access to the resource is denied
```

seems basically appropriate.

Is there anything that needs to be fixed in c/image?

**Comment by filippog** [comment]
Hello @mtrmac ! That's indeed the case, the root cause was a missing `podman login`. Thank you for your help here, I don't think there's anything else actionable here, closing!

**Comment by mtrmac** [comment]
Thanks for the confirmation.
