### ISSUE TITLE
Creation of Zstd:chunked layers seems racy

### ISSUE THREAD

**Issue by mtrmac** [containers/image#1979]
Reading the code (not testing this),
https://github.com/containers/image/blob/32e14695e9fda522a8b227299d8fb6185af33e5d/storage/storage_dest.go#L604 creates a layer, and https://github.com/containers/image/blob/32e14695e9fda522a8b227299d8fb6185af33e5d/storage/storage_dest.go#L612 later fills the contents.

AFAICS the layer is, in the meantime, visible to other processes, who can find it based on the deterministic “chain ID”, and try to use it, while the contents are missing.

Cc: @giuseppe

**Comment by giuseppe** [comment]
this was added before we had something like `PutLayer` that combines `CreateLayer` and `ApplyDiff`.

We may need something like `CreateLayerFromStagingDirectory` to solve the problem in a similar way

**Comment by giuseppe** [comment]
opened a PR for c/storage: https://github.com/containers/storage/pull/1826

**Comment by mtrmac** [comment]
#2301 has completed the fix.
