### ISSUE TITLE
Docs unclear about whether ostree is default

### ISSUE THREAD

**Issue by andrewbaxter** [containers/image#1988]
The readme currently says
> This library, by default, also depends on the GpgME and libostree C libraries. Either install them:
> ...
> or use the build tags described below to avoid the dependencies (e.g. using go build -tags …)

But the listed ostree tag is `containers_image_ostree` which does the opposite.  I think originally `_stub` was the tag, and this was changed in https://github.com/containers/image/pull/587 but the above text wasn't updated.

**Comment by mtrmac** [comment]
Thanks for your report. #1989 should make that a bit better.
