### ISSUE TITLE
Fails to convert manifest.List to manifest.Schema2List

### ISSUE THREAD

**Issue by leogps** [containers/image#2057]
Release Version: v5.26.1
Previously working on v5.24.2

For nginx image: nginx:1.14.2

```
// Build imageSource
ref, err := alltransports.ParseImageName("nginx:1.14.2")
src, _ := ref.NewImageSource(ctx, sys)

// Build Image 
im, err := image.FromUnparsedImage(ctx, sys, image.UnparsedInstance(src, nil))
// Get manifest byte array
manifestByteArray, mediaType, _ = im.Manifest(ctx)

// List from bytearray
list, err := manifest.ListFromBlob(manifestByteArray, mediaType)
schema2List := list.(*manifest.Schema2List) // Here it panics
```

In this case, err is nil but conversion fails with panic
```panic: interface conversion: manifest.ListPublic is *manifest.Schema2List, not *manifest.Schema2ListPublic [recovered]```
```panic: interface conversion: manifest.ListPublic is *manifest.Schema2List, not *manifest.Schema2ListPublic```

This was working on version: v5.24.2.
Looks like manifest.ListPublic and manifest.Schema2ListPublic were frozen internally and added aliases to these interfaces. There needs to be a way to convert List to Schema2List without issues.

**Comment by mtrmac** [comment]
Thanks for your report.

It was never documented that `manifest.ListFromBlob` returns instances of any specific type. The documentation of `List` says
```go
// Callers can either use this abstract interface without understanding the details of the formats,
// or instantiate a specific implementation (e.g. manifest.OCI1Index) and access the public members
// directly.
```

In this case, you should be able to run `manifest.Schema2ListFromManifest` to get the schema2-specific type.

**Comment by mtrmac** [comment]
Assuming this works as documented, please reopen if that’s not the case.
