### ISSUE TITLE
Copies with Zstd compression to schema-agnostic transports don’t trigger schema conversion

### ISSUE THREAD

**Issue by mtrmac** [containers/image#2195]
E.g.
```console
skopeo copy --dest-compress --dest-compress-format=zstd dir:uncompressed-schema2 dir:dest
```
fails with `FATA[0000] creating an updated image manifest: preparing updated manifest, layer "sha256:…": zstd compression is not supported for type "application/vnd.docker.image.rootfs.diff.tar"`

because `determineManifestConversion` sees that all formats are accepted, and thinks that there is no reason to try anything but the source format.

**Comment by rhatdan** [comment]
@giuseppe FYI

**Comment by mtrmac** [comment]
Related, still outstanding: https://github.com/containers/image/issues/2205 .
