### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by rahilarious** [containers/image#2246]
According to https://github.com/containers/image/compare/v5.29.0...main

From current HEAD to v5.29.0 there have been:
Commits 95
Files changed 54  with 1,253 additions and 341 deletions. 

and there have been some security fixes in x/crypto

**Comment by mtrmac** [comment]
Thanks for reaching out.

I believe a release will happen in some weeks… there isn’t really a strong headline feature to advertise (the Zstd-related work is still ongoing).

WRT `x/crypto`, `x/crypto/ssh` is not called from c/image at all, so it doesn’t warrant tagging a release. (Nothing prevents consumers of c/image from updating x/crypto in their projects if some process of theirs requires that.)

**Comment by rahilarious** [comment]
thanks for the info
