### ISSUE TITLE
docker→OCI conversion should differentiate compressed and uncompressed layers

### ISSUE THREAD

**Issue by mtrmac** [containers/image#229]
Right now, in `manifestSchema2.convertToManifestOCI1`, we assume that all input layers are gzipped, which is not generally the case. We should somehow detect this (e.g. `copy.copyLayers` does actually know the true format at some point) and use the correct MIME type.

**Comment by runcom** [comment]
I also noticed we should fix the image config when converting from docker v2s2 to OCI :cry: right now we're blindly just changing docker config media type to OCI config media type but that's wrong because docker v2s2 config has "container_config" which OCI doesn't have. Let's merge #223 and re-iterate ok?

**Comment by mtrmac** [comment]
Yes, that’s why I filed this as a separate issue.

**Comment by runcom** [comment]
> Right now, in manifestSchema2.convertToManifestOCI1, we assume that all input layers are gzipped,

schema2 to oci1 is always gzipped layers afaict - there's no such "no-gzipped" layers in docker v2s2

**Comment by mtrmac** [comment]
> > Right now, in manifestSchema2.convertToManifestOCI1, we assume that all input layers are gzipped,

> schema2 to oci1 is always gzipped layers afaict - there's no such "no-gzipped" layers in docker v2s2

Good point, `dockerd always compresses the layers when pushing; but it does do format autodetection when pulling and supports both uncompressed layers and non-gzip compression formats.

When both us and `dockerd` send layers compressed using gzip, so just assuming gzip should be good enough.
