### ISSUE TITLE
Podman cannot pull image from local registry 

### ISSUE THREAD

**Issue by Koncpa** [containers/image#2303]
When I tried install operator via operator-sdk to minikube, podman pull local registry failed and operator deployment wasn't successful. A provide required setup for local registry as insecure registry and specified port and also running bundle was with required options as using just http. When I provided manual podman pull on host, I was able to pull registry.

`[root@storageqe-85 install_upstream_tang-operator]# podman pull localhost:5000/tang-operator-bundle
Trying to pull localhost:5000/tang-operator-bundle:latest...
Getting image source signatures
Copying blob 16a666ebb5da skipped: already exists  
Copying blob 7233f72bfd4f skipped: already exists  
Copying blob 7f86b88e335b skipped: already exists  
Copying config 7d9894a32e done   | 
Writing manifest to image destination
7d9894a32e030d368d440124661ec89a066e4aeabae26ec9ab9a342d5fb93603
`

Expected behavior vs. Current behavior
podman pull image from local registry vs. podman pull from local registry failed.

Logs:

```
Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m42s                   default-scheduler  Successfully assigned default/c1990a48a40c4a698b0fa41b86eb58b661df9ac090f34624f22153a46bdmpft to minikube
  Normal   Pulled     9m41s                   kubelet            Container image "quay.io/operator-framework/olm@sha256:30481639e89a0cb282fc1855c1bfdde96ec5ee36d1c651c2d0d79c8d249e3ed5" already present on machine
  Normal   Created    9m41s                   kubelet            Created container util
  Normal   Started    9m41s                   kubelet            Started container util
  Warning  Failed     8m19s (x5 over 9m39s)   kubelet            Error: ImagePullBackOff
  Normal   Pulling    8m6s (x4 over 9m40s)    kubelet            Pulling image "localhost:5000/tang-operator-bundle:latest"
  Warning  Failed     8m6s (x4 over 9m40s)    kubelet            Failed to pull image "localhost:5000/tang-operator-bundle:latest": Error response from daemon: Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused
  Warning  Failed     8m6s (x4 over 9m40s)    kubelet            Error: ErrImagePull
  Normal   BackOff    4m33s (x21 over 9m39s)  kubelet            Back-off pulling image "localhost:5000/tang-operator-bundle:latest"

```

**Comment by vrothberg** [comment]
Please fill out the request issue template.  We need more information such as the version of Podman and the environment.

Since a manual pull works, I am under the impression something else (than Podman) is wrong.

**Comment by mtrmac** [comment]
I agree; my first guess would be networking differences for various processes on the machine, vaguely some aspect of Minikube setup / configuration.

If accessing `localhost:5000` is intended, and the error message is `dial tcp [::1]:5000: connect: connection refused`, I feel pretty confident there’s nothing in this c/image library that is the immediate cause, and there’s nothing in this c/image library that can be made to fix the server and/or the network to stop refusing the connection.

**Comment by Koncpa** [comment]
@vrothberg And where I can find requested issue template?

**Comment by mtrmac** [comment]
@Koncpa https://github.com/containers/podman/issues/new?assignees=&labels=kind%2Fbug%2Ctriage-needed&projects=&template=bug_report.yaml shows a Podman form.
