### ISSUE TITLE
OCI image index loose the artifactType property on copy

### ISSUE THREAD

**Issue by AlbanBedel** [containers/image#2460]
When copying an OCI image index with the `artifactType` property set it is re-written to a new version without the `artifactType` property.

To reproduce:
```
$ echo '{"schemaVersion": 2, "manifests": [],    "mediaType": "application/vnd.oci.image.index.v1+json","artifactType": "application/vnd.test.index.v1+json"}' | oras manifest push --oci-layout artifact:v1 -
$ skopeo copy -a oci:artifact:v1 oci:artifact-copy:v1
$ skopeo inspect --raw oci:artifact-copy:v1
```
Notice the missing `artifactType` and the removal of all extra white spaces in the copied manifest.

**Comment by mtrmac** [comment]
Thanks for your report. What version of c/image and Skopeo is this?

**Comment by AlbanBedel** [comment]
Looking at the code in `copyMultipleImages` the issue stem from `OCI1IndexPublic.PublicClone` which rely on `OCI1IndexPublicFromComponents` so it only copy the mediaType, manifests list and annotations. So I suppose the same issue will happen with the subject field as well, or any other fields that might be added in the future.

**Comment by mtrmac** [comment]
Ah, thanks. I was looking at the single-arch image copy path.
