### ISSUE TITLE
Add 'Env' to to imageInspectInfo

### ISSUE THREAD

**Issue by twaugh** [containers/image#248]
When [atomic-reactor](https://github.com/projectatomic/atomic-reactor) examines a Dockerfile and wants to know the value of a label after environment variable substitution, currently it must pull the parent image in order to be able to resolve environment variables.

It would be really useful if a remote image could be inspected to determine its environment variables instead of needing to pull it.

**Comment by rhatdan** [comment]
@twaugh @mtrmac @vrothberg Is this still an open issue, it has been two years.  I don't think anyone is working on it, should we close?

**Comment by twaugh** [comment]
We still have to use the same work-around as before. We pull the parent image for literally no other reason that to know its environment variables.

"skopeo inspect" already has this information (it shows the labels) but it throws it away.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg Is this something you guys have time to  add or should I get someone else to work on it?

**Comment by vrothberg** [comment]
Adding the good first issue label. Thanks for reviving, Dan!
