### ISSUE TITLE
How to change the policy.json default path?

### ISSUE THREAD

**Issue by ugiwgh** [containers/image#2493]
The policy.json default path is /etc/containers/policy.json or $HOME/.config/containers/policy.json.
In vendor/github.com/containers/image/v5/types/types.go, I get, it can be changed by setting RootForImplicitAbsolutePaths.
But I don't know how to set RootForImplicitAbsolutePaths.

**Comment by mtrmac** [comment]
Thanks for reaching out.

Typically, if you want to use a specific non-default file, that would be done by setting `SystemContext.SignaturePolicyPath`. But `RootForImplicitAbsolutePaths` might also be appropriate in some situations.

> But I don't know how to set RootForImplicitAbsolutePaths

I don’t really know how to answer that. This is a Go package providing a Go API, and nothing about that value is special in this respect.

**Comment by mtrmac** [comment]
Please reopen if there are more outstanding questions.
