### ISSUE TITLE
local registry copy

### ISSUE THREAD

**Issue by zeddii** [containers/image#250]
I'm currently using skopeo and umoci to manipulate OCI images in a docker free runtime.

I've been through the code, and as many READMEs/tutorials as I can find, and I still can't determine if I should expect that a copy to a local registry (from an oci image) should then be something I can copy again locally.

What I mean by that, is that I can copy an image to a docker registry (local or not), but I can never copy it back, find or otherwise manipulate it .. even though the first copy returns success.

i.e.: 
% skopeo copy oci:foo docker://localhost:5000/foo

works.

But I can never do anything like:

% skopeo copy docker://localhost:5000/foo oci:bar

.. I always get a "manifest unknown" error variant, and debugging from the registry side, I indeed can't see the image being returned as valid from the registry.

Before I sink more hours into this (and start hacking code), I'm wondering if I should expect this to work.

**Comment by mtrmac** [comment]
Yes, such docker-free copies should work (by actually converting to docker schema2 because docker/distribution registries so far do not support native OCI images).

Looking at skopeo’s `integration/copy_test.go:TestCopyOCIRoundTrip`, this should just work, at least against the server version used in the test.

**Comment by zeddii** [comment]
Right you are.  I just checked and in the two weeks since I pulled my support libs, a fix when into the registry copy and now the right tags are being created, and hence the manifest found.

Sorry for the noise, but thanks for the quick reply .. it made me take a second look at how fresh my code was.
