### ISSUE TITLE
Wrong build instructions in README

### ISSUE THREAD

**Issue by hferentschik** [containers/image#270]
From the README:

> For ordinary use, go build ./... is sufficient.
>  
> When developing this library, please use make to take advantage of the tests and validation.

That is not quite correct, if you check out the source, you will first need to run _make vendor_ before being able to run _go build_. 

On this note I am wondering why the actual _go build_ is not integrated into the _Makefile_, depending on vendor. In fact, imo it should be the default target.

You should be able to checkout the sources and run _make_ and everything gets bootstrapped and compiled.

**Comment by mtrmac** [comment]
Thanks for pointing this out, the instructions definitely need changing.

Though, it's not _entirely_ obvious what is the right thing to say in there: containers/image is a library-only package, so building it separately does not give the user anything immediately useful, whatever the build instructions are. Adding a default `make` target AFAICT does not change this.

We could provide some instructions for integrating the library into a caller.

Or we could just point at `skopeo` and tell users to try building that instead to have something to experiment with.

I guess, preferably, both?

**Comment by hferentschik** [comment]
> so building it separately does not give the user anything immediately useful, 

Sure, but what's about development? Would it not make sense for development purposes to have the build part of the Makefile. 

Consumers will indeed not see any of this.

**Comment by mtrmac** [comment]
> Sure, but what's about development? Would it not make sense for development purposes to have the build part of the Makefile.

For development, the current default (get all tools, run tests) broadly makes sense. Sure, adding a `go build ./...` step in there to catch subpackages with no tests would be great; I currently use `go build ./... && make` as my primary compile/test step, and folding that into a simple `make` would be better.
