### ISSUE TITLE
Valid oci reference names disallowed

### ISSUE THREAD

**Issue by owtaylor** [containers/image#294]
The rules for a valid `org.opencontainers.image.ref.name` at:

     https://github.com/opencontainers/image-spec/blob/master/annotations.md

Are quite different from the checks in the code, which seem to be (in oci_transport.go)

     var refRegexp = regexp.MustCompile(`^([A-Za-z0-9._-]+)+$`)

For example, `app/org.gnome.eog/x86_64/master` is valid by the former set of rules and not by the later. (See projectatomic/skopeo#369)

**Comment by runcom** [comment]
Nice catch

**Comment by owtaylor** [comment]
In  projectatomic/skopeo#369 mtrmac said:
> (We may have to break the transport syntax now that an arbitrary number of : is allowed in the .tag :( )

Looking at the code in `oci/layout/oci_transport.go` I'm wondering if that is necessary - the code disallows ":" in the path component, so that (as I understand it) you can set a policy on /a/b:c and have that be unambiguously refer to path=/a/b, tag=c. Since ':' is not allowed in the path, then I think it should be possible to simply change:

    + sep := strings.LastIndex(reference, ":")
    - sep := strings.Index(reference, ":")

If that doesn't work out for some reason, I think "::" would make sense as a separator since the ref-name syntax doesn't allow consecutive separator characters, and most single characters that aren't allowed in the ref-name are problematical in some way (|, $, etc.).

**Comment by mtrmac** [comment]
This was fixed in #318.

**Comment by rhatdan** [comment]
@mtrmac If it is fixed, close the issue.

**Comment by mtrmac** [comment]
Right, I meant to do that and somehow didn’t.
