### ISSUE TITLE
*: gating different drivers behind build tags

### ISSUE THREAD

**Issue by cyphar** [containers/image#296]
I'm not sure if we've discussed this before, but if we want to have a library that implements all manner of image formats and schemes we need to make it possible for users of this library to opt out of the dependencies if they're not going to use a particular driver.

For example, if I want to build `skopeo` without `ostree` support that is currently not possible. Should we add `noostree` and similar buildtags to each of the image schemes? Or do you feel that'll cause issues?

**Comment by runcom** [comment]
I'm +1 on this.

**Comment by mtrmac** [comment]
> For example, if I want to build `skopeo` without `ostree` support that is currently not possible. 

It actually is possible now, with https://github.com/containers/image/pull/290 . (To be fair, vendored into `skopeo` only yesterday, and undocumented in skopeo. We should probably add that documentation—or #359 vaguely talks about autodetection.)

> Should we add noostree and similar buildtags to each of the image schemes?

(As a side note, many users of the _library_ who need only specific transports can import only those transports and minimize dependencies. Only explicitly pulling in `alltransports`, whether as such or for `alltransports.ParseImageName`, gets all of them.)

I’m fine with allowing to opt out of the transports with non-trivial dependencies; I would be less enthusiastic (though probably could still be persuaded) about a blanket policy of making all transports optional, even the self-contained ones like `dir:` or `oci:`. It seems to me that the _transport_`:`… syntax provided by `containers/image/transports/alltransports` is more useful to users when they can generally expect the syntax to work the same everywhere, without bothering about which individual tools (and specific builds/packages of those tools) actually support which transports.

**Comment by cyphar** [comment]
Ah, I didn't see that PR @mtrmac. But yes, my suggestion only applies for things with non-trivial dependencies.

**Comment by rhatdan** [comment]
I believe we have this now, and this is a rather old issue, I am closing please reopen if you think we should still work on this.
