### ISSUE TITLE
docker:// requires root now due to certs.d

### ISSUE THREAD

**Issue by cyphar** [containers/image#297]
I understand that `certs.d` is needed but it means that you cannot run `skopeo` as an unprivileged user anymore due to the readability of `/etc/docker/cert.d` by normal users. This was actually a fairly big selling point of `skopeo` over `docker pull` because requiring `root` to download files of the internet doesn't make any sense.

It looks like you might be able to configure `skopeo` to not require this anymore by creating your own `certs.d` which you then point `skopeo` at, but I'm not really sure what it should contain and I don't believe there's any docs on this.

Would it be possible to disable `certs.d` usage or something? This makes the value proposition of rootless containers using `skopeo` weaker unfortunately...

**Comment by rhatdan** [comment]
skopeo should check if you are non root and then work the old way.  It should not require the use of a certs directory.

**Comment by rhatdan** [comment]
We definitely want skopeo to work without requiring privs.

**Comment by mtrmac** [comment]
Yeah, @runcom , IIRC we have discussed this on IRC, and just failed to capture this / fix it.  I can’t find the original conversation anymore; can you?

Just silently ignoring the client cert/key should be trivially safe. Silently ignoring a CA seems riskier, but `setupCertificates` always uses `tlsconfig.SystemCertPool` and only _appends_ the configured CA, so silently ignoring the one in `certs.d` can only cause unexpected failures, but not connection to untrusted servers.

So it seems that we could have `setupCertificates` handle a permission error by (a report in the debug log and) proceeding as if there is no subdirectory in `certs.d`. Unless I am missing something, or something else was pointed out in that IRC conversation.

**Comment by rhatdan** [comment]
Should it even be logged if the user is running as non-root?

**Comment by mtrmac** [comment]
At least at the debug level (not enabled by default), yes. We have originally implemented `certs.d` after reports of _very_ non-intuitive failures when trying to access RH images from a CDN (“repository not found” or something like that), and any unprivileged user without access to the CDN cert will hit that; I think there should be at least _something_ to suggest to them what they might want to look into.
