### ISSUE TITLE
Certificate signed by unknown authority error for copy.Image

### ISSUE THREAD

**Issue by hferentschik** [containers/image#299]
I am trying to use copy.Image to copy an image from a Docker daemon running in a local VM. Here is the code:

	srcRef, err := alltransports.ParseImageName("docker://192.168.99.129:2376/openshift/origin:v1.5.1")
	if err != nil {
		atexit.ExitWithMessage(1, fmt.Sprintf("Invalid source: %v", err))
	}
	destRef, err := alltransports.ParseImageName("oci:/Users/hardy/tmp-2/oci")
	if err != nil {
		atexit.ExitWithMessage(1, fmt.Sprintf("Invalid destination %v", err))
	}

	err = copy.Image(policyContext, destRef, srcRef, &copy.Options{
		RemoveSignatures: false,
		SignBy:           "",
		ReportWriter:     os.Stdout,
		SourceCtx:        sourceContext(),
		DestinationCtx:   &types.SystemContext{},
	})
	if err != nil {
		atexit.ExitWithMessage(1, fmt.Sprintf("Copy failed: %v", err))
	}

_sourceContext_ looks like this:

	ctx := &types.SystemContext{
		DockerCertPath:    "/Users/hardy/.minishift/certs",
		DockerInsecureSkipTLSVerify: false,
	}
	
	return ctx

When running this, I get:

    Copy failed: Error initializing image from source docker://192.168.99.129:2376/openshift/origin:v1.5.1: pinging docker registry returned: Get https://192.168.99.129:2376/v2/: x509: certificate signed by unknown authority

The daemon is running and if I set the the following environment variables in my console, I can use the Docker CLI without any issues:

    export DOCKER_TLS_VERIFY="1"
    export DOCKER_HOST="tcp://192.168.99.129:2376"
    export DOCKER_CERT_PATH="/Users/hardy/.minishift/certs"

Any ideas? Am I missing something in the code creating the source and destination references and contexts?

**Comment by hferentschik** [comment]
For what it's worth, if I change the TLS verify option to:

    DockerInsecureSkipTLSVerify: true

I'll get:

    Copy failed: Error initializing image from source docker://192.168.99.129:2376/openshift/origin:v1.5.1: pinging docker registry returned: Get http://192.168.99.129:2376/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

**Comment by mtrmac** [comment]
Most importantly, the `docker://` transport connects to docker _registries_, not _daemons_. Is that a typo or are you really trying to connect to a remote daemon? If the latter, that would be done using the `docker-daemon:` transport, but that transport doesn’t currently support connecting to non-`localhost` (https://github.com/containers/image/pull/149).

As for TLS, what does the `logrus` debug-level output say? It should include the exact paths and certificates being used.

If nothing in there looks fishy, I don’t know. Perhaps use `openssl x509 -text < $your_ca_file` and `openssl s_client -showcerts -connect $host:$port` to see if the files and the server really do match.

**Comment by mtrmac** [comment]
(For the `DockerInsecureSkipTLSVerify:True` case, the full `logrus` debug log could also be useful.)

**Comment by hferentschik** [comment]
> Most importantly, the docker:// transport connects to docker registries, not daemons. Is that a typo or are you really trying to connect to a remote daemon?

Ahh, that's a misunderstanding then. 

 > If the latter, that would be done using the docker-daemon: transport, but that transport doesn’t currently support connecting to non-localhost (#149).

I guess that's what I need, but it seems there will be an issue with that.

> As for TLS, what does the logrus debug-level output say? It should include the exact paths and certificates being used.

How do I enable logrus debug output. I am loosing track how many different log frameworks are by now included in Minishift by the mere fact of the various dependencies :-(

**Comment by mtrmac** [comment]
> How do I enable logrus debug output. 

`logrus.SetLevel(logrus.DebugLevel)` I believe.

Also, quite a few experiments are easier/faster to do using the `skopeo` command-line utility, than writing Go code, e.g. `skopeo --debug copy …`.

**Comment by hferentschik** [comment]
Closing this issue. Turns out what is needed is the ability to configure a remote Docker daemon connection. See #149.
