### ISSUE TITLE
enhance help messages

### ISSUE THREAD

**Issue by runcom** [containers/image#31]
was contacted today because people could not figure out the right syntax for `skopeo inspect`  and they were trying `skopeo inspect fedora`.

would be nice to provide better help messages in *all* commands (not just `inspect`) and tell ppl about our image *prefixies* e.g. `docker://`, `atomic:`, `oci:` etc

/cc @TomasTomecek @mtrmac

**Comment by TomasTomecek** [comment]
https://github.com/projectatomic/skopeo/pull/134

**Comment by runcom** [comment]
right, I mistaken repository lol
