### ISSUE TITLE
Support configure Docker daemon source and destination via SystemContext settings

### ISSUE THREAD

**Issue by hferentschik** [containers/image#327]
Create the Docker daemon client from environment settings. See also pull request #149

**Comment by hferentschik** [comment]
See pull request #328

**Comment by rhatdan** [comment]
@hferentschik  @mtrmac @vrothberg What is the state of this issue? Can we close it?

**Comment by vrothberg** [comment]
https://github.com/containers/image/pull/328 fixed that, closing.
