### ISSUE TITLE
[Docker] CredsStore support

### ISSUE THREAD

**Issue by r2d4** [containers/image#334]
I'm trying to use a private GCR registry with this library.  I've set up a service account with the proper credentials as documented in the bottom of https://cloud.google.com/container-registry/docs/advanced-authentication under `Using a JSON key file`

It seems like [`getAuth` ](https://github.com/containers/image/blob/dec75a46e65489eb3d04e8e851190916531e6e38/docker/docker_client.go#L401)will try to parse my `~/.docker/config.json` file, however [`decodeDockerAuth`](https://github.com/containers/image/blob/dec75a46e65489eb3d04e8e851190916531e6e38/docker/docker_client.go#L550) will only try to parse username and password.   

GCR uses the `credsStore` feature which shells out to https://github.com/GoogleCloudPlatform/docker-credential-gcr.  My `~/.docker/config` then looks like 
```
{
	"auths": {
		"https://appengine.gcr.io": {},
		"https://asia.gcr.io": {},
		"https://b.gcr.io": {},
		"https://beta.gcr.io": {},
		"https://bucket.gcr.io": {},
		"https://eu.gcr.io": {},
		"https://gcr.io": {},
		"https://gcr.kubernetes.io": {},
		"https://us.gcr.io": {}
	},
	"credsStore": "gcr"
}
```  

It looks like we might be able to use some of the helper functions here: https://github.com/docker/docker-ce/blob/master/components/cli/cli/config/configfile/file.go to parse the `~/.docker/config.json` file and get credentials.

Let me know if I'm overlooking something obvious here.  I'd definitely be up to implement the needed change, whatever it is.

**Comment by mtrmac** [comment]
You’re not overlooking anything, this is not currently supported. An implementation of this would be very welcome.

**Comment by runcom** [comment]
Yeah, thanks for pointing this out

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by umohnani8** [comment]
@rhatdan Should I work on adding this support as well to the authentication package?

**Comment by runcom** [comment]
this can be closed now though

**Comment by rhatdan** [comment]
@umohnani8 yes

**Comment by r2d4** [comment]
Thanks for the quick resolution!
