### ISSUE TITLE
Add kerberos and SSH support to containers/image to pull from a container registry.

### ISSUE THREAD

**Issue by rhatdan** [containers/image#345]
Would need to add support to OpenShift Registry as well but this would give us  a better security story then storing base64 encoded passwords.  

It would show leadership in containers/image also

**Comment by rhatdan** [comment]
@mtrmac @vrothberg Is this something we should consider or just close it?

**Comment by vrothberg** [comment]
I opt for closing given kernel keyrings are getting namespaced.
