### ISSUE TITLE
Store image Digest from ostree_transport

### ISSUE THREAD

**Issue by giuseppe** [containers/image#347]
I'd like to store the `"Digest":` information that is given by Skopeo inspect into the OSTree metadata when pulling a new image.  I could do this separately but: 1) it will require another process/request 2) have to overwrite the metadata once it is written by containers/image.  I don't see any immediate way for doing this, is there a way for doing this from `ostree_transport.go`.  Is there a way from accessing this information when writing the image to the storage?  Could it be added to the manifest given by `PutManifest`?

**Comment by mtrmac** [comment]
Could you be more precise, please? I am probably missing a fair amount of context.

- Digest of what? manifest list / manifest / config / blobs? (Note that the pull may use a digest of the manifest list, which does not match the architecture-specific manifest!)
- By what? The `ostree:` transport? If so, how do processes figure in this?

My best guess is that you want to know a manifest digest in `PutManifest`; in that case, `manifest.Digest` can compute it from the manifest blob, and it is cheap enough to compute there even if it were known previously. (OTOH see the note above about manifest lists vs. architecture-specific manifests; `PutManifest` doesn’t have access to the manifest list digest.)

**Comment by giuseppe** [comment]
it is literally called `Digest` in the `skopeo inspect` output.  I was using the name `Digest` referring to the Skopeo output and I believe it is the v2 image digest.
With system containers we used it for comparison of the images version.  While I could also use any other kind of checksum on the manifest itself here, I'd like to store the digest in the OSTree metadata, it is quite handly when you want to pull the exact version with the `@sha256:...` format.

**Comment by mtrmac** [comment]
```go
func (d *ostreeImageDestination) PutManifest(manifestBlob []byte) error {
     digest, err := manifest.Digest(manifestBlob)
```
Is there anything that makes the above impossible?

But again, note the difference between manifest lists (what `skopeo inspect` currently gives you) and the individual image manifests (what the code above computes).

**Comment by giuseppe** [comment]
Thanks, that works.  I've opened a PR here:

https://github.com/containers/image/pull/349
