### ISSUE TITLE
Make compilation of storage transport optional

### ISSUE THREAD

**Issue by hferentschik** [containers/image#361]
The storage transport is Unix specific and does not cross compile to Windows, making it impossible to compile containers/image for Windows.

Similar to ostree the storage compilation should be optional and be controlled via build tags.

**Comment by mtrmac** [comment]
See https://github.com/containers/image/pull/355 .

**Comment by hferentschik** [comment]
Ahh, I see. Shall I close this issue or leave it open? Seems #355 is a pull request without a matching issue? I think there is also something missing.

**Comment by mtrmac** [comment]
Well, it still is an issue; I don’t care strongly whether it is kept open. (We don’t require a separately filed issue for each PR.)

The code in #355 seems fine; it needs @runcom to take a look, and rebasing.

**Comment by hferentschik** [comment]
> We don’t require a separately filed issue for each PR

IMO it makes sense since it helps people to determine whether an issue already exists. I did, for example, search the issues to determine whether this was reported before but did not find anything. Hence I created a new issue.

**Comment by rhatdan** [comment]
I would love to see us turn on storage support for Windows...

**Comment by mtrmac** [comment]
This was fixed by #362 AFAICT; please reopen if that’s not the case.
