### ISSUE TITLE
Windows incompatibilities in Docker daemon and OCI transport 

### ISSUE THREAD

**Issue by hferentschik** [containers/image#368]
In the Docker daemon and OCI transport, there are some operations which are not compatible with Windows. For example, _ocArchiveTransport_ makes use of non-portable tmp directory in
https://github.com/containers/image/blob/master/oci/archive/oci_transport.go#L197:

```go
    func createOCIRef(image string) (tempDirOCIRef, error) {
    	dir, err := ioutil.TempDir("/var/tmp", "oci")
        //  ...
    	return tempDirRef, nil
    }
```

There are some other places where "/var/tmp" is used which should be addressed as part of the issue. 

Another problem is trying to rename a file while it is still open. On Windows the file needs to be closed first.

**Comment by mtrmac** [comment]
This was fixed in #379 . Thanks!
