### ISSUE TITLE
[RFE] Source/Destination for shared storage

### ISSUE THREAD

**Issue by runcom** [containers/image#38]
Cross posting from https://github.com/projectatomic/skopeo/issues/110

From kubernetes/kubernetes#26788 (comment)

Would be nice to support such a thing in skopeo itself as part of our types

**Comment by humblec** [comment]
@runcom I would like to sign in here on this effort.  If there is a chance to bring Shared network storages for source and Destination, I would like to bring in gluster support to the same.

**Comment by runcom** [comment]
@rhatdan @mtrmac ptal

**Comment by rhatdan** [comment]
Works for me.  We need to do some design around this.

**Comment by humblec** [comment]
@rhatdan sure.

**Comment by mtrmac** [comment]
@runcom Could you describe more precisely what “for shared storage” means? Is it simply a filesystem containing image blobs? A filesystem containing expanded image? Something else?

How does synchronization against multiple writers happen?

**Comment by humblec** [comment]
iic, its about a filesystem containing image blobs.  synchronization against multiple writes should be taken care by the underlying FS. @runcom/@rhatdan can correct me though :)

**Comment by rhatdan** [comment]
@runcom @humblec  @mtrmac @vrothberg What is the state of this issue?  Is anyone working on it? It is two years old, can we close it?

**Comment by vrothberg** [comment]
Yup, let's close it.
