### ISSUE TITLE
docker destination fails on quay.io

### ISSUE THREAD

**Issue by jonboulle** [containers/image#381]
quay.io implements the V2 Docker Registry API, but not yet the V2.2 media types. containers/image is fine copying from it as a source, but when trying to copy to it as a destination, it fails [during the `PutManifest`](https://github.com/containers/image/blob/0136a925854d78a47f785ce009b5fa8ef5f7e810/docker/docker_image_dest.go#L240) because Quay returns a 202:
```
DEBU[0011] Upload of manifest type application/vnd.docker.distribution.manifest.v1+json failed: Error writing manifest: Error uploading manifest to /v2/jonboulle/busybox/manifests/latest: received unexpected HTTP status: 202 ACCEPTED 
```

The [registry API documentation](https://docs.docker.com/registry/spec/api/#pushing-an-image) doesn't explicitly call out whether 202 is supported in this case as it does for when pushing blobs (when it's expected). 

I'm on the fence about whether this is a bug in Quay or not? Docker manages to push to it just fine, so I still suspect this could be handled better in containers/image - whether the specific error handling here or in the fallback

**Comment by runcom** [comment]
> I'm on the fence about whether this is a bug in Quay or not? Docker manages to push to it just fine, so I still suspect this could be handled better in containers/image - whether the specific error handling here or in the fallback

yup, I'll try to fix this, definitely something we can handler better here.

**Comment by jonboulle** [comment]
For what it's worth, the docker/distribution code is pretty broad about what success codes it's happy with in this scenario: https://github.com/docker/distribution/blob/e5b5e44386f7964a1f010a2b8b7687d073215bbb/registry/client/repository.go#L559

**Comment by runcom** [comment]
surely an issue with quay.io according to the registry spec though https://docs.docker.com/registry/spec/api/#put-manifest

**Comment by runcom** [comment]
see https://github.com/containers/image/pull/382

**Comment by jonboulle** [comment]
thanks!!

**Comment by rhatdan** [comment]
@jonboulle Could you tweet about this? 
@runcom should we cut a new skopeo version?  Or should we wait for the enhanced Dir support?

**Comment by runcom** [comment]
> @runcom should we cut a new skopeo version? Or should we wait for the enhanced Dir support?

I'd wait about the Dir enhance if it's ok with you Dan

**Comment by rhatdan** [comment]
SGTM
