### ISSUE TITLE
Return errcode from HasBlob rather than error

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/image#409]
The code in docker_image_dest.go:HasBlob() (https://github.com/containers/image/blob/master/docker/docker_image_dest.go#L193-L205) returns an error which then has to be parsed to determine if the problem was an authorization error, read error from the destination, or other error.  It would be good if it could also (or maybe instead) return an error code.   Then code like what was done in https://github.com/projectatomic/buildah/pull/406 for GetFailureCauses() could check the code rather than parsing the returned error.  This was a suggestion from @ripcurld0.

**Comment by TomSweeneyRedHat** [comment]
I'd add that this is an enhancement request.  I tried to add a label to that effect but was unable to.

**Comment by mtrmac** [comment]
Yeah, `HasBlob` should probably be handling errors consistently with https://github.com/containers/image/pull/390 .
