### ISSUE TITLE
Regression in the returning of inspected labels

### ISSUE THREAD

**Issue by steveb** [containers/image#413]
Since the commit 82b213b, the following command had returned an empty dict instead of fully populated Labels:

`skopeo --debug inspect docker://registry.access.redhat.com/rhosp12/openstack-nova-api:latest`

Since this is a regression and the revert is clean I'm going to propose a PR with the revert.

Whatever the fix, this affects builds of skopeo-0.1.28 so revendoring will be required.

**Comment by mtrmac** [comment]
Thanks for your report.

The revert would work, but also leave us with two copies of the code, one working and one broken; it would ultimately be cleaner to just fix the one copy.

I think I’ve done that on https://github.com/mtrmac/image/tree/305-cleanup , but this shows that we would benefit from tests for the code—so, I’ll add some before submitting that branch as a PR.

**Comment by runcom** [comment]
@nalind PTAL it's related to one of your commit

**Comment by steveb** [comment]
Thanks, I've tried testing projectatomic/skopeo master with image branch 305-cleanup but compile failed:

`cmd/skopeo/inspect.go:100:11: cannot use imgInspect.Created (type *time.Time) as type time.Time in field value
make: *** [Makefile:78: binary-local] Error 2
`
I can test again when requested.

**Comment by steveb** [comment]
I've tested https://github.com/mtrmac/skopeo/tree/305-cleanup and the labels are being returned again.
