### ISSUE TITLE
Slow image pull with ostree backend

### ISSUE THREAD

**Issue by strigazi** [containers/image#442]
I have been using system containers with the ostree backend on Fedora 26 Atomic hosts and Fedora 27 Atomic hosts and I have noticed that in Fedora 27 it is quite slower. The Atomic utility uses skopeo to pull container images which uses this library. I use a couple of applications in system containers: etcd, kubernetes, flannel and an openstack tool and I have timed in a silly (but pragmatic) way the time needed to install the containers in question. Here are the results:

skopeo copy docker:// to ostree:
~120-130 seconds with 4 cores on Fedora 27 Atomic Host and skopeo version 0.1.28 commit: 926e7eb39a036c00d87980894b888594bf2062f3
~112 seconds with improved skopeo with 4 cores on Fedora 27 Atomic Host and skopeo by @giuseppe 
No ostree option in skopeo 0.1.19,  I need to check how it is done there.

atomic install --system:
~160 seconds with 4 cores on Fedora 27 Atomic Host and skopeo version 0.1.28 commit: 926e7eb39a036c00d87980894b888594bf2062f3 contianers/image: https://github.com/projectatomic/skopeo/commit/64b3bd28e37897e1855288befc8d082ecb9dedcc
~180 seconds with 2 cores on Fedora 27 Atomic Host and skopeo version 0.1.28 commit: 926e7eb39a036c00d87980894b888594bf2062f3
~ 97 seconds with 2 cores on Fedora 26 Atomic Host and skopeo version 0.1.19-dev commit: 35d2a045922fa9d7c6dbefd2606cf0043e3d74ba containers/image commit: b95a6b8688d7702cf5906debf87f01cfd849a67a

docker run (just to compare, it is irrelevant to this issue):
~ 81 seconds on Fedora 27 Atomic Host and docker 1.13.1
~ 60 seconds on Fedora 26 Atomic Host and docker 1.13.1

You can reproduce like so:
```
export START=$(date +'(%s)') && \
skopeo copy docker://docker.io/strigazi/etcd:v3.2.7 ostree:etcd:latest && \
skopeo copy docker://docker.io/strigazi/kubernetes-apiserver:v1.9.6 ostree:apiserver:latest && \
skopeo copy docker://docker.io/strigazi/kubernetes-controller-manager:v1.9.6 ostree:controller-manager:latest && \
skopeo copy docker://docker.io/strigazi/kubernetes-scheduler:v1.9.6 ostree:scheduler:latest && \
skopeo copy docker://docker.io/strigazi/kubernetes-kubelet:v1.9.6 ostree:kubelet:latest && \
skopeo copy docker://docker.io/strigazi/kubernetes-proxy:v1.9.6 ostree:kube-proxy:latest && \
skopeo copy docker://docker.io/strigazi/flannel:v0.9.0 ostree:flanneld:latest && \
skopeo copy docker://docker.io/strigazi/heat-container-agent:rawhide ostree:heat-container-agent:latest && \
export END=$(date +'(%s)') && \
echo "Finished in: " $((END-START)) " seconds." 

export START=$(date +'(%s)') && \
atomic install --system --system-package no --storage ostree docker.io/strigazi/etcd:v3.2.7 && \
atomic install --system --system-package no --storage ostree docker.io/strigazi/kubernetes-apiserver:v1.9.6 && \
atomic install --system --system-package no --storage ostree docker.io/strigazi/kubernetes-controller-manager:v1.9.6 && \
atomic install --system --system-package no --storage ostree docker.io/strigazi/kubernetes-scheduler:v1.9.6 && \
atomic install --system --system-package no --storage ostree docker.io/strigazi/kubernetes-kubelet:v1.9.6 && \
atomic install --system --system-package no --storage ostree docker.io/strigazi/kubernetes-proxy:v1.9.6 && \
atomic install --system --system-package no --storage ostree docker.io/strigazi/flannel:v0.9.0 && \
atomic install --system --system-package no --storage ostree --set REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt docker.io/strigazi/heat-container-agent:rawhide && \
export END=$(date +'(%s)') && \
echo "Finished in: " $((END-START)) " seconds." 

export START=$(date +'(%s)') && \
image=docker.io/strigazi/etcd:v3.2.7 && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600 && \
image=docker.io/strigazi/kubernetes-apiserver:v1.9.6 && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600 && \
image=docker.io/strigazi/kubernetes-controller-manager:v1.9.6 && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600 && \
image=docker.io/strigazi/kubernetes-scheduler:v1.9.6 && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600 && \
image=docker.io/strigazi/kubernetes-kubelet:v1.9.6 && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600 && \
image=docker.io/strigazi/kubernetes-proxy:v1.9.6 && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600 && \
image=docker.io/strigazi/flannel:v0.9.0 && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600 && \
image=docker.io/strigazi/heat-container-agent:rawhide && \
docker run -d --entrypoint=/usr/bin/sleep $image 3600
export END=$(date +'(%s)') && \
echo "Finished in: " $((END-START)) " seconds." 

```

**Comment by mtrmac** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I've some WIP in https://github.com/giuseppe/image/tree/ostree-parallel that can improve the situation

But that needs to be better tested

**Comment by strigazi** [comment]
@giuseppe Can I help with testing?

How can can we get this in skopeo soon-ish? :)

**Comment by giuseppe** [comment]
@strigazi could you first confirm if that changes improve the situation for you?

If that is the case I can open a PR, I've done some testing and the changes seem to work for me, I'd need though to test more images and that everything works as expected.

**Comment by rhatdan** [comment]
@mtrmac @strigazi @giuseppe Since we have had no response, I take it this issue is resolved.  Reopen if you disagree.
