### ISSUE TITLE
Some of the dependencies in vendor.conf are not needed

### ISSUE THREAD

**Issue by agonzalezro** [containers/image#443]
It has come to my attention that you have `gorilla/mux` inside the `vendor.conf` but it seems that it's not being used at all in the library.

Probably there are some other dependencies that you are tracking in the vendor file that are not being used either.

**Comment by agonzalezro** [comment]
I looked for the ones that are not being imported anywhere and they seems to be a few:

```
$ for dep in $(cat vendor.conf|cut -d" " -f1|tail -n+3); do found=$(ack $dep|egrep -v "vendor|trash.lock"); if [ -z "$found" ]; then echo $dep; fi; done
github.com/davecgh/go-spew
github.com/docker/go-units
github.com/gorilla/context
github.com/gorilla/mux
github.com/mattn/go-runewidth
github.com/mattn/go-shellwords
github.com/mistifyio/go-zfs
github.com/opencontainers/runc
github.com/pborman/uuid
github.com/pmezard/go-difflib
golang.org/x/sys
gopkg.in/yaml.v2
github.com/xeipuuv/gojsonreference
github.com/xeipuuv/gojsonpointer
github.com/tchap/go-patricia
github.com/gogo/protobuf
github.com/pquerna/ffjson
```

Maybe I did something wrong with that "script" but I manually checked some of them and I couldn't find references to them.

**Comment by rhatdan** [comment]
Why not remove those open a PR and see if the tests pass?

**Comment by agonzalezro** [comment]
@rhatdan here you go: #444. I didn't do it before because I thought there should be some reason to have them there and I just wanted to check.

**Comment by mtrmac** [comment]
> ```
> $ for dep in $(cat vendor.conf|cut -d" " -f1|tail -n+3); do found=$(ack $dep|egrep -v "vendor|trash.lock"); if [ -z "$found" ]; then echo $dep; fi; done
> ```
Excluding all of `vendor` means that all transitive dependencies are not considered. Many of the listed results seem to be that kind.
