### ISSUE TITLE
Update docker dependency

### ISSUE THREAD

**Issue by mgoltzsche** [containers/image#445]
Update dependency of github.com/docker/docker since it stops me from using a newer docker feature.

**Comment by rhatdan** [comment]
Which feature?

**Comment by mtrmac** [comment]
… and more to the point, update to what version? A tested PR would be nice.

**Comment by mgoltzsche** [comment]
To be precise: I want to use github.com/docker/docker/dockerfile/shell which is separately available since [a634526d14639c6b98c509a069ef29e2b69c0ef0](https://github.com/moby/moby/commit/a634526d14639c6b98c509a069ef29e2b69c0ef0). In the version used here this Dockerfile variable parser code is still contained in the parent dockerfile package with a lot of other docker-specific dependencies which I would like to avoid to include into my [project](https://github.com/mgoltzsche/cntnr) (experimental rootless container tool).
Maybe tomorrow I will try to create a pull request.

**Comment by mgoltzsche** [comment]
Tested PRs to be applied in the following order:
1) Merge #446 - vendor.conf update; small code adjustment due to changed dependency; using projectatomic/skopeo#498 to pass integration test
2) Merge projectatomic/skopeo#498 - vendor dir update
3) Merge #452 - use skopeo master for integration test again

**Comment by mgoltzsche** [comment]
Adjusted steps to be done according to the [process](https://github.com/projectatomic/skopeo#dependencies-management):
1) Merge #446 - vendor.conf update + small code adjustment due to changed dependency
2) Change containers/image reference in projectatomic/skopeo#498 to make it mergeable
3) Merge projectatomic/skopeo#498 - vendor dir update
