### ISSUE TITLE
docker-archive: multiple tag support

### ISSUE THREAD

**Issue by cyphar** [containers/image#447]
At the moment if you want to operate on a `docker-archive:` it will only create a single `RepoTags` entry. However, Docker image tarballs are quite different to other images in that when you import them into `docker` you have no way of changing their name -- so if you wanted to import a single image under multiple names you would have to `skopeo copy` the image to different archives. However the format of `docker load` supports more than one entry in `RepoTags`.

The idea would be to add the ability to have "alternative names" in `SystemContext` (or something similar) for the `ImageDestination`. This would result in having multiple tags created referencing the image we've decided as our destination. Then we could plumb through an option like `--dst-additional-tags` to `skopeo`. Ultimately this could be added to all transports, though I'm not sure whether it would work very well with all of them.

WDYT?

/cc @vrothberg

**Comment by mtrmac** [comment]
Sure.  The feature makes sense; exposing it through `SystemContext` seems to be the best of the various ugly options.

Maybe make the `SystemContext` field / `skopeo` option explicitly `docker-archive:`-specific, at least until we have more enough other transports to understand the common/different aspects.  (E.g. `oci-archive:` might in principle benefit from something similar, but uses a different reference syntax.)

**Comment by mtrmac** [comment]
Looking at https://github.com/projectatomic/libpod/issues/649 , do you need to handle _only_ the case of multiple tags for a single image, or do you expect to need support for true multi-image archives? The latter would make adding special-case `SystemContext` facilities somewhat less attractive (though still acceptable to me).

Cc: @runcom

**Comment by vrothberg** [comment]
Just to clarify: this issue and projectatomic/libpod#649 are only indirectly related. The current issue mostly relates to `skopeo-copy` dealing with multiple tags. In this context, we checked how podman deals with it and found the issues mentioned in  projectatomic/libpod#649.

> [...] do you need to handle only the case of multiple tags for a single image, or do you expect to need support for true multi-image archives?

We only need multiple tags for a single image.

**Comment by vrothberg** [comment]
Here's a PR implementing it: https://github.com/containers/image/pull/450

I used this commit in `skopeo copy` to add additional tags via a `--additional-tag` flag, and it works as expected (i.e., the `manifest.json` in the archive includes the additional tags).
