### ISSUE TITLE
http/https detection for Docker clients must be configurable, should be opt-in

### ISSUE THREAD

**Issue by mtrmac** [containers/image#45]
… otherwise a MITM can prevent use of TLS by blocking connections, and then on unauthenticated HTTP they can send a custom `WWW-Authenticate: Bearer realm=$attacked-controlled-URL`"` header which will cause the user name and password to be sent to the attacker-controlled location.

**Comment by mtrmac** [comment]
… and given that infrastructure, `getBearerToken` should probably insist on HTTPS (per RFC 6749 3.2), even if `realm` uses a `http://` URL, unless the registry is allowed to be insecure.

**Comment by runcom** [comment]
Great point, not sure upstream does this already, might be good to propose this also if it's something they need to look into

**Comment by mtrmac** [comment]
At least the first part does happen (`--insecure-registry`). The second part AFAICS does not, but then it is unnecessary assuming a well-intentioned and well-managed registry.
