### ISSUE TITLE
Support uncompressed image in docker registries

### ISSUE THREAD

**Issue by jethrogb** [containers/image#469]
Docker registries ostensibly support uncompressed layers: https://github.com/docker/distribution/blob/7dba427612198a11b161a27f9d40bb2dca1ccd20/manifest/schema2/manifest.go#L33

It would be nice if this were supported by this library.

**Comment by rhatdan** [comment]
Since no response ever came, I am going to close this issue. @jethrogb Reopen it if you are still interested and want to respond to @mtrmac

**Comment by jethrogb** [comment]
I think I meant "able to create", but I fixed my usecase with https://github.com/containers/skopeo/issues/517 instead.
