### ISSUE TITLE
image copy from oci source to different docker daemons does not behave as it should be.

### ISSUE THREAD

**Issue by praveenkumar** [containers/image#477]
Is below expected?

```
# docker daemon running on the 192.168.42.191
<192.168.42.191> $ docker pull openshift/origin:latest

<localhost> $ skopeo copy --src-cert-dir /home/prkumar/.minishift/certs --src-daemon-host tcp://192.168.42.191:2376  docker-daemon:openshift/origin:latest oci:openshift:origin:latest
Getting image source signatures
Copying blob sha256:bcc97fbfc9e1a709f0eb78c1da59caeb65f43dc32cd5deeb12b8c1784e5b8237
 198.59 MB / 198.59 MB [===================================================] 13s
Copying blob sha256:378e1794c586063ac71fb5c06a27ef01580b809b2ec09c452a22847238acfef6
 3.00 KB / 3.00 KB [========================================================] 0s
Copying blob sha256:ec49d1733bdc33db541af81b9d3029cafade8944035c31cfaccf5a8605b5b54e
 27.96 MB / 27.96 MB [======================================================] 1s
Copying blob sha256:c9b477485f0eb147d5bd64e431d123dcbfb37a62bb83f9e474bfb45e25a64d7d
 134.01 MB / 134.01 MB [====================================================] 7s
Copying blob sha256:e9d7c9d316e8ddf77b9b96b6913b934b9878044ec8f2445f0a5438a46681a8e8
 291.07 MB / 291.07 MB [===================================================] 13s
Copying config sha256:14ff09e2ba8634c49fc8c980d9c839928597a4f0cd36f9dc6df8c242426bb401
 1.99 KB / 1.99 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures

<192.168.42.191> $ docker rmi docker.io/openshift/origin
Untagged: docker.io/openshift/origin:latest
Untagged: docker.io/openshift/origin@sha256:f99c544eff0c28d12593ebafd4cbf039a83b95cf2aa89d40c236caffbaf0c250
Deleted: sha256:c45099c2bcfa0359552ed3e207ef098373f87b211676e4b7c171f2cf2c70b16a
Deleted: sha256:c2345b6629e5a8f5290f460564e75dfc4b5f9e01eb27853e0886812a2f9177d4
Deleted: sha256:f2a46868f51cb33a81827a1bad593e0751727aad2afa2d0705e6b0af5777a327
Deleted: sha256:4b315418b7fb24798059d333e635e8f16c838e832acc938d53cdb41a660e29fd
Deleted: sha256:1c29031fe2c206171a5697c5f6f18fb99fd53e73e560f5d604fbcb43e5b3ea45
Deleted: sha256:bcc97fbfc9e1a709f0eb78c1da59caeb65f43dc32cd5deeb12b8c1784e5b8237

<localhost> $ $ skopeo copy --dest-cert-dir /home/prkumar/.minishift/certs --dest-daemon-host tcp://192.168.42.191:2376 oci:openshift:origin:latest docker-daemon:openshift/origin:latest
Getting image source signatures
Copying blob sha256:7dc0dca2b1516961d6b3200564049db0a6e0410b370bb2189e2efae0d368616f
 71.23 MB / 71.23 MB [======================================================] 0s
Copying blob sha256:89297ec2ab9b84686a2e00dbae3dc33f4227f811dada592c899b4b39327ed508
 262 B / 262 B [============================================================] 0s
Copying blob sha256:b0ad566301c1a76292246b3fbe81d6ae317ea0164123a5ffab8d0371b46450d2
 8.79 MB / 8.79 MB [========================================================] 0s
Copying blob sha256:34795a676aa3c60fde1d73c5f6d4f6879927ab222c0188b3c82924891032e871
 31.89 MB / 31.89 MB [======================================================] 0s
Copying blob sha256:dc2ca306d9f081c325a87333d8db5b73114da86b0e39b75d98d2e9b9f43b0a41
 55.11 MB / 55.11 MB [======================================================] 0s
Copying config sha256:14ff09e2ba8634c49fc8c980d9c839928597a4f0cd36f9dc6df8c242426bb401
 1.99 KB / 1.99 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures

<192.168.42.191> $ docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin   latest              14ff09e2ba86        3 weeks ago         674 MB

<192.168.42.191> $ docker pull docker.io/openshift/origin
Using default tag: latest
Trying to pull repository docker.io/openshift/origin ... 
latest: Pulling from docker.io/openshift/origin
7dc0dca2b151: Already exists   ===================> As expected since this layer made exist by skopeo copy (my understanding)
89297ec2ab9b: Already exists  
b0ad566301c1: Already exists 
34795a676aa3: Already exists 
dc2ca306d9f0: Already exists 
Digest: sha256:f99c544eff0c28d12593ebafd4cbf039a83b95cf2aa89d40c236caffbaf0c250
```

Now lets use a different docker-daemon <192.168.42.184>

```
<localhost> $ skopeo copy --dest-cert-dir /home/prkumar/.minishift/certs --dest-daemon-host tcp://192.168.42.184:2376 oci:openshift:origin:latest docker-daemon:openshift/origin:latest
Getting image source signatures
Copying blob sha256:7dc0dca2b1516961d6b3200564049db0a6e0410b370bb2189e2efae0d368616f
 71.23 MB / 71.23 MB [======================================================] 0s
Copying blob sha256:89297ec2ab9b84686a2e00dbae3dc33f4227f811dada592c899b4b39327ed508
 262 B / 262 B [============================================================] 0s
Copying blob sha256:b0ad566301c1a76292246b3fbe81d6ae317ea0164123a5ffab8d0371b46450d2
 8.79 MB / 8.79 MB [========================================================] 0s
Copying blob sha256:34795a676aa3c60fde1d73c5f6d4f6879927ab222c0188b3c82924891032e871
 31.89 MB / 31.89 MB [======================================================] 0s
Copying blob sha256:dc2ca306d9f081c325a87333d8db5b73114da86b0e39b75d98d2e9b9f43b0a41
 55.11 MB / 55.11 MB [======================================================] 0s
Copying config sha256:14ff09e2ba8634c49fc8c980d9c839928597a4f0cd36f9dc6df8c242426bb401
 1.99 KB / 1.99 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures

<192.168.42.184> $ docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin   latest              14ff09e2ba86        3 weeks ago         674 MB

<192.168.42.184>  $ docker pull docker.io/openshift/origin
Using default tag: latest
Trying to pull repository docker.io/openshift/origin ... 
latest: Pulling from docker.io/openshift/origin
7dc0dca2b151: Pull complete          =======> why this time it not able to detect existing layer and again pulling everything from internet :(
89297ec2ab9b: Pull complete 
b0ad566301c1: Pull complete 
34795a676aa3: Pull complete 
dc2ca306d9f0: Pull complete 
Digest: sha256:f99c544eff0c28d12593ebafd4cbf039a83b95cf2aa89d40c236caffbaf0c250
Status: Downloaded newer image for docker.io/openshift/origin:latest
```

**Comment by LalatenduMohanty** [comment]
Basically it seems docker is not able to recognize the  layers when skopeo copies the container image to different docker daemon.  This seems like a bug to me and we are seeing the issue https://github.com/minishift/minishift/issues/2583. We caught the issue because users delete the Minishift VM and recreate it when required.

**Comment by mtrmac** [comment]
Thanks for your report.

It is definitely unexpected that behavior differs _based on an IP address_. the code makes no choices based on an IP address as such. There must be some other cause.

Are the two hosts using exactly the same docker daemon version?

**Comment by praveenkumar** [comment]
> Are the two hosts using exactly the same docker daemon version?

@mtrmac  Yes, both the remote hosts using the same docker daemon which we ship as part of CentOS repo.

```
$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by mtrmac** [comment]
OK, this is basically the mirror of #475: the daemon image store internally identifies layers by their uncompressed digest (`DiffID`), but the compressed tarballs (used both by `oci:` and the `docker/distribution` registry protocol) must first be decompressed to determine that value. That’s basically the same “cache” discussed in #475, except that the Docker daemon actually implements it.

So, the crucial difference is the _first_ `docker pull`; at that time the daemon downloads the compressed data, decompresses it, and records the compressed/decompressed equivalence it the cache; this is not removed even after removing the image.

So, on the original host, `skopeo copy … docker-daemon:` makes the layer available again, and later `docker pull` looks up the compressed digest in the manifest in its cache, and realizes that the layer already exists and it does not need to be pulled again.

On _new_ hosts, `docker pull` does not have the cache entry, and needs to download and decompress the layer. At that point it will notice that the layer already exists, and reuses it — but the transfer and decompression must have happened.

AFAICT the same thing happens with plain `docker save` / `docker load` on Linux — but the code actually supports carrying the data on Windows, and the file format supports it universally. So, this should be solvable (by filling `LayerSources` in `docker.tarfile.Destination.PutManifest`).

**Comment by mtrmac** [comment]
> AFAICT the same thing happens with plain docker save / docker load on Linux — but the code actually supports carrying the data on Windows, and the file format supports it universally. So, this should be solvable (by filling LayerSources in docker.tarfile.Destination.PutManifest).

I was mistaken about this; the _file format_ can record the data, but the code interpreting the data is really only enabled on Windows. Worse, Docker before 1.12, when not running on Windows, rejects any tarballs with `LayerSources` filled in; so, adding that data helps nothing and decreases compatibility. (FWIW, an implementation is in https://github.com/mtrmac/image/tree/tarfile-LayerSources , but I’m not sure it is worth maintaining if it makes things worse.)

So, I don’t think this can be fixed against the current _unmodified_ versions of docker (both 1.13 you are using, and the current upstream version). And that, in turn, may make the performance issues discussed in #475 harder to work around.

[`containers-storage:` seems to record compressed digests in its metadata, so this should work well there. But I haven’t tested that now, and of course it does not immediately solve the issue you are facing.]

The last possible option I can see is to add the support for `LayerSources` to Docker, both upstream and in 1.13; @runcom may know more about that, both whether it is technically feasible and about any possible related discussions (if I understand it correctly, the Windows-only nature of `layer.DescribableStore` is a part of the “foreign layers support on Linux” feature request).

**Comment by LalatenduMohanty** [comment]
> So, I don’t think this can be fixed against the current unmodified versions of docker (both 1.13 you are using, and the current upstream version). And that, in turn, may make the performance issues discussed in #475 harder to work around.

We are using docker available in CentOS, is that unmodified version of docker?  It should not as it is same as docker in RHEL7.

**Comment by mtrmac** [comment]
> We are using docker available in CentOS 7, is that unmodified version of docker?

CentOS works the same way currently; I meant “unmodified compared to status quo”, sorry about that.

**Comment by praveenkumar** [comment]
@runcom ping, any comment for https://github.com/containers/image/issues/477#issuecomment-404277704 ?

**Comment by rhatdan** [comment]
@praveenkumar @runcom  @mtrmac @vrothberg What is the state of this issue?

**Comment by mtrmac** [comment]
It seems to me that the priority of enhancing the Docker daemon to support `LayerSources` in `docker load` input, and of adding features to `docker-daemon:` in general, is pretty low and decreasing, but I’ll let @praveenkumar comment before closing this.

**Comment by mtrmac** [comment]
There seems to be no interest in enhancing Docker to support this, and maintaining https://github.com/mtrmac/image/tree/tarfile-LayerSources would now require extra effort to make it not conflict with existing tests that create invalid data.

Closing, I don’t plan to work on this for the foreseeable future.
