### ISSUE TITLE
Clearer licensing statement

### ISSUE THREAD

**Issue by Silvanoc** [containers/image#479]
The licensing statement at the end of the [README.md](https://github.com/containers/image#license) is confusing, because it's unclear which license is meant with 'ASL 2.0'. Looking at the [LICENSE file](https://github.com/containers/image/blob/master/LICENSE) I concluded that it's a not so wide spread acronym for Apache Software License (or something similar).

I'd rather explicitly state the license full name ("Apache License 2.0") and it would be also helpful to provide the [SPDX short identifier](https://spdx.org/licenses/Apache-2.0.html)("Apacher-2.0").

**Comment by rhatdan** [comment]
Please open a PR to change it

**Comment by Silvanoc** [comment]
I will, but it might take a while. I first have to request a contribution permission on my company :unamused:

**Comment by rhatdan** [comment]
SGTM
