### ISSUE TITLE
docs: prefix with "containers-"

### ISSUE THREAD

**Issue by vrothberg** [containers/image#492]
I started working on improving the CRI-O docs (see kubernetes-incubator/cri-o#1747) and noticed an inconsistency regarding the naming of manpages among the `containers/*` libraries. `containers/storage` prefixes all manpages with `containers-` while `containers/image` doesn't.

I see two main reasons for using the `containers-` prefix also for `containers/image`:
 - Consistency :)
 - `registries.conf(5)` is reserving a rather generic name, whereas `containers-registries.conf(5)` is more explicit and is more aligned with the default path of the config in `/etc/containers/`.

**Comment by vrothberg** [comment]
@rhatdan I think that conflicts are likely without the prefix (also for `policy.json(5)`, for instance). I can take over propagating the renames if we decide to do it.

**Comment by rhatdan** [comment]
Yes please start doing this. Would also like to make sure this content shows up if the user executes

man -k container

**Comment by mtrmac** [comment]
> The goal is for users to easily find the man page.

With the proliferation of `git-*(1)` and `systemd.*(5)` man pages and so on, I feel that we have lost the predictability of the manual naming a long time ago (and of course no-one prints it all and reads it from start to finish any more).

I also quite agree that nobody is going to just _guess_ `policy.json(5)` or `registries.conf(5)`; at best it can be found in `/etc/containers` by a curious student, but most will probably start with high-level product documentation.

Overall, `apropos`/`man -k` is probably the best we have, and renaming does not hurt this at all – actually it would automatically make the content visible in `man -k container`; it is not visible in there now.
