### ISSUE TITLE
Add a random image transport

### ISSUE THREAD

**Issue by yolo3301** [containers/image#507]
The transport should generate a random image with the given # of layers and # of bytes of each layer. It should only support produce an ImageSource but not ImageDestination. This will come handy for testing scenarios - e.g. testing if a registry supports certain manifest schema

I could contribute to such a feature if it makes sense at all.

**Comment by rhatdan** [comment]
SGTM
@mtrmac WDYT?

**Comment by mtrmac** [comment]
It seems to me that a problem with “random image for testing” is that each test only wants to test something _specific_, and usually fairly isolated; i.e. the image is “entirely random except for this aspect which must not be random at all” (in your example, “it must have a valid manifest in a specified schema”) — and it’s not at all obvious to me that it is possible to create a random image generator that is universal enough to allow all the various specific non-random aspects, without making it unusably complex.

Maybe it is easy to make the generator ”random but universally specific”, or maybe I am thinking about this in an entirely wrong way and missing an obvious solution. If so, do point that out, please.

Absent that, and without the random image transport being general enough to support many different testing scenarios, we would be talking about adding a transport to a library shared between projects only for the purpose of enabling a single test in a single project, which does not look like a great fit to me.

Possible alternatives
------------
Of course, you still need to write your tests.  There are two ways to integrate an “external” image generator with c/image:

- Generate the image as necessary (perhaps using the data structures in `c/image/manifest` and `c/image/image`, perhaps not), and write it into a directory consumable by the `dir:` transport. This can be used both with the c/image library directly and with the `skopeo` CLI tool (i.e. the generator does not need to be written in Go).

- Implement the specific generator you need as a c/image `types.ImageSource` + `types.ImageReference`, but keep it as a part of the test code, not in c/image.  The c/image APIs, notably `c/image/copy.Image`, only need a `types.ImageReference`; the image does not need to be registered in `c/image/transports/alltransports`, and even not in `c/image/transports` (apart from parsing `c/image/signature.Policy` objects from JSON).

  E.g. `buildah` is already creating such an `types.ImageSource` to represent ”the newly created image with a specified set of layers and buildah-CLI-specified container config”, which is a concept that does not make much sense outside of a `buildah` process, and to use `c/image` for pushing the buildah-specific image to arbitrary destinations.

  One downside to this is that the `types.ImageSource` API keeps changing (and is likely to keep changing for some time still), so maintaining the transport in your tests repo would require managing the version/API drift somehow.  You are referring to ”testing if a _registry supports_…”, so maybe it would be practical enough to just vendor a specific version of c/image and be insulated from this.

Overall, if this is a _single-purpose_ non-extensible generator, it seems to me that maintaining it in the tests repo, as described above, would be a better fit. If you are proposing a general-purpose generator, I’m a bit skeptical but curious and interested :)

**Comment by yolo3301** [comment]
Thanks for the feedback!

My idea is simple. The random image source will always generate a valid v2s2 image. Since the "copy" enables converting v2s2 to other schemas, it pretty much means we can get a random image for all schemas. Forgive me I lack the knowledge of any "specific" test requirements other than the schema.

Also the "test" here, I meant more like conformance tests. E.g. to see if a registry supports what schemas, or like in health probes, to check if certain registry API is not broken. If to think about generating all kinds of invalid images, for sure there will be too many cases and thus impossible to cover all. 

For alternatives, I thought about them before. They should all work. I just thought it would be nice contribute this to upstream.

**Comment by yolo3301** [comment]
@mtrmac

**Comment by rhatdan** [comment]
@yolo3301  @mtrmac @vrothberg What is the state of this issue?

**Comment by mtrmac** [comment]
> It seems to me that a problem with “random image for testing” is that each test only wants to test something specific, and usually fairly isolated; i.e. the image is “entirely random except for this aspect which must not be random at all” (in your example, “it must have a valid manifest in a specified schema”

I don’t think it’s at all easy to make a _universal_ ”random image generator”, and limited random image generators (like the ones suggested here, “given # of layers and # of bytes of each layer.”, “always generate a valid v2s2 image”) are, I think, better located directly in the tests which need those particular images.

We do provide, e.g. `c/image/manifest.Schema2FromComponents`, which makes it fairly easy to generate a manifest with arbitrary properties; an `ImageSource` returning data in memory can be implemented in less than a hundred lines (looking at `dirImageSource`).
