### ISSUE TITLE
when trying to pull from an untrusted registry, an incorrect error is reported

### ISSUE THREAD

**Issue by bparees** [containers/image#509]
my registry is insecure but i didn't have it listed as an allowed insecure registry in my config.  This appears to lead to a confusing error while pulling the image:

```
time="2018-09-28T16:03:31Z" level=debug msg="GET https://172.30.162.90:5000/v1/_ping"
time="2018-09-28T16:03:31Z" level=debug msg="Ping https://172.30.162.90:5000/v1/_ping err &url.Error{Op:\"Get\", URL:\"https://172.30.162.90:5000/v1/_ping\", Err:(*errors.errorString)(0xc420250070)}"
F0928 16:03:31.373156 1 helpers.go:119] error: build error: invalid reference format
```

@nalind

**Comment by bparees** [comment]
(note also that the error string isn't being printed correctly because it's a pointer)

**Comment by nalind** [comment]
Well the string part should be #508.  The "build error:" message isn't in the image library, so the rest of the error reporting issue is probably in buildah or the code that's calling into it.

**Comment by rhatdan** [comment]
@nalind @mtrmac @bparees @vrothberg Since this referenced PR is merged, can I close this issue?

**Comment by vrothberg** [comment]
Tested the latest state:
`pinging docker registry returned: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client`

So we can close it.
