### ISSUE TITLE
Add debug logs to show where docker/distribution credentials came from

### ISSUE THREAD

**Issue by mtrmac** [containers/image#510]
- Were they provided in `types.SystemContext`?
- Were they read from a config file? If so, from which one?
- Are we using no credentials at all?

**Comment by rhatdan** [comment]
@mtrmac @vrothberg What is the state of this issue?  Do you want me to get someone else to work on it?

**Comment by vrothberg** [comment]
The issue is still valid and I absolutely agree that such logs are needed.

Marked as `Good first issue` which may be something for interns or new contributors :)
