### ISSUE TITLE
Uncaught error while opening "authfile"

### ISSUE THREAD

**Issue by cjeanner** [containers/image#514]
Dear Containers Dev Team,

There appear t be an uncatched exception when we run "skopeo inspect" as a non-root user from within a container having a bind-mount for "/run:/run":
```
podman exec  1d01350439f7 skopeo --debug inspect docker://docker.io/tripleomaster/centos-binary-cron:965941f1e62cef16967e7a7cd6d98263e52acb62_0989b280
time="2018-10-10T14:21:17Z" level=fatal msg="error getting username and password: error reading JSON file "/run/containers/42430/auth.json": error unmarshaling JSON at "/run/containers/42430/auth.json": unexpected end of JSON input" 
exit status 1
```

After some more checks and tests, it seems the following function is the culprit:
https://github.com/containers/image/blob/7a1eac5d1df2dbd73d8b71853ebce32d989fcae3/pkg/docker/config/config.go#L164-L185

It tests "only" for a non-existing file, while in the described case it's a permission denied, producing an invalid JSON, and crashing the whole run.

Adding a test of something like "os.PermissionDenied" (don't know how it's called in Go) would be great, maybe throwing a warning if you see it suited, but at least it should go through and try to inspect the image (or do whatever we want), and crash in case authentication is needed.

Thank you for your support!

Cheers,

C.

Version:
- podman version 0.9.4-dev
- skopeo version 0.1.31-dev commit: be4ba88d78b026e2b2b3c155f65656b16104240e

**Comment by mtrmac** [comment]
Thanks for your report.

This error handling bug was just independently noted and fixed in #515 ; it will now report “permission denied”.

As for completely ignoring the “permission denied” error in that case, that’s not obviously correct and more conversation around the design is likely to happen.  You do bring up a good point about images that don’t need any authentication, and contexts where `podman login` may never be necessary.

In the meantime, the cleanest workaround is to ensure `XDG_RUNTIME_DIR` is set appropriately to a writable directory for the user (which is usually done by `pam_systemd`; `su` or `sudo` breaks it).

**Comment by cjeanner** [comment]
Hello @mtrmac,

Thank you for your answer! So in my case, as skopeo is launched from within a container, all I have to do is to add a ```-e XDG_RUNTIME_DIR=/tmp/``` for example. It seems to work as expected with that new environment variable.

It might be sufficient, but it should be documented somewhere, although the use-case is probably specific.

Thanks again for your feedback!

**Comment by mtrmac** [comment]
Thanks for the confirmation that this works; I don’t quite think that this is a satisfactory long-term solution, so let’s wait a bit whether that settles on a better one before documenting this workaround.

**Comment by cjeanner** [comment]
Maybe allowing the "Permission Denied" to be ignored as an option? But that will diverge from docker options I guess? Not really familiar with that.

And if doc is to be created, /tmp/ should not be mentioned as it might create some security issue, of course ;). In my test, it was a quick'n'dirty thing.

**Comment by rhatdan** [comment]
@cjeanner @mtrmac @vrothberg What is the state of this issue?

**Comment by vrothberg** [comment]
https://github.com/containers/image/pull/515 seemed to have fixed that, closing.
