### ISSUE TITLE
Need a way to learn the digest of (the manifest of) a copy of an image

### ISSUE THREAD

**Issue by nalind** [containers/image#518]
When we copy an image from one place to another, in cases where a format conversion is performed, we don't have a way to learn the digest of the written image's manifest.  OpenShift will want to know that value in order to be able to tell a runtime engine to use that exact version of the image.

While we can attempt to immediately use the destination reference to obtain an ImageSource, read the manifest from it, and compute its digest, if we do that we can't be really sure that there wasn't another image copied to the same reference in between.

I think we can work around this in buildah by wrapping reference and image destination types so that it can record the contents of manifests that are written to destinations, but it's probably simpler to extend copy.Image() to communicate that information to its caller somehow.

**Comment by nalind** [comment]
@bparees FYI

**Comment by mtrmac** [comment]
Makes sense; `copy.Image` could, I think, very reasonably just return the manifest digest as an extra return value. (Or maybe the raw manifest as a `[]byte`, to avoid the overhead of computing the manifest digest if the caller does not care.)

Right now we only copy a single image instance, so this is trivial. After true support for multi-arch images is added, it still seems reasonable to return the top-level manifest list, and the caller could then dig in to extract the per-arch manifests if necessary.

**Comment by rhatdan** [comment]
@nalind @mtrmac @vrothberg What is the state of this issue? Since the referenced PR was merged can we close it?

**Comment by vrothberg** [comment]
https://github.com/containers/image/pull/519 fixed that, closing.
