### ISSUE TITLE
Missing documentation for mirror support in containers-registries.conf

### ISSUE THREAD

**Issue by EmilienM** [containers/image#529]
@vrothberg introduced support for Mirrors in containers/image but there is no documentation:

https://github.com/containers/image/commit/633422b62042815f4288a1d85ad68bc58675b5fb
https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md

It is pretty difficult for users to understand what can be done, and how it can be configured.
Basically, I want to know if as a user I can ```podman pull``` containers from a mirror, same for buildah and skopeo.

**Comment by EmilienM** [comment]
ping @mtrmac

**Comment by rhatdan** [comment]
@mtrmac @vrothberg What is the state of this issue?

**Comment by vrothberg** [comment]
This is now documented but still subject to change. But we can close it.
