### ISSUE TITLE
New transport type: localdocker://

### ISSUE THREAD

**Issue by aweiteka** [containers/image#53]
Use case: I have built a local docker image. I need a way to reference this image to push it to a registry and sign it. We need to be able to reference local docker images to copy them to a registry and generate a manifest to sign without changing the name of the image.

*localdocker://* is just a suggestion. Don't care what we call it.

**Comment by aweiteka** [comment]
cc @baude

**Comment by aweiteka** [comment]
Better naming might be "docker-daemon:"

**Comment by philips** [comment]
Isn't it techinically the docker engine? Or even docker engine API?

**Comment by cyphar** [comment]
In addition, something that would be incredibly useful would be having `docker load`-style images be supported. Specifically it would really help with our plans for having KIWI support OCI image building (to then be able to convert the OCI images to Docker images without ever needing a Docker daemon running on our build system).

**Comment by aweiteka** [comment]
Resolved by #135 
If we want to discuss further we should probably open another issue as a separate change request.

**Comment by mtrmac** [comment]
> In addition, something that would be incredibly useful would be having docker load-style images be supported. Specifically it would really help with our plans for having KIWI support OCI image building (to then be able to convert the OCI images to Docker images without ever needing a Docker daemon running on our build system).

The conversions from/to that format (or at least the latest version) already exist in #135, so this would be a matter of factoring the conversion code out and adding a transport which simply uses files instead of docker/engine-api/client. But, yeah, a separate issue (and PRs welcome).

**Comment by mtrmac** [comment]
Sorry, I see you have already filed #140.
