### ISSUE TITLE
make localhost insecure by default

### ISSUE THREAD

**Issue by vrothberg** [containers/image#544]
Docker marks localhost as insecure by default. I assume that the reasoning behind that is to enable an easy and straight-forward way to develop and test against a local registry running on the same host. Note that there doesn't seem to be a restriction regarding ports.

I think containers/image should follow the example as I think that users expect this behaviour.

**Comment by vrothberg** [comment]
@runcom @rhatdan @giuseppe @TomSweeneyRedHat WDYT?

**Comment by mtrmac** [comment]
What is the _exact_ set of hosts this would apply to? Precisely `localhost`? Precisely `127.0.0.1`? Both? More?

At a first glance this makes sense because a CA-signed certificate (even if signed by a private CA) for `localhost` is a dubious idea.

**Comment by rhatdan** [comment]
Makes sense to me. localhost/image has no meaning to Docker, they default to docker.io/image
I think 127.0.0.1 would.
But this works for me.

**Comment by vrothberg** [comment]
What I would like to support is `localhost:$PORT` and `127.0.0.1`, which afaik aligns with what Docker does.

**Comment by vrothberg** [comment]
Closing. It can easily be configured in the registries.conf.
