### ISSUE TITLE
[RFC] Add GetManifestDigest that uses HTTP HEAD to check if manifest is cached

### ISSUE THREAD

**Issue by glestaris** [containers/image#55]
Hello,

In GrootFS [1], we are caching the blobs and image config when downloading remote (Docker) images. The only thing we can't cache at the moment is the manifest, since `ImageSource.GetManifest` is fetching the whole manifest regardless of whether or not is already cached.

The Docker registry v2 API supports `Docker-Content-Digest` header [2], which contains the manifest digest. We would like to extend the `ImageSource` interface by adding a `GetManifestDigest` method which uses HTTP HEAD to just fetch the digest and MIME type. That way we will be able to use our cache if we have the most recent manifest.

``` diff
diff --git a/types/types.go b/types/types.go
index b67e6b3..669f579 100644
--- a/types/types.go
+++ b/types/types.go
@@ -85,6 +85,9 @@ type ImageSource interface {
  // Reference returns the reference used to set up this source, _as specified by the user_
  // (not as the image itself, or its underlying storage, claims).  This can be used e.g. to determine which public keys are trusted for this image.
  Reference() ImageReference
+ // GetManifestDigest returns the image's manifest digest along with its MIME type. The empty string is returned if the MIME type is unknown. The slice parameter indicates the supported mime types the manifest should be when getting it.
+ // You may use this operation to check if you have the most recent manifest in cache. It may use a remote (= slow) service.
+ GetManifestDigest([]string) (string, string, error)
  // GetManifest returns the image's manifest along with its MIME type. The empty string is returned if the MIME type is unknown. The slice parameter indicates the supported mime types the manifest should be when getting it.
  // It may use a remote (= slow) service.
  GetManifest([]string) ([]byte, string, error)
--
```

We would like to PR this work, but before we would like to know WDYT?

Thanks,
@albertoleal and @glestaris

[1] https://github.com/cloudfoundry/grootfs
[2] https://github.com/docker/distribution/blob/master/docs/spec/api.md#digest-header

**Comment by runcom** [comment]
not sure, that header is there for security and content verification - not to hack on it for caching, shouldn't you take care of the whole index/cache system instead of having the library doing this? (I'm not sure how you would do this, just thinking out loud)
@mtrmac wdyt

**Comment by glestaris** [comment]
> not sure, that header is there for security and content verification - not to hack on it for caching

`docker/distribution` seems to use in in their tag service [1] to get the descriptor.

> shouldn't you take care of the whole index/cache system instead of having the library doing this?

That's an interesting question. In GrootFS we consume `containers/image` for the Docker registry interaction and implement the cache (storing the blobs in the filesystem) ourselves. We would be very happy to PR some of the caching behaviour (and thus share the maintenance cost) if you think it's worthy. But that would be more of a long term thing.

[1] https://github.com/docker/distribution/blob/master/registry/client/repository.go#L294

**Comment by mtrmac** [comment]
> that header is there for security and content verification - not to hack on it for caching

It is really for caching and discovering random corruption during transfers; nothing prevents the registry from lying in this header, or from returning the expected header value but a non-matching manifest.


I am more concerned about https://github.com/docker/docker/blob/master/distribution/pull_v2.go#L341 :
> // NOTE: not using TagService.Get, since it uses HEAD requests
> // against the manifests endpoint, which are not supported by
> // all registry versions.

though I suppose treating this as an optimization which might fail would work.


More importantly, have you actually measured, or do you have anything to suggest, that using HEAD to look up in the cache would be an improvement? My first-order intuition is that a roundtrip is a roundtrip is a roundtrip, at least with the manifest sizes between a few hundred and a few thousand bytes, so I would expect `HEAD` manifest to take about as much time as `GET` manifest; and `HEAD`+`GET` is definitely worse than just `GET`.

**Comment by glestaris** [comment]
> // NOTE: not using TagService.Get, since it uses HEAD requests
// against the manifests endpoint, which are not supported by
// all registry versions.

Interesting.

> More importantly, have you actually measured, or do you have anything to suggest, that using HEAD to look up in the cache would be an improvement? My first-order intuition is that a roundtrip is a roundtrip is a roundtrip, at least with the manifest sizes between a few hundred and a few thousand bytes, so I would expect HEAD manifest to take about as much time as GET manifest; and HEAD+GET is definitely worse than just GET.

Correct, we do not expect a huge improvement there. We will probably try and investigate how much this would give us before making a PR...

**Comment by runcom** [comment]
> It is really for caching and discovering random corruption during transfers; nothing prevents the registry from lying in this header, or from returning the expected header value but a non-matching manifest.

but it isn't documented as such https://github.com/docker/distribution/blob/master/docs/spec/api.md#digest-header - I'm not sure either though

**Comment by mtrmac** [comment]
> > It is really for caching and discovering random corruption during transfers; nothing prevents the registry from lying in this header, or from returning the expected header value but a non-matching manifest.

> but it isn't documented as such https://github.com/docker/distribution/blob/master/docs/spec/api.md#digest-header - I'm not sure either though

That says
> IMPORTANT: If a digest is used to fetch content, the client should use the same digest used to fetch the content to verify it. The header Docker-Content-Digest should not be trusted over the "local" digest.

**Comment by rhatdan** [comment]
@glestaris @mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
After (almost) three years, we can close it.
