### ISSUE TITLE
Allow parallel copying from docker-archives

### ISSUE THREAD

**Issue by teozkr** [containers/image#567]
Is there any reason that `HasThreadSafeGetBlob` for `docker/tarball` is marked `false`?

From what I can tell, all IO in `GetBlob` seems to go through `openTarComponent` which opens a new file descriptor for each call, which should be thread-safe. `ensureCachedDataIsPresent` mutates state, but should be idempotent from what I can tell.

/cc @vrothberg

**Comment by mtrmac** [comment]
(For other readers,) see 
https://github.com/containers/image/pull/568#issuecomment-458173387 .
