### ISSUE TITLE
Incorrect/inconsistent docker/config.json path lookup

### ISSUE THREAD

**Issue by mtrmac** [containers/image#596]
- If the user specifies `SystemContext.AuthFilePath`, we should not be checking the home directory
- <s>It’s surprising that `GetAuthentication` and `GetUserLoggedIn` use different sets of paths.</s>

**Comment by rhatdan** [comment]
Since the PR Is merged, I am closing this issue.

**Comment by mtrmac** [comment]
The home directory aspect is still outstanding.
