### ISSUE TITLE
Go binary path being assumed to be part of PATH

### ISSUE THREAD

**Issue by Silvanoc** [containers/image#620]
The [`vendor` target of the `Makefile`](https://github.com/containers/image/blob/54d6f626f672b295efc65f9336ce200d207dc264/Makefile#L54) is assuming that the directory where the Go binaries get installed (`GOBIN` or `GOPATH/bin`) is part of the `PATH`.

But at least that target doesn't work if that's not the case, like in one of my build environments.

**Comment by vrothberg** [comment]
This will be fixed once we migrate to using go modules which I expect to happen in the near future.

**Comment by Silvanoc** [comment]
> This will be fixed once we migrate to using go modules which I expect to happen in the near future.

I've nevertheless fixed it on my side and sent a PR with the fix, just in case you are interested until it's so far.
