### ISSUE TITLE
Custom defaultDomain to support pushing to custom default repositories

### ISSUE THREAD

**Issue by orthoxerox** [containers/image#642]
Right now the default domain is hardcoded in /docker/reference/normalize.go, so pulling and pushing work differently if your /etc/containers/registries.conf has been customized:
- `podman pull foo` tries to pull `foo` from the repositories configured in /etc/containers/registries.conf
- `podman push foo` tries to push `foo` to `docker.io/library/foo:latest`

A way to configure a different default push repository in /etc/containers/registries.conf would allow both pulling and pushing to transparently work with custom repositories.

**Comment by mtrmac** [comment]
Thanks for your report, but no, this is not going to happen at the c/image level, and definitely not in docker/reference.    The whole idea of short names defaulting to a registry has, in retrospect, been a mistake, and having names change their semantics depending on an option would be much less manageable, and basically nothing in the call stack is ready for such a change to the semantics.  (See all the difficulties and struggles with supporting the search list for unqualified images, e.g. OpenShift notionally can use that but in practice it ended up not working at all.)

This is definitely not going to happen in c/image/docker/reference, nor in the `docker://…` generic syntax.

Higher-level callers like podman, can, of course, implement their own syntax and their own ways for creating the `docker://` references (like they already do for the search functionality on pull), and _as long as that does not change the semantics of the `docker://` format_), that’s fine with me (and, like the search code, that might end up in a shared library, maybe even in c/image).

Personally, I don’t quite see the point of a default push registry; it is easy enough to set up shell aliases and helper scripts that make it easy and short-to-type to use your specific corporate registry, without affecting/breaking any third-party scripts or software, or without risking that the created software product requires a specific default push path and can’t be used together with some other product that requires a different default push path.

**Comment by mtrmac** [comment]
> having names change their semantics depending on an option would be much less manageable, and basically nothing in the call stack is ready for such a change to the semantics.

Also of note, signatures created by the c/image/signature format were initially using the short format for `docker.io[/library]` names. It could be disastrous if those signatures were accepted for some other  repository just because someone intended to set up that repository as a default push location.
