### ISSUE TITLE
Tag naming doesn't corespond to the OCI Image Format

### ISSUE THREAD

**Issue by denisok** [containers/image#649]
I was struggling to find the documentation about tag naming format.

I had an issue assigning such tag : "1.0.0+git1530.gad89e4f4'"

```
skopeo: stderr: time="2019-06-18T17:37:00Z" level=fatal msg="error parsing additional-tag 'rook/ceph:1.0.0+git1530.gad89e4f4': invalid reference format" 
```

The only documentation I found that is close to the tag names is [OCI Image Format Annotations]( https://github.com/opencontainers/image-spec/blob/master/annotations.md)

> org.opencontainers.image.ref.name Name of the reference for a target (string).
> 
>     SHOULD only be considered valid when on descriptors on index.json within image layout.
>     Character set of the value SHOULD conform to alphanum of A-Za-z0-9 and separator set of -._:@/+
>     The reference must match the following grammar:
> 
>     ref       ::= component ("/" component)*
>     component ::= alphanum (separator alphanum)*
>     alphanum  ::= [A-Za-z0-9]+
>     separator ::= [-._:@+] | "--"

Is that format should be used for the tags as well? Or should be "org.opencontainers.image.ref.name" changed to comply with actual code ?

Or they aren't related at all?

As I understand currently only doc that exists is the code:
https://github.com/containers/image/blob/270aea3b8bc8dd03dc3939e7ae5942fd99b17bc5/docker/reference/regexp.go#L37

Should label naming be documented in the OCI Image Format ?

**Comment by mtrmac** [comment]
Please provide a _complete_ reproducer for the situation.

It seems that you are trying to use the `skopeo copy --additional-tags` option, but that one only works for `docker-archive:` destinations, and the enforced syntax is correct for that format.

It has nothing to do with the OCI `image.ref.name` annotation, which has indeed much looser syntax than traditional docker/distribution references (and that is, in turn, still looser than tags usable in `docker-archive:`).

**Comment by denisok** [comment]
> Please provide a _complete_ reproducer for the situation.
> 

I don't have local reproducer. OBS was used to build container. It uses `skopeo copy` to copy container from local container to other location.

> It seems that you are trying to use the `skopeo copy --additional-tags` option, but that one only works for `docker-archive:` destinations, and the enforced syntax is correct for that format.

This doesn't look  `1.0.0+git1530.gad89e4f4` to match `[\w][\w.-]{0,127}`, at least no https://regex101.com/.

I just reverse analyzed skopeo code and at the end it calls:
https://github.com/containers/skopeo/blob/1715c9084124875cb71f006916396e3c7d03014e/cmd/skopeo/copy.go#L78
which I think fails on TagRegexp match and later on digest.

> 
> It has nothing to do with the OCI `image.ref.name` annotation, which has indeed much looser syntax than traditional docker/distribution references (and that is, in turn, still looser than tags usable in `docker-archive:`).

OK. Is there any docs for the format?

**Comment by mtrmac** [comment]
> > Please provide a _complete_ reproducer for the situation.
> 
> I don't have local reproducer.
…
> I just reverse analyzed skopeo code and at the end it calls:
(I can’t quite understand how you can trace down the relevant code without having a command to run; how do you know that the code you found is relevant to the situation? Anyway, you are right that `TagRegexp` is involved here, among other values.

> > It has nothing to do with the OCI `image.ref.name` annotation, which has indeed much looser syntax than traditional docker/distribution references (and that is, in turn, still looser than tags usable in `docker-archive:`).
> 
> OK. Is there any docs for the format?

For the tag name, basically consider `c/image/docker/reference/regexp.go` (or `GitHub.com/docker/distribution/reference/regexp.go`) to be _the_ documentation.

**Comment by denisok** [comment]
> > > Please provide a _complete_ reproducer for the situation.
> > 
> > 
> > I don't have local reproducer.
> > …
> > I just reverse analyzed skopeo code and at the end it calls:
> 
> (I can’t quite understand how you can trace down the relevant code without having a command to run; how do you know that the code you found is relevant to the situation? Anyway, you are right that `TagRegexp` is involved here, among other values.
> 

build server did run that command and I have output then just looking to the code.

> > > It has nothing to do with the OCI `image.ref.name` annotation, which has indeed much looser syntax than traditional docker/distribution references (and that is, in turn, still looser than tags usable in `docker-archive:`).
> > 
> > 
> > OK. Is there any docs for the format?
> 
> For the tag name, basically consider `c/image/docker/reference/regexp.go` (or `GitHub.com/docker/distribution/reference/regexp.go`) to be _the_ documentation.

OK, works for me. Thanks!
