### ISSUE TITLE
podman login not working with certificate authentication

### ISSUE THREAD

**Issue by linkvt** [containers/image#654]
Hi,

we have an Artifactory running behind a load balancer that uses certificate authentication.
When we try to `podman login` we get the error `Error: error authenticating creds for "domain": pinging docker registry returned: Get https://domain/v2/: remote error: tls: handshake failure`

When using `docker login` the login succeeds.
When using `podman login` it tries to reuse the existing login but also fails again:
```
$ sudo podman login domain --log-level debug
Authenticating with existing credentials...
DEBU[0000] Looking for TLS certificates and private keys in /etc/containers/certs.d/domain
DEBU[0000]  crt: /etc/containers/certs.d/domain/ca.crt
DEBU[0000]  cert: /etc/containers/certs.d/domain/client.cert
DEBU[0000]  key: /etc/containers/certs.d/domain/client.key
DEBU[0000] GET https://domain/v2/
DEBU[0000] Ping https://domain/v2/ status 401
DEBU[0000] GET https://domain/artifactory/api/docker/null/v2/token?account=userid&service=domain
Existing credentials are invalid, please enter valid username and password
Username (userid):
Password:
DEBU[0008] Looking for TLS certificates and private keys in /etc/containers/certs.d/domain
DEBU[0008]  crt: /etc/containers/certs.d/domain/ca.crt
DEBU[0008]  cert: /etc/containers/certs.d/domain/client.cert
DEBU[0008]  key: /etc/containers/certs.d/domain/client.key
DEBU[0008] GET https://domain/v2/
DEBU[0008] Ping https://domain/v2/ status 401
DEBU[0008] GET https://domain/artifactory/api/docker/null/v2/token?account=userid&service=domain
ERRO[0009] error authenticating creds for "domain": Get https://domain/artifactory/api/docker/null/v2/token?account=userid&service=domain: remote error: tls: handshake failure
```

I guess that the error is probably in this area as the certificates from the dockerClient are not used: https://github.com/containers/image/blob/5136fb6b50bde99319d73345947cf028bef9f3e9/docker/docker_client.go#L526-L530 
I will try to fix it in the next days but I'm not very familiar with the code base yet so if you see an easy fix we would appreciate that, otherwise I would also appreciate some guidance.

Thanks!

**Comment by rhatdan** [comment]
Is this a Podman issue or a containers/image issue?
@vrothberg @mtrmac PTAL

**Comment by linkvt** [comment]
@rhatdan If this comment was directed to me, I think this is an issue with containers/image - at least that's where I found the code snippet above that doesn't use the certificates in opposite to other locations like https://github.com/containers/image/blob/5136fb6b50bde99319d73345947cf028bef9f3e9/docker/docker_client.go#L278 where they use the `dockerClient` directly.

**Comment by mtrmac** [comment]
@linkvt Thanks for the report, this is a c/image issue. I’m working on a fix.

**Comment by linkvt** [comment]
@mtrmac I was really keen on fixing it myself so I took some time and as it turned out, the fix was quite trivial. I hope you're not already on it and that the PR is sufficient but I would really appreciate feedback if there are more changes needed. Thanks!
