### ISSUE TITLE
containers-transports man page ambiguous

### ISSUE THREAD

**Issue by thmo** [containers/image#666]
In the containers-transports man page, the syntax for the containers-storage is noted as:
```
containers-storage: [storage-specifier]{image-id|docker-reference[@image-id]}
```
However, there's two problems:
- an extra space after the first colon
- the `[` `]` around `storage-specifier` are *literals*, i.e. have to be given, and are not denoting an optional part of the syntax.

**Comment by TomSweeneyRedHat** [comment]
I'd assign this to myself, but it looks like I don't have the juice to do so.

**Comment by rhatdan** [comment]
I do...
Thanks @thmo for pointing this out.
