### ISSUE TITLE
docker: Pass Bearer Token directly

### ISSUE THREAD

**Issue by knqyf263** [containers/image#689]
Currently, this library gets the Bearer Token by using username/password .
https://github.com/containers/image/blob/5144ced37a1b21b63c6ef605e56811e29a687528/docker/docker_client.go#L428

Then, it sets the token to the Authorization header.
https://github.com/containers/image/blob/5144ced37a1b21b63c6ef605e56811e29a687528/docker/docker_client.go#L435

However, I would like to pass the Bearer Token generated elsewhere directly. This is because I am developing a Harbor plugin and this plugin receives Bearer Token directly. Any chances getting support this feature? 

If so, I'm going to implement it.

Thank you for the awesome library.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg WDYT?

**Comment by knqyf263** [comment]
@rhatdan @mtrmac @vrothberg How is it?

**Comment by lizrice** [comment]
Hi @rhatdan! If we (well, I really mean @knqyf263) came up with a proposal / PR for adding this support is that something you might accept?

**Comment by mtrmac** [comment]
@knqyf263 @lizrice Sorry for the delay.  Sure, if you want to add a `types.SystemContext.DockerBearerToken` or something like that for library use, that should work nicely.

(To be extra clear, this is different from the “IdentityToken” support being added in #829, isn’t it?)

**Comment by rhatdan** [comment]
Even better if you drop the "Docker" adjective.

**Comment by knqyf263** [comment]
Hi @rhatdan, I've opened PR to close this issue. Would you take a look? DockerBearerToken(=DockerRegistyToken) is used to authenticate to a registry. Actually, `containers/image` already uses DockerBearerToken internally in exchange for username/password. When developing a plugin for the container registry such as Harbor, we don't have username/password but DockerRegistryToken. This PR just makes it possible to pass DockerRegistryToken from outside.

To my understanding, `IdentityToken` is used to obtain DockerRegistryToken instead of username/password.

**Comment by yihuaf** [comment]
That's correct. IdentityToken is used as a refresh_token to obtain a bearer token in place of password in the oauth2 workflow. @knqyf263 intention is to pass in a bear token instead of getting one from the registry using username/password or identitytoken.
