### ISSUE TITLE
Decide on go-connections/tlsconfig version / alternatives

### ISSUE THREAD

**Issue by mtrmac** [containers/image#699]
<s>c/image currently vendors `github.com/docker/go-connections` 7beb39f0b969;</s> meanwhile podman is 4 commits ahead at v0.4.0, but that’s a pretty significant behavior difference that some users are actually hitting.

Do we want to update c/image (and other users) to v0.4.0 as well?
Or revert podman back, for more compatibility and less security?
Or update much more, to keep up with upstream?
Or do something else entirely?

**Comment by mtrmac** [comment]
Well, there is https://docs.fedoraproject.org/en-US/packaging-guidelines/CryptoPolicies/ ; if we are going to introduce knobs, that would be the knob to introduce.

But we need to figure out the right default _first_; if we add knobs, it will never be important enough to have the right default, but the default matters for most users.

**Comment by ewolinetz** [comment]
Another issue that we noticed playing around with this is the TLS version that the proxy supports. When tested with squid `3.5` it would only use up to `1.2` but when i bumped up the squid proxy to be squid `4.x` it would handshake with `1.3`

**Comment by therevoman** [comment]
Following this thread.   I'm working with some financial institutions, which are notorious for wanting both bleeding edge security and EOL security.

**Comment by mtrmac** [comment]
Hum, we have updated go-connections in https://github.com/containers/image/pull/874 . But the research / decisions are still basically outstanding, primarily to consider whether similar code in `docker/docker_client.go` needs updating.

**Comment by mtrmac** [comment]
Let’s consolidate this with #161.
