### ISSUE TITLE
MIME type updates vs. buildah inconsistencies

### ISSUE THREAD

**Issue by mtrmac** [containers/image#720]
Per @vrothberg:
> ```
> buildah from alpine; buildah commit $ctr; buildah push $image dir:foo; jq . foo/manifest.json. 
> ```
> 
> The blobs are gzipped but the mediaType's are wrong. Even when using latest image.

**Comment by vrothberg** [comment]
That was a false alarm from my side. I have used a wrong binary which did not contain the latest c/image. Thanks for opening the issue and apologies for the false alarm.
