### ISSUE TITLE
migrate to golangci-lint

### ISSUE THREAD

**Issue by vrothberg** [containers/image#730]
Most github.com/containers projects use https://github.com/golangci/golangci-lint which improved the quality of the code and the quality of the CI. Currently, c/image uses `golint`which is a smaller subset of what `golangci-lint` can do.

Steps for migration:
1. Run `golangci-lint run` and fix the reported issues - preferably in small and easy to digest/review commits.
2. Let `make lint` use golangci-lint.

**Comment by bege13mot** [comment]
Hi,
I would like to take a look at it.

**Comment by vrothberg** [comment]
Sounds great, thanks, @bege13mot!

Please make sure to make small commits. This makes reviewing the changes much easier but it also helps debugging as we can properly bisect to track down errors. Have fun!

**Comment by jvanz** [comment]
As the PR has been merged, can not close this issue?

**Comment by vrothberg** [comment]
The issue is not yet done completely. #731 didn't manage to enable golangci-lint in the CI and missed to fix some reports. I am working in https://github.com/containers/image/pull/760 to address the remaining bits.

**Comment by mtrmac** [comment]
@vrothberg #760 was merged, so this might be done now.
