### ISSUE TITLE
wrong mediatypes when blob is already present at destination

### ISSUE THREAD

**Issue by vrothberg** [containers/image#733]
When copying an image, the media type of a given blob can be wrong when the a blob with the same digest is already present at the destination. Ultimately, `TryReusingBlob` and semantics behind (including the caches) only care about digests but they do not take the media types into consideration.

I think we need to lift setting media types on a higher level and not embed that in each individual `BlobInfo`. Currently, the API doesn't allow for specifying the compression on the granularity of layers but only for the entire image. That's something we could (should?) make use of when updating the manifest.

**Comment by vrothberg** [comment]
@rhatdan @mrunalp FYI

**Comment by rhatdan** [comment]
SGTM

**Comment by mtrmac** [comment]
> When copying an image, the media type of a given blob can be wrong when the a blob with the same digest is already present at the destination. Ultimately, `TryReusingBlob` and semantics behind (including the caches) only care about digests but they do not take the media types into consideration.

Well, `TryReusingBlob` _does_ return a `types.BlobInfo` and could return a valid MIME type. The difficulty is in knowing the right media type, https://github.com/docker/distribution/blob/master/docs/spec/api.md#get-blob suggests that `Content-Type: application/octet-stream` is OK and the MIME type is only carried in manifests. So, I guess we would have to always pass in the expected MIME type into `TryReusingBlob`, _and_ modify the blob info cache to record MIME types.

> I think we need to lift setting media types on a higher level and not embed that in each individual `BlobInfo`. Currently, the API doesn't allow for specifying the compression on the granularity of layers but only for the entire image. That's something we could (should?) make use of when updating the manifest.

I can’t quite see how this relates to the issue, it seems to go exactly the opposite way. It could _easily_ be the case that a single image (created as a sequence of build+push steps) can contain differently-compressed individual layers, so moving this from `BlobInfo` to “a higher level” does not make sense to me … I probably don’t understand what “a higher level” means.

---

We _really need to_ move `ImageDestination` and a fair amount of the copy infrastructure out of the stable API (`containers/image/types/unstable.ImageDestination`? or an actual embedded Go module with v0 version?), or we are going to keep bumping the major version all the time.

**Comment by vrothberg** [comment]
> We _really need to_ move `ImageDestination` and a fair amount of the copy infrastructure out of the stable API (`containers/image/types/unstable.ImageDestination`? or an actual embedded Go module with v0 version?), or we are going to keep bumping the major version all the time.

That's a great topic for the meeting in Westford. @rhatdan @mtrmac , can we allocate some time to discuss this there? We've been chatting about similar topics during this year and it would be great to come up with a plan to resolve the stability issues.

**Comment by rhatdan** [comment]
SGTM, I am not sure who is setting the agenda for the f2f meetings. @baude FYI

**Comment by marshallford** [comment]
Any updates on this?

**Comment by Frederik-Baetens** [comment]
Using podman build with --no-cache seems to somewhat resolve this. (podman version 1.8.1)

I say somewhat, because without --no-cache i immediately get the following error when gke tries to create the container:

```
  Warning  Failed     9s                kubelet, gke-quivrqlustr-pool-4-15-9b560ec4-cbf7  Error: failed to create containerd container: error unpacking image: failed to extract layer sha256:e370c53ec2429b596f60e124d3a427ac63aa5735451575e707c8645eae86e0fd: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount329076992: archive/tar: invalid tar header: unknown
```

But when i create 2 instances, using --no-cache, gke can create the first container, without problems but the second container, gives me the same error. This leads me to believe that using the cached image locally on the kubernetes cluster breaks something?

**Comment by loxal** [comment]
`--no-cache` does not help me whereas `**--squash-all**` helped me resolving this issue and getting rid of the problematic blob. It's a **workaround** however.

**Comment by dermarens** [comment]
Sadly the --squash option doesn't work for me either when e.g.

1. buildah bud --squash -t image:1.0.0
2. buildah push image:1.0.0
3. buildah tag image:1.0.0 image:latest
4. buildah push image:latest

trying to use image:latest in k3s still fails when trying to pull it from the registry with the known error: `archive/tar: invalid tar header: unknown`. Using image:1.0.0 works though.

**Comment by mtrmac** [comment]
FWIW, as a workaround, it should work to remove `/var/lib/containers/cache/blob-info-cache-v1.boltdb` (if running as root), or `$XDG_DATA_HOME/containers/cache/blob-info-cache-v1.boltdb` (if not).

The cost is that all layers will be re-compressed and re-uploaded instead of mounted on the registry (making both pulls and especially pushes much slower), the file needs to be removed before basically every push, and even this might not help if the image being pushed contains the same layer twice.

**Comment by cdjohnson** [comment]
@mtrmac I found a more serious problem related to this.

If I attempt to push the same tag to docker.io twice in a row, I get a different digest.

If I remove the database as you suggested, then I get the original digest.

```
docker build... -t docker.io/cdjohnson/test:test
podman push docker.io/cdjohnson/test:test
skopeo inspect docker://docker.io/cdjohnson/test:test | jq .Digests
"sha256:8f69f5bcb72ac644ec82a5dd01f56620226e9dc5b0dcf3647a5a3b7b1993f002

podman push docker.io/cdjohnson/test:test
skopeo inspect docker://docker.io/cdjohnson/test:test | jq .Digests
"sha256:29996e2fe0d7bb953724001f8fd23e00c9313a684c2516c12537a6d2cd9af2fa"

rm /var/lib/containers/cache/blob-info-cache-v1.boltdb
podman push docker.io/cdjohnson/test:test
skopeo inspect docker://docker.io/cdjohnson/test:test | jq .Digests
"sha256:8f69f5bcb72ac644ec82a5dd01f56620226e9dc5b0dcf3647a5a3b7b1993f002

```

**Comment by jdockter** [comment]
Any update on this as still seeing this in podman 2.0.x.

**Comment by rhatdan** [comment]
@mtrmac What is going on with this?

**Comment by Frederik-Baetens** [comment]
I just had this issue (or at least [the issue described in my comment above](https://github.com/containers/image/issues/733#issuecomment-602319948) with podman, and rebuilding & repushing with --format docker did seem to fix the issue, but that is a sample size of 1.

**Comment by tvvignesh** [comment]
I am facing the same issue as well.

<img width="779" alt="1" src="https://user-images.githubusercontent.com/1165845/95667280-8e3d4980-0b81-11eb-9075-607c20016cc3.png">

I pruned all images, removed all tags, used no cache and squash all to get it fixed. It might crop up again.

**Comment by tvvignesh** [comment]
This issue is the only pain with using buildah sadly 😢 Everything else works great. I have to rebuild and change the tag everytime this happens.
