### ISSUE TITLE
Have copyUpdatedConfigAndManifest update not rely on src manifest restrictions

### ISSUE THREAD

**Issue by lumjjb** [containers/image#746]
Currently, the way `copyUpdatedConfigAndManifest` in `copy` package updates the manifest is to apply updates to the source manifest and call PutManifest of the modified source manifest. 

The implication is that updates to the manifest that use annotations cannot be done even if the destination supports them. An example of this is in the case of encryption - schemas like docker2 cannot be encrypted even though the destination supports encryption because docker2 struct does not have annotations, which are required.

I can look into this after https://github.com/containers/image/pull/673. Feel free to assign the issue to me.

**Comment by mtrmac** [comment]
“Update destination manifest” is not really possible — the destination manifest, in general, does not exist until `PutManifest`; and we should not upload any user-visible intermediate stages only to somehow read them and edit them again.

This is all an internal in-memory matter of how `image.UpdatedImage` is implemented.

**Comment by lumjjb** [comment]
Ah ok - so maybe something like creating an intermediate manifest representation that we can update in flight before actually putting it to the destination.

**Comment by mtrmac** [comment]
Look at how `UpdatedImage` works, this already almost the case (the _result_ of the conversion is already an in-memory manifest representation).

Basically this amounts to doing the conversion before other edits — and having it comprehensively enough thought through / tested to handle all the corner cases, `UpdatedImageNeedsLayerDiffIDs`, and so on.

**Comment by lumjjb** [comment]
alright - let me take a look at that! Thanks

**Comment by lumjjb** [comment]
Resolved by https://github.com/containers/image/pull/836
