### ISSUE TITLE
Documentation refers to wrong URL

### ISSUE THREAD

**Issue by assarbad** [containers/image#764]
Coming from [here](https://podman.io/getting-started/installation.html) I ended up on [this page](https://github.com/containers/image/blob/master/docs/registries.conf.5.md) after clicking the link that was supposed to lead me to the man page for **registries.conf.5**, but the proper link appears to be [this one instead](https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md) (likely a rename of `registries.conf.5.md` to `containers-registries.conf.5.md`).

I didn't check whether similar issues exist for all URLs, though, but [this is another instance](https://github.com/containers/image/blob/master/docs/policy.json.md) from the same documentation page.

**Comment by rhatdan** [comment]
Could you open a PR to fix this issue?

**Comment by assarbad** [comment]
@rhatdan frankly I had no idea where to even look.

But then sifting through the list of repos I came up with [this](https://github.com/containers/podman.io/blob/master/getting-started/index.md) ... so send a PR there, I presume and close _this one_?

**Comment by rhatdan** [comment]
Yes that sounds good.

**Comment by assarbad** [comment]
@rhatdan sent [a PR](https://github.com/containers/podman.io/pull/164) as promised.

**Comment by rhatdan** [comment]
Thanks @assarbad, merged
