### ISSUE TITLE
Drop the architecture check in checkImageDestinationForCurrentRuntime

### ISSUE THREAD

**Issue by mtrmac** [containers/image#799]
Per recent Buildah / Podman reports, apparently pulling different-architecture images is fairly common; so, revert/undo #752.

**Comment by vrothberg** [comment]
I suggest to not revert the previous changes entirely but to `logrus.Info` instead of returning the error. The motivation would be to make users aware of the issue. I am somehow quite surprised that the k8s pause image issue hasn't been detected earlier.

**Comment by mtrmac** [comment]
Sure.

**Comment by vrothberg** [comment]
Fixed with https://github.com/containers/image/pull/804. Sorry for missing that in the commit message!
