### ISSUE TITLE
move docker/* under docker/registry/*

### ISSUE THREAD

**Issue by runcom** [containers/image#85]
If we end up having another transport named `docker-daemon:` (or whatever the naming will be) - we would move the implementation under `docker/*` to be `docker/registry/*` and have `github.com/containers/image/docker/registry` package (and `docker/daemon` ofc).

**Comment by rhatdan** [comment]
@runcom @mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
Yup.

**Comment by mtrmac** [comment]
I think this is still a good idea, but maybe we don’t quite need to track this, and with the move to semantic versioning there’s more resistance to non-feature cleanups like these.

**Comment by mtrmac** [comment]
… and the OCI distribution spec might arrive and ruffle the design/naming soon enough anyway.
