### ISSUE TITLE
dockerImageDestination.SupportedManifestMIMETypes may be incorrect

### ISSUE THREAD

**Issue by mtrmac** [containers/image#86]
`dockerImageDestination.SupportedManifestMIMETypes` returns a hard-coded value; if the destination registry does not in fact support schema 2, we would still attempt to upload this.

This incorrect information will break any manifest conversion we might attempt.

**Comment by runcom** [comment]
We should probably test if V2 is really supported, otherwise fallback to push v2s1?

**Comment by mtrmac** [comment]
Yes. It would be very convenient if we could determine v2 support without having to create and try to push v2, I am not sure whether that is possible.

**Comment by runcom** [comment]
@mtrmac it should be easy https://github.com/docker/docker/blob/master/distribution/push_v2.go#L159-L193

**Comment by mtrmac** [comment]
Yeah, that is the “convert and try” method which I’d like to avoid :)

**Comment by runcom** [comment]
> Yeah, that is the “convert and try” method which I’d like to avoid :)

can it work with this "convert and try" though?

**Comment by mtrmac** [comment]
> > Yeah, that is the “convert and try” method which I’d like to avoid :)

> can it work with this "convert and try" though?

Sure, it is software, we can build anything we can specify. But with the increasing number of formats (schema1, schema2, OCI, perhaps even native Docker tar exposed to `copy.go`), the conversion engine will need to do a series of false starts instead of just statically detecting the optimal destination format and doing a single conversion. Doable but ugly.

**Comment by mtrmac** [comment]
#88 implements the “convert and try” method. At least with the OpenShift `acceptschema2` option, there is no way to tell what is supported other than try to push a manifest.
