### ISSUE TITLE
no image found in manifest list for architecture amd64, variant v7, OS linux

### ISSUE THREAD

**Issue by crazy-max** [containers/image#864]
Hi,

It looks like #854 adds a new field `platform.variant` that is not available for some multi-arch image. For example image manifest of `grafana/grafana:6.7.1` does not include any `variant` field for `platform`:

```
λ docker manifest inspect grafana/grafana:6.7.1
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1997,
         "digest": "sha256:9d43bebe9f3a5d27647231e1fa760644fafcc09a1ad85eeae1df40c491841bd9",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1575,
         "digest": "sha256:e5c033be6235bb1cb8c55153223f83ae7580c7a29adea2c17d671b2f68df9b11",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1575,
         "digest": "sha256:b624750e7cdd78634b58047400a9e172b9055e1f03284afc332d7402eeaab15e",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

Any hint to handle `platform.variant` correctly?

Logs and more info in crazy-max/diun#54

Thanks!

**Comment by mtrmac** [comment]
Thanks for your report.

To confirm, you are _running_ this on ARM, but the configuration is something like https://github.com/crazy-max/diun/blob/bac975009afbc4aa802913ecc0c314957fa0a1d6/pkg/registry/registry.go#L42-L49 with an `ArchitectureChoice: "amd64"`?

That looks like an oversight with no workaround, stay tuned.

**Comment by mtrmac** [comment]
Can you verify that https://github.com/containers/image/pull/865 fixes this, please?

**Comment by crazy-max** [comment]
Hi @mtrmac, thanks for your quick response. Will check this out.

**Comment by crazy-max** [comment]
> To confirm, you are running this on ARM, but the configuration is something like https://github.com/crazy-max/diun/blob/bac975009afbc4aa802913ecc0c314957fa0a1d6/pkg/registry/registry.go#L42-L49 with an ArchitectureChoice: "amd64"?

Yes indeed. I've added these defaults in case a static analysis of the manifest is performed. For example if a user performs the scan on windows and tries to fetch the manifest of an image that is only available for linux/amd64, the scan will fail. I will review this process in my application.
