### ISSUE TITLE
Windows Variant detection based on Arch

### ISSUE THREAD

**Issue by grooverdan** [containers/image#875]
In getCPUVariant here, https://github.com/containers/image/blob/master/internal/pkg/platform/platform_matcher.go#L110, shouldn't we be passing the `arch` argument so that `getCPUVariantWindows` doesn't base it on the runtime?

**Comment by mtrmac** [comment]
AFAICS `getCPUVariant` is currently only called if `ctx.ArchitectureChoice` is not specified, so `arch` would be `runtime.GOARCH` anyway. Admittedly the global reference to `runtime.GOARCH` inside is redundant, but that’s a micro-optimization.

**Comment by grooverdan** [comment]
yep, you're right. pr to clean it up anyway :)
