### ISSUE TITLE
There seems to be two man pages for /etc/containers-registries.d

### ISSUE THREAD

**Issue by rhatdan** [containers/image#894]
ls  ./docs/containers-registries*d*md
./docs/containers-registries.conf.d.5.md  ./docs/containers-registries.d.5.md

Are they supposed to be there or should we consolodate?

**Comment by rhatdan** [comment]
@vrothberg @mtrmac PTAL

**Comment by vrothberg** [comment]
They are serving different purposes. `registries.conf.d` is describing the drop-in configs we introduced for OpenShift. `regisries.d` pre-dates that by far and can be used, for instance, to configure custom sigstores. I can't see how we could merge the two.

**Comment by rhatdan** [comment]
I see that as incredible confusing especially where the names are so close.  And 15 minutes after you described them I would not be able to tell which is which.

**Comment by mtrmac** [comment]
Yes, how we evolutionally ended up with many specialized config files ends up difficult to use. Also https://github.com/containers/skopeo/issues/849 .
