### ISSUE TITLE
Do not use 0755 permission for files and dirs

### ISSUE THREAD

**Issue by CooperLi** [containers/image#974]
Some files should not have 0755 permissions (especially **auth.json**). Nothing serious as of now. But, still ;-)

```bash
$ grep -Erni "0?755"                                                                                                                                                  
pkg/docker/config/config.go:348:                if err = ioutil.WriteFile(path, newData, 0755); err != nil {                                                          
Makefile:53:    install -d -m 755 ${MANINSTALLDIR}/man5                                                                                                               
oci/layout/oci_dest.go:319:             if err := os.MkdirAll(path, 0755); err != nil {                                                                               
.
.
.                                  
```

**Comment by mtrmac** [comment]
Thanks for your report. You’re right about `auth.json`; but why should the directories not be 0755? Especially the man pages should be accessible by all users if installed system-wide, but even for the OCI files, the general convention is to make files group/user readable and limit that by umask, AFAIK.

**Comment by CooperLi** [comment]
ping @mtrmac 
You are right about it, we need to consider the permission about `auth.json` first and leave the dir to the umask for example :-)
