### ISSUE TITLE
Memory leak if copy canceled in the middle.

### ISSUE THREAD

**Issue by ajayr2512** [containers/image#983]
Calling cancel in middle of an operation causes a leak. (calling https://github.com/containers/image/blob/v5.5.1/copy/copy.go#L202 to copy image from one registry to another).
Notice that the function doesn't return at all. 
After further debugging, the stack trace seems to be hinting at a block in https://github.com/containers/image/blob/v5.5.1/copy/copy.go#L854.
Also, looking at the stack trace related to copyLayer() .. This is the path observed:
https://github.com/containers/image/blob/v5.5.1/copy/copy.go#L827 =>
https://github.com/containers/image/blob/v5.5.1/copy/copy.go#L1082 =>
https://github.com/containers/image/blob/v5.5.1/copy/copy.go#L984 =>
https://github.com/vbauerster/mpb/blob/v5.0.4/progress.go#L103 =>
https://github.com/vbauerster/mpb/blob/v5.0.4/progress.go#L135 =>
https://github.com/vbauerster/mpb/blob/v5.0.4/bar.go#L363 =>
https://github.com/vbauerster/mpb/blob/v5.0.4/bar.go#L161

Additionally, Is there a way to not use 'progress' at all completely ?

**Comment by mtrmac** [comment]
Thanks for the report.

Could you clarify what you see exactly? Is this a leak or hang, then? Is there a way to reproduce?

And as you have probably seen, there isn’t a branch to avoid those code paths. We don’t much want one, either: if there are bugs, let’s just fix them.

**Comment by ajayr2512** [comment]
This is a hang, i.e notice function never returns. Other words, looks like the routine is blocked.
In terms of reproducing, it is not exactly reproducible every time. Run the function in a loop and send out cancel after random amount of time. Can get it to hang when I send out the cancel at the right time (which usually I notice tends to be around 2-5 secs). 
Will post a code sample if required.

**Comment by mtrmac** [comment]
From a quick look, this seems to be a progress bar bug — the `TraverseDecorators`, as well as probably several other places, needs to `select{ case b.operateState <- …: …; case <- b.done: … }`, because `Bar.serve` terminates if the context is canceled, but that does not automatically mean no further calls that rely on `Bar.serve` running will happen.

But I haven’t created a reproducer to confirm yet.

**Comment by ajayr2512** [comment]
Thanks for the update. Is this something that should be reported to the progress repo then ?

**Comment by mtrmac** [comment]
Thanks for reporting it upstream; this should be fixed with the update in #988 , then.

**Comment by ajayr2512** [comment]
Yes. Closing the issue thanks.
